; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.anon.2, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, i32, i8, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.rb_id_table*, [1023 x %struct.rb_callcache*], %struct.anon.9, [29 x i16] }
%struct.anon.2 = type { %struct.list_head, i32, i32, %struct.rb_ractor_struct*, %struct.rb_thread_struct*, %struct.anon.3 }
%struct.rb_ractor_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_ractor_struct*, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_waiting_list*, %union.anon.12, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64, i32, i64, %struct.rb_ext_config, i8* }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.rb_id_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.16 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.15, i32, i32, i32, i32, i8, i8, %struct.rb_id_table* }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.anon.1 }
%struct.anon.1 = type { %struct.rb_thread_struct*, i64 }
%struct.rb_call_data = type { %struct.rb_callinfo*, %struct.rb_callcache* }
%struct.rb_callinfo = type { i64, %struct.rb_callinfo_kwarg*, i64, i64, i64 }
%struct.rb_callinfo_kwarg = type { i32, [0 x i64] }
%struct.rb_callcache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*)*, %union.__atomic_wide_counter }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.__atomic_wide_counter = type { i64 }
%struct.anon.15 = type { i64, i64, i64, i64* }
%union.anon.16 = type { %struct.anon.17 }
%struct.anon.17 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { %struct.rb_callinfo*, %struct.rb_callcache*, i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.11 }
%union.anon.11 = type { %union.pthread_cond_t }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.__atomic_wide_counter, %union.__atomic_wide_counter, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_waiting_list = type { %struct.rb_waiting_list*, %struct.rb_thread_struct*, %struct.rb_fiber_struct* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.rb_ext_config = type { i8 }
%struct.anon.3 = type { %union.pthread_mutex_t, %struct.rb_ractor_struct*, i32, i8, i32, %union.pthread_cond_t, %union.pthread_cond_t, i8 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.rb_id_table = type opaque
%struct.anon.9 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_call_data }
%struct.RBasic = type { i64, i64 }

@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@sorbet_getTRetry.retry = internal constant [25 x i8] c"T::Private::Retry::RETRY\00", align 16
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_ec = external thread_local local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@"stackFramePrecomputed_func_<root>.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@iseqEncodedArray = internal global [28 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@ic_test = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_test.2 = internal global %struct.FunctionInlineCache zeroinitializer
@"stackFramePrecomputed_func_A.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@stackFramePrecomputed_func_A.4test = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_A.4test$block_2" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_A.4test$block_3" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"<retry-singleton>" = internal unnamed_addr global i64 0
@ic_puts.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_raise = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_===" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.5 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.7 = internal global %struct.FunctionInlineCache zeroinitializer
@sorbet_moduleStringTable = internal unnamed_addr constant [281 x i8] c"<top (required)>\00test/testdata/compiler/exceptions/basic.rb\00A\00Object\00=== no-raise ===\00puts\00test\00=== raise ===\00master\00<class:A>\00normal\00x\00<exceptionValue>\00<returnMethodTemp>\00e\00<gotoDeadTemp>\00rescue in test\00ensure in test\00begin\00foo\00raise\00StandardError\00Module\00===\00else\00T\00unsafe\00ensure\00", align 1
@sorbet_moduleIDTable = internal unnamed_addr global [15 x i64] zeroinitializer, align 8
@sorbet_moduleIDDescriptors = internal unnamed_addr constant [15 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 86, i32 4 }, %struct.rb_code_position_struct { i32 91, i32 4 }, %struct.rb_code_position_struct { i32 117, i32 9 }, %struct.rb_code_position_struct { i32 127, i32 6 }, %struct.rb_code_position_struct { i32 134, i32 1 }, %struct.rb_code_position_struct { i32 136, i32 16 }, %struct.rb_code_position_struct { i32 153, i32 18 }, %struct.rb_code_position_struct { i32 172, i32 1 }, %struct.rb_code_position_struct { i32 174, i32 14 }, %struct.rb_code_position_struct { i32 189, i32 14 }, %struct.rb_code_position_struct { i32 204, i32 14 }, %struct.rb_code_position_struct { i32 229, i32 5 }, %struct.rb_code_position_struct { i32 256, i32 3 }, %struct.rb_code_position_struct { i32 267, i32 6 }], align 8
@sorbet_moduleRubyStringTable = internal unnamed_addr global [12 x i64] zeroinitializer, align 8
@sorbet_moduleRubyStringDescriptors = internal unnamed_addr constant [12 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 17, i32 42 }, %struct.rb_code_position_struct { i32 69, i32 16 }, %struct.rb_code_position_struct { i32 96, i32 13 }, %struct.rb_code_position_struct { i32 117, i32 9 }, %struct.rb_code_position_struct { i32 91, i32 4 }, %struct.rb_code_position_struct { i32 189, i32 14 }, %struct.rb_code_position_struct { i32 204, i32 14 }, %struct.rb_code_position_struct { i32 219, i32 5 }, %struct.rb_code_position_struct { i32 225, i32 3 }, %struct.rb_code_position_struct { i32 260, i32 4 }, %struct.rb_code_position_struct { i32 274, i32 6 }], align 8
@rb_cObject = external local_unnamed_addr constant i64
@guard_epoch_A = linkonce local_unnamed_addr global i64 0
@guarded_const_A = linkonce local_unnamed_addr global i64 0
@rb_eStandardError = external local_unnamed_addr constant i64
@rb_cModule = external local_unnamed_addr constant i64

declare i64 @rb_ary_push(i64 noundef, i64 noundef) local_unnamed_addr #0

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i64 @rb_id2sym(i64 noundef) local_unnamed_addr #1

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i64 @rb_obj_is_kind_of(i64 noundef, i64 noundef) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32 noundef, i32 noundef, i32 noundef) local_unnamed_addr #2

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef, i64 noundef, i64 noundef, i64 noundef, %struct.rb_iseq_struct* noundef, i32 noundef, i32 noundef, %struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef) local_unnamed_addr #0

declare i64 @sorbet_getConstant(i8* noundef, i64 noundef) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64 noundef) local_unnamed_addr #0

declare void @sorbet_popFrame() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef, i64 noundef, i32 noundef, i32 noundef, i32 noundef, ...) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef, i64 noundef) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #0

declare void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #0

declare void @sorbet_vm_define_method(i64 noundef, i8* noundef, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef, i8* noundef, %struct.rb_iseq_struct* noundef, i1 noundef zeroext) local_unnamed_addr #0

declare void @sorbet_vm_intern_ids(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

declare void @sorbet_vm_init_string_table(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

declare i64 @sorbet_run_exception_handling(%struct.rb_execution_context_struct* noundef, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef, i64** noundef, i64 noundef, %struct.rb_control_frame_struct* noundef, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef, i64 noundef, i64 noundef, i64 noundef) local_unnamed_addr #0

declare i64 @rb_define_class(i8* noundef, i64 noundef) local_unnamed_addr #0

; Function Attrs: argmemonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #3

; Function Attrs: argmemonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #3

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #4

declare i64 @rb_ary_new_capa(i64 noundef) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64 noundef, i8* noundef, ...) local_unnamed_addr #2

declare i64 @rb_ary_entry(i64 noundef, i64 noundef) local_unnamed_addr #0

declare void @rb_ary_store(i64 noundef, i64 noundef, i64 noundef) local_unnamed_addr #0

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #4

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef, i32 noundef) local_unnamed_addr #0

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64 noundef, i64 noundef) local_unnamed_addr #5

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xmalloc2(i64 noundef, i64 noundef) local_unnamed_addr #5

; Function Attrs: argmemonly mustprogress nocallback nofree nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #6

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #7 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i32 0, i32 0)) #10
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #7 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i32 0, i32 0)) #10
  unreachable
}

define void @Init_basic() local_unnamed_addr {
entry:
  %positional_table.i.i = alloca i64, align 8, !dbg !9
  %locals.i11.i = alloca i64, i32 5, align 8
  %locals.i9.i = alloca i64, i32 0, align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  tail call void @sorbet_vm_intern_ids(i64* noundef getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([15 x %struct.rb_code_position_struct], [15 x %struct.rb_code_position_struct]* @sorbet_moduleIDDescriptors, i32 0, i32 0), i32 noundef 15, i8* noundef getelementptr inbounds ([281 x i8], [281 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_vm_init_string_table(i64* noundef getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([12 x %struct.rb_code_position_struct], [12 x %struct.rb_code_position_struct]* @sorbet_moduleRubyStringDescriptors, i32 0, i32 0), i32 noundef 12, i8* noundef getelementptr inbounds ([281 x i8], [281 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 28)
  %"rubyId_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), align 8, !invariant.load !14
  %"rubyStr_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), align 8, !invariant.load !14
  %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 1), align 8, !invariant.load !14
  %0 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<top (required)>.i.i", i64 noundef %"rubyId_<top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %0, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %rubyId_puts.i = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 1), align 8, !dbg !17, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !17
  %rubyId_test.i = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 2), align 8, !dbg !18, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test, i64 noundef %rubyId_test.i, i32 noundef 16, i32 noundef 1, i32 noundef 0), !dbg !18
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.1, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !19
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_test.2, i64 noundef %rubyId_test.i, i32 noundef 16, i32 noundef 1, i32 noundef 0), !dbg !20
  %"rubyId_<class:A>.i.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 3), align 8, !invariant.load !14
  %"rubyStr_<class:A>.i.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 4), align 8, !invariant.load !14
  %1 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<class:A>.i.i", i64 noundef %"rubyId_<class:A>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 3, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i9.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %1, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.13<static-init>", align 8
  %2 = bitcast i64* %locals.i11.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 40, i8* nonnull %2)
  %rubyStr_test.i.i = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 5), align 8, !invariant.load !14
  %3 = load <4 x i64>, <4 x i64>* bitcast (i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 5) to <4 x i64>*), align 8, !invariant.load !14
  %shuffle = shufflevector <4 x i64> %3, <4 x i64> poison, <4 x i32> <i32 1, i32 0, i32 2, i32 3>
  %4 = bitcast i64* %locals.i11.i to <4 x i64>*
  store <4 x i64> %shuffle, <4 x i64>* %4, align 8
  %"rubyId_<gotoDeadTemp>.i.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 9), align 8, !invariant.load !14
  %5 = getelementptr i64, i64* %locals.i11.i, i32 4
  store i64 %"rubyId_<gotoDeadTemp>.i.i", i64* %5, align 8
  %6 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_test.i.i, i64 noundef %rubyId_test.i, i64 noundef %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull align 8 %locals.i11.i, i32 noundef 5, i32 noundef 2)
  store %struct.rb_iseq_struct* %6, %struct.rb_iseq_struct** @stackFramePrecomputed_func_A.4test, align 8
  call void @llvm.lifetime.end.p0i8(i64 40, i8* nonnull %2)
  %"rubyId_rescue in test.i.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 10), align 8, !invariant.load !14
  %"rubyStr_rescue in test.i.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 6), align 8, !invariant.load !14
  %7 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_rescue in test.i.i", i64 noundef %"rubyId_rescue in test.i.i", i64 noundef %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef %6, i32 noundef 4, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %7, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.4test$block_2", align 8
  %stackFrame.i13.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_A.4test, align 8
  %"rubyId_ensure in test.i.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 11), align 8, !invariant.load !14
  %"rubyStr_ensure in test.i.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 7), align 8, !invariant.load !14
  %8 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_ensure in test.i.i", i64 noundef %"rubyId_ensure in test.i.i", i64 noundef %"rubyStr_test/testdata/compiler/exceptions/basic.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef %stackFrame.i13.i, i32 noundef 5, i32 noundef 6, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %8, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.4test$block_3", align 8
  %9 = call i64 @sorbet_getConstant(i8* noundef getelementptr inbounds ([25 x i8], [25 x i8]* @sorbet_getTRetry.retry, i32 0, i32 0), i64 noundef 25) #11
  store i64 %9, i64* @"<retry-singleton>", align 8
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.3, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !21
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.4, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !25
  %rubyId_raise.i = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 12), align 8, !dbg !26, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_raise, i64 noundef %rubyId_raise.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !26
  %"rubyId_===.i" = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 13), align 8, !dbg !27, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_===", i64 noundef %"rubyId_===.i", i32 noundef 16, i32 noundef 1, i32 noundef 0), !dbg !27
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.5, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !29
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.6, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !30
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.7, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !32
  %10 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !34
  %11 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %10, i64 0, i32 12
  %12 = load i64, i64* %11, align 8, !tbaa !36
  %13 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %14 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %13, i64 0, i32 2
  %15 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %14, align 8, !tbaa !47
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %16 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %16, align 8, !tbaa !50
  %17 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 4
  %18 = load i64*, i64** %17, align 8, !tbaa !52
  %19 = load i64, i64* %18, align 8, !tbaa !5
  %20 = and i64 %19, -33
  store i64 %20, i64* %18, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %13, %struct.rb_control_frame_struct* noundef %15, %struct.rb_iseq_struct* noundef %stackFrame.i) #11
  %21 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %21, align 8, !tbaa !34
  %22 = load i64, i64* @rb_cObject, align 8, !dbg !53
  %23 = call i64 @rb_define_class(i8* noundef getelementptr inbounds ([281 x i8], [281 x i8]* @sorbet_moduleStringTable, i64 0, i64 60), i64 noundef %22) #11, !dbg !53
  %24 = call %struct.rb_control_frame_struct* @sorbet_pushStaticInitFrame(i64 noundef %23) #11, !dbg !53
  %25 = bitcast i64* %positional_table.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %25)
  %stackFrame.i.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.13<static-init>", align 8
  %26 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %27 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %26, i64 0, i32 2
  %28 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %27, align 8, !tbaa !47
  %29 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %28, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i.i, %struct.rb_iseq_struct** %29, align 8, !tbaa !50
  %30 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %28, i64 0, i32 4
  %31 = load i64*, i64** %30, align 8, !tbaa !52
  %32 = load i64, i64* %31, align 8, !tbaa !5
  %33 = and i64 %32, -33
  store i64 %33, i64* %31, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %26, %struct.rb_control_frame_struct* noundef %28, %struct.rb_iseq_struct* noundef %stackFrame.i.i) #11
  %34 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %24, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %34, align 8, !dbg !54, !tbaa !34
  %rawSym.i.i = call noundef i64 @rb_id2sym(i64 noundef %rubyId_test.i), !dbg !9
  %35 = and i64 %rawSym.i.i, 255, !dbg !9
  %36 = icmp eq i64 %35, 12, !dbg !9
  br i1 %36, label %sorbet_isa_Symbol.exit, label %37, !dbg !9

37:                                               ; preds = %entry
  %38 = and i64 %rawSym.i.i, 7, !dbg !9
  %39 = icmp ne i64 %38, 0, !dbg !9
  %40 = and i64 %rawSym.i.i, -9, !dbg !9
  %41 = icmp eq i64 %40, 0, !dbg !9
  %42 = or i1 %39, %41, !dbg !9
  br i1 %42, label %sorbet_isa_Symbol.exit, label %43, !dbg !9

43:                                               ; preds = %37
  %44 = inttoptr i64 %rawSym.i.i to %struct.RBasic*, !dbg !9
  %45 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %44, i64 0, i32 0, !dbg !9
  %46 = load i64, i64* %45, align 8, !dbg !9, !tbaa !55
  %47 = and i64 %46, 31, !dbg !9
  %48 = icmp eq i64 %47, 20, !dbg !9
  br label %sorbet_isa_Symbol.exit, !dbg !9

sorbet_isa_Symbol.exit:                           ; preds = %entry, %37, %43
  %49 = phi i1 [ true, %entry ], [ %48, %43 ], [ false, %37 ], !dbg !9
  call void @llvm.assume(i1 noundef %49), !dbg !9
  %rubyId_normal.i.i = load i64, i64* getelementptr inbounds ([15 x i64], [15 x i64]* @sorbet_moduleIDTable, i64 0, i64 4), align 8, !dbg !9, !invariant.load !14
  %rawSym6.i.i = call i64 @rb_id2sym(i64 noundef %rubyId_normal.i.i), !dbg !9
  %50 = and i64 %rawSym6.i.i, 255, !dbg !9
  %51 = icmp eq i64 %50, 12, !dbg !9
  br i1 %51, label %sorbet_isa_Symbol.exit9, label %52, !dbg !9

52:                                               ; preds = %sorbet_isa_Symbol.exit
  %53 = and i64 %rawSym6.i.i, 7, !dbg !9
  %54 = icmp ne i64 %53, 0, !dbg !9
  %55 = and i64 %rawSym6.i.i, -9, !dbg !9
  %56 = icmp eq i64 %55, 0, !dbg !9
  %57 = or i1 %54, %56, !dbg !9
  br i1 %57, label %sorbet_isa_Symbol.exit9, label %58, !dbg !9

58:                                               ; preds = %52
  %59 = inttoptr i64 %rawSym6.i.i to %struct.RBasic*, !dbg !9
  %60 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %59, i64 0, i32 0, !dbg !9
  %61 = load i64, i64* %60, align 8, !dbg !9, !tbaa !55
  %62 = and i64 %61, 31, !dbg !9
  %63 = icmp eq i64 %62, 20, !dbg !9
  br label %sorbet_isa_Symbol.exit9, !dbg !9

sorbet_isa_Symbol.exit9:                          ; preds = %sorbet_isa_Symbol.exit, %52, %58
  %64 = phi i1 [ true, %sorbet_isa_Symbol.exit ], [ %63, %58 ], [ false, %52 ], !dbg !9
  call void @llvm.assume(i1 noundef %64), !dbg !9
  %65 = load i64, i64* @guard_epoch_A, align 8, !dbg !9
  %66 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !9, !tbaa !57
  %needTakeSlowPath = icmp ne i64 %65, %66, !dbg !9
  br i1 %needTakeSlowPath, label %67, label %68, !dbg !9, !prof !58

67:                                               ; preds = %sorbet_isa_Symbol.exit9
  call void @const_recompute_A(), !dbg !9
  br label %68, !dbg !9

68:                                               ; preds = %sorbet_isa_Symbol.exit9, %67
  %69 = load i64, i64* @guarded_const_A, align 8, !dbg !9
  %70 = load i64, i64* @guard_epoch_A, align 8, !dbg !9
  %71 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !9, !tbaa !57
  %guardUpdated = icmp eq i64 %70, %71, !dbg !9
  call void @llvm.assume(i1 %guardUpdated), !dbg !9
  %stackFrame7.i.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @stackFramePrecomputed_func_A.4test, align 8, !dbg !9
  %72 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #12, !dbg !9
  %73 = bitcast i8* %72 to i16*, !dbg !9
  %74 = load i16, i16* %73, align 8, !dbg !9
  %75 = and i16 %74, -384, !dbg !9
  %76 = or i16 %75, 1, !dbg !9
  store i16 %76, i16* %73, align 8, !dbg !9
  %77 = getelementptr inbounds i8, i8* %72, i64 12, !dbg !9
  %78 = getelementptr inbounds i8, i8* %72, i64 4, !dbg !9
  %79 = bitcast i8* %78 to i32*, !dbg !9
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %77, i8 0, i64 20, i1 false), !dbg !9
  %80 = bitcast i32* %79 to <2 x i32>*, !dbg !9
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %80, align 4, !dbg !9, !tbaa !59
  %81 = extractelement <4 x i64> %3, i32 0, !dbg !9
  store i64 %81, i64* %positional_table.i.i, align 8, !dbg !9
  %82 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #12, !dbg !9
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %82, i8* noundef nonnull align 1 %25, i64 noundef 8, i1 noundef false), !dbg !9
  %83 = getelementptr inbounds i8, i8* %72, i64 32, !dbg !9
  %84 = bitcast i8* %83 to i8**, !dbg !9
  store i8* %82, i8** %84, align 8, !dbg !9, !tbaa !60
  call void @sorbet_vm_define_method(i64 noundef %69, i8* noundef getelementptr inbounds ([281 x i8], [281 x i8]* @sorbet_moduleStringTable, i64 0, i64 91), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @func_A.4test, i8* noundef nonnull %72, %struct.rb_iseq_struct* noundef %stackFrame7.i.i, i1 noundef zeroext true) #11, !dbg !9
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %25)
  call void @sorbet_popFrame() #11, !dbg !53
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 23), i64** %21, align 8, !dbg !53, !tbaa !34
  %"rubyStr_=== no-raise ===.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 2), align 8, !dbg !63, !invariant.load !14
  %85 = and i64 %"rubyStr_=== no-raise ===.i", 7, !dbg !63
  %86 = icmp ne i64 %85, 0, !dbg !63
  %87 = and i64 %"rubyStr_=== no-raise ===.i", -9, !dbg !63
  %88 = icmp eq i64 %87, 0, !dbg !63
  %89 = or i1 %86, %88, !dbg !63
  br i1 %89, label %sorbet_isa_String.exit8, label %90, !dbg !63

90:                                               ; preds = %68
  %91 = inttoptr i64 %"rubyStr_=== no-raise ===.i" to %struct.RBasic*, !dbg !63
  %92 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %91, i64 0, i32 0, !dbg !63
  %93 = load i64, i64* %92, align 8, !dbg !63, !tbaa !55
  %94 = and i64 %93, 31, !dbg !63
  %95 = icmp eq i64 %94, 5, !dbg !63
  br label %sorbet_isa_String.exit8, !dbg !63

sorbet_isa_String.exit8:                          ; preds = %68, %90
  %96 = phi i1 [ false, %68 ], [ %95, %90 ], !dbg !63
  call void @llvm.assume(i1 noundef %96), !dbg !63
  %97 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 1, !dbg !17
  %98 = load i64*, i64** %97, align 8, !dbg !17
  store i64 %12, i64* %98, align 8, !dbg !17, !tbaa !5
  %99 = getelementptr inbounds i64, i64* %98, i64 1, !dbg !17
  store i64 %"rubyStr_=== no-raise ===.i", i64* %99, align 8, !dbg !17, !tbaa !5
  %100 = getelementptr inbounds i64, i64* %99, i64 1, !dbg !17
  store i64* %100, i64** %97, align 8, !dbg !17
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !17
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 24), i64** %21, align 8, !dbg !17, !tbaa !34
  %101 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 1, !dbg !18
  %102 = load i64*, i64** %101, align 8, !dbg !18
  store i64 %69, i64* %102, align 8, !dbg !18, !tbaa !5
  %103 = getelementptr inbounds i64, i64* %102, i64 1, !dbg !18
  store i64 0, i64* %103, align 8, !dbg !18, !tbaa !5
  %104 = getelementptr inbounds i64, i64* %103, i64 1, !dbg !18
  store i64* %104, i64** %101, align 8, !dbg !18
  %send3 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test, i64 0), !dbg !18
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 26), i64** %21, align 8, !dbg !18, !tbaa !34
  %"rubyStr_=== raise ===.i" = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 3), align 8, !dbg !64, !invariant.load !14
  %105 = and i64 %"rubyStr_=== raise ===.i", 7, !dbg !64
  %106 = icmp ne i64 %105, 0, !dbg !64
  %107 = and i64 %"rubyStr_=== raise ===.i", -9, !dbg !64
  %108 = icmp eq i64 %107, 0, !dbg !64
  %109 = or i1 %106, %108, !dbg !64
  br i1 %109, label %sorbet_isa_String.exit, label %110, !dbg !64

110:                                              ; preds = %sorbet_isa_String.exit8
  %111 = inttoptr i64 %"rubyStr_=== raise ===.i" to %struct.RBasic*, !dbg !64
  %112 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %111, i64 0, i32 0, !dbg !64
  %113 = load i64, i64* %112, align 8, !dbg !64, !tbaa !55
  %114 = and i64 %113, 31, !dbg !64
  %115 = icmp eq i64 %114, 5, !dbg !64
  br label %sorbet_isa_String.exit, !dbg !64

sorbet_isa_String.exit:                           ; preds = %sorbet_isa_String.exit8, %110
  %116 = phi i1 [ false, %sorbet_isa_String.exit8 ], [ %115, %110 ], !dbg !64
  call void @llvm.assume(i1 noundef %116), !dbg !64
  %117 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 1, !dbg !19
  %118 = load i64*, i64** %117, align 8, !dbg !19
  store i64 %12, i64* %118, align 8, !dbg !19, !tbaa !5
  %119 = getelementptr inbounds i64, i64* %118, i64 1, !dbg !19
  store i64 %"rubyStr_=== raise ===.i", i64* %119, align 8, !dbg !19, !tbaa !5
  %120 = getelementptr inbounds i64, i64* %119, i64 1, !dbg !19
  store i64* %120, i64** %117, align 8, !dbg !19
  %send5 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.1, i64 0), !dbg !19
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 27), i64** %21, align 8, !dbg !19, !tbaa !34
  %121 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %15, i64 0, i32 1, !dbg !20
  %122 = load i64*, i64** %121, align 8, !dbg !20
  store i64 %69, i64* %122, align 8, !dbg !20, !tbaa !5
  %123 = getelementptr inbounds i64, i64* %122, i64 1, !dbg !20
  store i64 20, i64* %123, align 8, !dbg !20, !tbaa !5
  %124 = getelementptr inbounds i64, i64* %123, i64 1, !dbg !20
  store i64* %124, i64** %121, align 8, !dbg !20
  %send7 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_test.2, i64 0), !dbg !20
  ret void
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @func_A.4test(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #8 !dbg !23 {
functionEntryInitializers:
  %0 = tail call i64 @rb_ary_new_capa(i64 noundef 5) #11
  br label %1

1:                                                ; preds = %1, %functionEntryInitializers
  %2 = phi i32 [ %4, %1 ], [ 0, %functionEntryInitializers ]
  %3 = tail call i64 @rb_ary_push(i64 noundef %0, i64 noundef 8) #11
  %4 = add nuw nsw i32 %2, 1
  %5 = icmp eq i32 %4, 5
  br i1 %5, label %sorbet_allocateEscapedVarsArray.exit, label %1, !llvm.loop !65

sorbet_allocateEscapedVarsArray.exit:             ; preds = %1
  %6 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %6, align 8, !tbaa !34
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !67
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !67
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !67
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !67, !prof !68

postProcess:                                      ; preds = %fillRequiredArgs, %exception-continue
  %"<returnValue>.sroa.0.0" = phi i64 [ %10, %exception-continue ], [ %9, %fillRequiredArgs ], !dbg !69
  ret i64 %"<returnValue>.sroa.0.0"

argCountFailBlock:                                ; preds = %sorbet_allocateEscapedVarsArray.exit
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #13, !dbg !67
  unreachable, !dbg !67

fillRequiredArgs:                                 ; preds = %sorbet_allocateEscapedVarsArray.exit
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !67
  tail call void @rb_ary_store(i64 noundef %0, i64 noundef 1, i64 noundef %rawArg_x) #11, !dbg !67
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %6, align 8, !tbaa !34
  %7 = tail call i64 @rb_ary_entry(i64 noundef %0, i64 noundef 1) #11, !dbg !70
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %6, align 8, !dbg !70, !tbaa !34
  %8 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !71, !tbaa !34
  %"<retry-singleton>" = load i64, i64* @"<retry-singleton>", align 8, !dbg !71
  %9 = tail call i64 @sorbet_run_exception_handling(%struct.rb_execution_context_struct* noundef %8, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef @"func_A.4test$block_1", i64** noundef nonnull %6, i64 noundef %0, %struct.rb_control_frame_struct* noundef nonnull %cfp, i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef @"func_A.4test$block_2", i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef @"func_A.4test$block_4", i64 (i64**, i64, %struct.rb_control_frame_struct*)* noundef @"func_A.4test$block_3", i64 noundef %"<retry-singleton>", i64 noundef 0, i64 noundef 0), !dbg !71
  %ensureReturnValue = icmp ne i64 %9, 52, !dbg !71
  br i1 %ensureReturnValue, label %postProcess, label %exception-continue, !dbg !71

exception-continue:                               ; preds = %fillRequiredArgs
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 20), i64** %6, align 8, !tbaa !34
  %10 = tail call i64 @rb_ary_entry(i64 noundef %0, i64 noundef 2) #11, !dbg !72
  br label %postProcess, !dbg !72
}

define internal noundef i64 @"func_A.4test$block_1"(i64** nocapture nofree noundef nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* noundef %cfp) !dbg !22 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !47
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !73
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %pc, align 8, !tbaa !34
  %rubyStr_begin = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 8), align 8, !dbg !74, !invariant.load !14
  %5 = and i64 %rubyStr_begin, 7, !dbg !74
  %6 = icmp ne i64 %5, 0, !dbg !74
  %7 = and i64 %rubyStr_begin, -9, !dbg !74
  %8 = icmp eq i64 %7, 0, !dbg !74
  %9 = or i1 %6, %8, !dbg !74
  br i1 %9, label %sorbet_isa_String.exit, label %10, !dbg !74

10:                                               ; preds = %functionEntryInitializers
  %11 = inttoptr i64 %rubyStr_begin to %struct.RBasic*, !dbg !74
  %12 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %11, i64 0, i32 0, !dbg !74
  %13 = load i64, i64* %12, align 8, !dbg !74, !tbaa !55
  %14 = and i64 %13, 31, !dbg !74
  %15 = icmp eq i64 %14, 5, !dbg !74
  br label %sorbet_isa_String.exit, !dbg !74

sorbet_isa_String.exit:                           ; preds = %functionEntryInitializers, %10
  %16 = phi i1 [ false, %functionEntryInitializers ], [ %15, %10 ], !dbg !74
  tail call void @llvm.assume(i1 noundef %16) #14, !dbg !74
  %17 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !21
  %18 = load i64*, i64** %17, align 8, !dbg !21
  store i64 %4, i64* %18, align 8, !dbg !21, !tbaa !5
  %19 = getelementptr inbounds i64, i64* %18, i64 1, !dbg !21
  store i64 %rubyStr_begin, i64* %19, align 8, !dbg !21, !tbaa !5
  %20 = getelementptr inbounds i64, i64* %19, i64 1, !dbg !21
  store i64* %20, i64** %17, align 8, !dbg !21
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.3, i64 0), !dbg !21
  %21 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 1) #11, !dbg !21
  %22 = and i64 %21, -9, !dbg !21
  %23 = icmp ne i64 %22, 0, !dbg !21
  br i1 %23, label %BB5, label %BB6, !dbg !21

BB5:                                              ; preds = %sorbet_isa_String.exit
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %pc, align 8, !tbaa !34
  %24 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 1) #11, !dbg !25
  %25 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !25
  %26 = load i64*, i64** %25, align 8, !dbg !25
  store i64 %4, i64* %26, align 8, !dbg !25, !tbaa !5
  %27 = getelementptr inbounds i64, i64* %26, i64 1, !dbg !25
  store i64 %24, i64* %27, align 8, !dbg !25, !tbaa !5
  %28 = getelementptr inbounds i64, i64* %27, i64 1, !dbg !25
  store i64* %28, i64** %25, align 8, !dbg !25
  %send27 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.4, i64 0), !dbg !25
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %pc, align 8, !dbg !25, !tbaa !34
  %rubyStr_foo = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 9), align 8, !dbg !75, !invariant.load !14
  %29 = and i64 %rubyStr_foo, 7, !dbg !75
  %30 = icmp ne i64 %29, 0, !dbg !75
  %31 = and i64 %rubyStr_foo, -9, !dbg !75
  %32 = icmp eq i64 %31, 0, !dbg !75
  %33 = or i1 %30, %32, !dbg !75
  br i1 %33, label %sorbet_isa_String.exit30, label %34, !dbg !75

34:                                               ; preds = %BB5
  %35 = inttoptr i64 %rubyStr_foo to %struct.RBasic*, !dbg !75
  %36 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %35, i64 0, i32 0, !dbg !75
  %37 = load i64, i64* %36, align 8, !dbg !75, !tbaa !55
  %38 = and i64 %37, 31, !dbg !75
  %39 = icmp eq i64 %38, 5, !dbg !75
  br label %sorbet_isa_String.exit30, !dbg !75

sorbet_isa_String.exit30:                         ; preds = %BB5, %34
  %40 = phi i1 [ false, %BB5 ], [ %39, %34 ], !dbg !75
  tail call void @llvm.assume(i1 noundef %40), !dbg !75
  %41 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !26
  %42 = load i64*, i64** %41, align 8, !dbg !26
  store i64 %4, i64* %42, align 8, !dbg !26, !tbaa !5
  %43 = getelementptr inbounds i64, i64* %42, i64 1, !dbg !26
  store i64 %rubyStr_foo, i64* %43, align 8, !dbg !26, !tbaa !5
  %44 = getelementptr inbounds i64, i64* %43, i64 1, !dbg !26
  store i64* %44, i64** %41, align 8, !dbg !26
  %send29 = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_raise, i64 0), !dbg !26
  br label %BB7, !dbg !26

BB6:                                              ; preds = %sorbet_isa_String.exit
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %pc, align 8, !tbaa !34
  br label %BB7, !dbg !76

BB7:                                              ; preds = %BB6, %sorbet_isa_String.exit30
  %.sink = phi i64 [ 8, %BB6 ], [ %send29, %sorbet_isa_String.exit30 ]
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 2, i64 noundef %.sink) #11, !dbg !77
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %pc, align 8, !tbaa !34
  ret i64 52
}

define internal noundef i64 @"func_A.4test$block_2"(i64** nocapture nofree readnone %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) !dbg !28 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !47
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !73
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.4test$block_2", align 8
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* noundef %0, %struct.rb_control_frame_struct* noundef %2, %struct.rb_iseq_struct* noundef %stackFrame) #11
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %8, align 8, !tbaa !34
  %9 = load i64, i64* @rb_eStandardError, align 8, !dbg !27
  %10 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 0) #11, !dbg !27
  %11 = load i64, i64* @rb_cModule, align 8, !dbg !27
  %12 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 0) #11, !dbg !27
  %13 = tail call i64 @rb_obj_is_kind_of(i64 %12, i64 %9), !dbg !27
  %14 = icmp eq i64 %13, 20, !dbg !27
  %15 = select i1 %14, i64 20, i64 0, !dbg !27
  %16 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !27, !tbaa !34
  %17 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %16, i64 0, i32 5, !dbg !27
  %18 = load i32, i32* %17, align 8, !dbg !27, !tbaa !78
  %19 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %16, i64 0, i32 6, !dbg !27
  %20 = load i32, i32* %19, align 4, !dbg !27, !tbaa !79
  %21 = xor i32 %20, -1, !dbg !27
  %22 = and i32 %21, %18, !dbg !27
  %23 = icmp eq i32 %22, 0, !dbg !27
  br i1 %23, label %afterSend, label %36, !dbg !27, !prof !80

blockExit:                                        ; preds = %BB11, %BB10
  tail call void @sorbet_popFrame()
  ret i64 52

BB10:                                             ; preds = %afterSend
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %8, align 8, !tbaa !34
  %24 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 0) #11, !dbg !27
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 3, i64 noundef %24) #11, !dbg !27
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 0, i64 noundef 8) #11, !dbg !81
  %25 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 0) #11, !dbg !82
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %8, align 8, !dbg !82, !tbaa !34
  %26 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 3) #11, !dbg !29
  %27 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !29, !tbaa !34
  %28 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %27, i64 0, i32 2, !dbg !29
  %29 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %28, align 8, !dbg !29, !tbaa !47
  %30 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %29, i64 0, i32 1, !dbg !29
  %31 = load i64*, i64** %30, align 8, !dbg !29
  store i64 %4, i64* %31, align 8, !dbg !29, !tbaa !5
  %32 = getelementptr inbounds i64, i64* %31, i64 1, !dbg !29
  store i64 %26, i64* %32, align 8, !dbg !29, !tbaa !5
  %33 = getelementptr inbounds i64, i64* %32, i64 1, !dbg !29
  store i64* %33, i64** %30, align 8, !dbg !29
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.5, i64 0), !dbg !29
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 2, i64 noundef %send) #11, !dbg !29
  br label %blockExit, !dbg !29

BB11:                                             ; preds = %afterSend
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %8, align 8, !tbaa !34
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 4, i64 noundef 20) #11, !dbg !83
  br label %blockExit, !dbg !83

afterSend:                                        ; preds = %36, %functionEntryInitializers
  %34 = and i64 %15, -9, !dbg !27
  %35 = icmp ne i64 %34, 0, !dbg !27
  br i1 %35, label %BB10, label %BB11, !dbg !27

36:                                               ; preds = %functionEntryInitializers
  %37 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %16, i64 0, i32 8, !dbg !27
  %38 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %37, align 8, !dbg !27, !tbaa !84
  %39 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %38, i32 noundef 0) #11, !dbg !27
  br label %afterSend, !dbg !27
}

define internal noundef i64 @"func_A.4test$block_3"(i64** nocapture nofree readnone %pc, i64 %localsOffset, %struct.rb_control_frame_struct* nocapture nofree readnone %cfp) !dbg !33 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !47
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !73
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_A.4test$block_3", align 8
  tail call void @sorbet_setExceptionStackFrame(%struct.rb_execution_context_struct* noundef %0, %struct.rb_control_frame_struct* noundef %2, %struct.rb_iseq_struct* noundef %stackFrame) #11
  %5 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %6 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %5, i64 0, i32 2
  %7 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %6, align 8, !tbaa !47
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %7, i64 0, i32 0
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %8, align 8, !tbaa !34
  %9 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 0) #11, !dbg !85
  tail call void @llvm.experimental.noalias.scope.decl(metadata !86), !dbg !85
  %10 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !85, !tbaa !34
  %11 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %10, i64 0, i32 5, !dbg !85
  %12 = load i32, i32* %11, align 8, !dbg !85, !tbaa !78
  %13 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %10, i64 0, i32 6, !dbg !85
  %14 = load i32, i32* %13, align 4, !dbg !85, !tbaa !79
  %15 = xor i32 %14, -1, !dbg !85
  %16 = and i32 %15, %12, !dbg !85
  %17 = icmp eq i32 %16, 0, !dbg !85
  br i1 %17, label %sorbet_afterIntrinsic.exit, label %18, !dbg !85, !prof !80

18:                                               ; preds = %functionEntryInitializers
  %19 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %10, i64 0, i32 8, !dbg !85
  %20 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %19, align 8, !dbg !85, !tbaa !84
  %21 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %20, i32 noundef 0) #11, !dbg !85
  br label %sorbet_afterIntrinsic.exit, !dbg !85

sorbet_afterIntrinsic.exit:                       ; preds = %functionEntryInitializers, %18
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 3, i64 noundef %9) #11, !dbg !85
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 18), i64** %8, align 8, !dbg !85, !tbaa !34
  %rubyStr_ensure = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 11), align 8, !dbg !89, !invariant.load !14
  %22 = and i64 %rubyStr_ensure, 7, !dbg !89
  %23 = icmp ne i64 %22, 0, !dbg !89
  %24 = and i64 %rubyStr_ensure, -9, !dbg !89
  %25 = icmp eq i64 %24, 0, !dbg !89
  %26 = or i1 %23, %25, !dbg !89
  br i1 %26, label %sorbet_isa_String.exit, label %27, !dbg !89

27:                                               ; preds = %sorbet_afterIntrinsic.exit
  %28 = inttoptr i64 %rubyStr_ensure to %struct.RBasic*, !dbg !89
  %29 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %28, i64 0, i32 0, !dbg !89
  %30 = load i64, i64* %29, align 8, !dbg !89, !tbaa !55
  %31 = and i64 %30, 31, !dbg !89
  %32 = icmp eq i64 %31, 5, !dbg !89
  br label %sorbet_isa_String.exit, !dbg !89

sorbet_isa_String.exit:                           ; preds = %sorbet_afterIntrinsic.exit, %27
  %33 = phi i1 [ false, %sorbet_afterIntrinsic.exit ], [ %32, %27 ], !dbg !89
  tail call void @llvm.assume(i1 noundef %33), !dbg !89
  %34 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !32, !tbaa !34
  %35 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %34, i64 0, i32 2, !dbg !32
  %36 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %35, align 8, !dbg !32, !tbaa !47
  %37 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %36, i64 0, i32 1, !dbg !32
  %38 = load i64*, i64** %37, align 8, !dbg !32
  store i64 %4, i64* %38, align 8, !dbg !32, !tbaa !5
  %39 = getelementptr inbounds i64, i64* %38, i64 1, !dbg !32
  store i64 %rubyStr_ensure, i64* %39, align 8, !dbg !32, !tbaa !5
  %40 = getelementptr inbounds i64, i64* %39, i64 1, !dbg !32
  store i64* %40, i64** %37, align 8, !dbg !32
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.7, i64 0), !dbg !32
  %41 = tail call i64 @rb_ary_entry(i64 noundef %localsOffset, i64 noundef 4) #11, !dbg !32
  %42 = and i64 %41, -9, !dbg !32
  %43 = icmp ne i64 %42, 0, !dbg !32
  %44 = xor i1 %43, true, !dbg !32
  tail call void @llvm.assume(i1 noundef %44), !dbg !32
  tail call void @sorbet_popFrame()
  ret i64 52
}

define internal noundef i64 @"func_A.4test$block_4"(i64** nocapture nofree noundef nonnull writeonly align 8 dereferenceable(8) %pc, i64 %localsOffset, %struct.rb_control_frame_struct* noundef %cfp) !dbg !31 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !34
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !47
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 3
  %4 = load i64, i64* %3, align 8, !tbaa !73
  store i64* getelementptr inbounds ([28 x i64], [28 x i64]* @iseqEncodedArray, i64 0, i64 16), i64** %pc, align 8, !tbaa !34
  %rubyStr_else = load i64, i64* getelementptr inbounds ([12 x i64], [12 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 10), align 8, !dbg !90, !invariant.load !14
  %5 = and i64 %rubyStr_else, 7, !dbg !90
  %6 = icmp ne i64 %5, 0, !dbg !90
  %7 = and i64 %rubyStr_else, -9, !dbg !90
  %8 = icmp eq i64 %7, 0, !dbg !90
  %9 = or i1 %6, %8, !dbg !90
  br i1 %9, label %sorbet_isa_String.exit, label %10, !dbg !90

10:                                               ; preds = %functionEntryInitializers
  %11 = inttoptr i64 %rubyStr_else to %struct.RBasic*, !dbg !90
  %12 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %11, i64 0, i32 0, !dbg !90
  %13 = load i64, i64* %12, align 8, !dbg !90, !tbaa !55
  %14 = and i64 %13, 31, !dbg !90
  %15 = icmp eq i64 %14, 5, !dbg !90
  br label %sorbet_isa_String.exit, !dbg !90

sorbet_isa_String.exit:                           ; preds = %functionEntryInitializers, %10
  %16 = phi i1 [ false, %functionEntryInitializers ], [ %15, %10 ], !dbg !90
  tail call void @llvm.assume(i1 noundef %16) #14, !dbg !90
  %17 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !30
  %18 = load i64*, i64** %17, align 8, !dbg !30
  store i64 %4, i64* %18, align 8, !dbg !30, !tbaa !5
  %19 = getelementptr inbounds i64, i64* %18, i64 1, !dbg !30
  store i64 %rubyStr_else, i64* %19, align 8, !dbg !30, !tbaa !5
  %20 = getelementptr inbounds i64, i64* %19, i64 1, !dbg !30
  store i64* %20, i64** %17, align 8, !dbg !30
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.6, i64 0), !dbg !30
  tail call void @rb_ary_store(i64 noundef %localsOffset, i64 noundef 2, i64 noundef %send) #11, !dbg !30
  ret i64 52
}

; Function Attrs: argmemonly nocallback nofree nounwind willreturn writeonly
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #9

define linkonce void @const_recompute_A() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([281 x i8], [281 x i8]* @sorbet_moduleStringTable, i64 0, i64 60), i64 1)
  store i64 %1, i64* @guarded_const_A, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !57
  store i64 %2, i64* @guard_epoch_A, align 8
  ret void
}

attributes #0 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #1 = { mustprogress nofree nosync nounwind readnone willreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #2 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #3 = { argmemonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #4 = { inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #5 = { allocsize(0,1) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #6 = { argmemonly mustprogress nocallback nofree nounwind willreturn }
attributes #7 = { nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #8 = { nounwind sspreq uwtable }
attributes #9 = { argmemonly nocallback nofree nounwind willreturn writeonly }
attributes #10 = { noreturn nounwind }
attributes #11 = { nounwind }
attributes #12 = { nounwind allocsize(0,1) }
attributes #13 = { noreturn }
attributes #14 = { willreturn }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!4 = !DIFile(filename: "test/testdata/compiler/exceptions/basic.rb", directory: ".")
!5 = !{!6, !6, i64 0}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !DILocation(line: 6, column: 3, scope: !10, inlinedAt: !15)
!10 = distinct !DISubprogram(name: "A.<static-init>", linkageName: "func_A.13<static-init>L62", scope: null, file: !4, line: 5, type: !11, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!11 = !DISubroutineType(cc: DW_CC_nocall, types: !12)
!12 = !{!13}
!13 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!14 = !{}
!15 = distinct !DILocation(line: 5, column: 1, scope: !16)
!16 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>", scope: null, file: !4, line: 5, type: !11, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!17 = !DILocation(line: 23, column: 1, scope: !16)
!18 = !DILocation(line: 24, column: 1, scope: !16)
!19 = !DILocation(line: 26, column: 1, scope: !16)
!20 = !DILocation(line: 27, column: 1, scope: !16)
!21 = !DILocation(line: 8, column: 7, scope: !22)
!22 = distinct !DISubprogram(name: "A.test", linkageName: "func_A.4test$block_1", scope: !23, file: !4, line: 6, type: !24, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!23 = distinct !DISubprogram(name: "A.test", linkageName: "func_A.4test", scope: null, file: !4, line: 6, type: !24, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!24 = !DISubroutineType(types: !12)
!25 = !DILocation(line: 10, column: 9, scope: !22)
!26 = !DILocation(line: 11, column: 9, scope: !22)
!27 = !DILocation(line: 13, column: 15, scope: !28)
!28 = distinct !DISubprogram(name: "A.test", linkageName: "func_A.4test$block_2", scope: !23, file: !4, line: 6, type: !24, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!29 = !DILocation(line: 14, column: 7, scope: !28)
!30 = !DILocation(line: 16, column: 7, scope: !31)
!31 = distinct !DISubprogram(name: "A.test", linkageName: "func_A.4test$block_4", scope: !23, file: !4, line: 6, type: !24, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!32 = !DILocation(line: 18, column: 7, scope: !33)
!33 = distinct !DISubprogram(name: "A.test", linkageName: "func_A.4test$block_3", scope: !23, file: !4, line: 6, type: !24, scopeLine: 6, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!34 = !{!35, !35, i64 0}
!35 = !{!"any pointer", !7, i64 0}
!36 = !{!37, !6, i64 376}
!37 = !{!"rb_vm_struct", !6, i64 0, !38, i64 8, !35, i64 216, !44, i64 224, !7, i64 232, !39, i64 272, !39, i64 288, !39, i64 304, !41, i64 320, !41, i64 324, !41, i64 324, !41, i64 324, !41, i64 324, !6, i64 328, !7, i64 336, !6, i64 376, !6, i64 384, !6, i64 392, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !35, i64 432, !35, i64 440, !45, i64 448, !35, i64 968, !35, i64 976, !41, i64 984, !41, i64 988, !39, i64 992, !7, i64 1008, !6, i64 1048, !6, i64 1056, !6, i64 1064, !41, i64 1072, !35, i64 1080, !35, i64 1088, !35, i64 1096, !35, i64 1104, !35, i64 1112, !35, i64 1120, !41, i64 1128, !35, i64 1136, !7, i64 1144, !46, i64 9328, !7, i64 9360}
!38 = !{!"", !39, i64 0, !41, i64 16, !41, i64 20, !35, i64 24, !35, i64 32, !42, i64 40}
!39 = !{!"list_head", !40, i64 0}
!40 = !{!"list_node", !35, i64 0, !35, i64 8}
!41 = !{!"int", !7, i64 0}
!42 = !{!"", !7, i64 0, !35, i64 40, !41, i64 48, !43, i64 52, !41, i64 56, !7, i64 64, !7, i64 112, !43, i64 160}
!43 = !{!"_Bool", !7, i64 0}
!44 = !{!"long long", !7, i64 0}
!45 = !{!"", !7, i64 0}
!46 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!47 = !{!48, !35, i64 16}
!48 = !{!"rb_execution_context_struct", !35, i64 0, !6, i64 8, !35, i64 16, !35, i64 24, !35, i64 32, !41, i64 40, !41, i64 44, !35, i64 48, !35, i64 56, !35, i64 64, !6, i64 72, !6, i64 80, !35, i64 88, !6, i64 96, !35, i64 104, !35, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !49, i64 152}
!49 = !{!"", !35, i64 0, !35, i64 8, !6, i64 16, !7, i64 24}
!50 = !{!51, !35, i64 16}
!51 = !{!"rb_control_frame_struct", !35, i64 0, !35, i64 8, !35, i64 16, !6, i64 24, !35, i64 32, !35, i64 40, !35, i64 48}
!52 = !{!51, !35, i64 32}
!53 = !DILocation(line: 5, column: 1, scope: !16)
!54 = !DILocation(line: 5, column: 1, scope: !10, inlinedAt: !15)
!55 = !{!56, !6, i64 0}
!56 = !{!"RBasic", !6, i64 0, !6, i64 8}
!57 = !{!44, !44, i64 0}
!58 = !{!"branch_weights", i32 1, i32 10000}
!59 = !{!41, !41, i64 0}
!60 = !{!61, !35, i64 32}
!61 = !{!"rb_sorbet_param_struct", !62, i64 0, !41, i64 4, !41, i64 8, !41, i64 12, !41, i64 16, !41, i64 20, !41, i64 24, !41, i64 28, !35, i64 32, !41, i64 40, !41, i64 44, !41, i64 48, !41, i64 52, !35, i64 56}
!62 = !{!"", !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 0, !41, i64 1, !41, i64 1}
!63 = !DILocation(line: 23, column: 6, scope: !16)
!64 = !DILocation(line: 26, column: 6, scope: !16)
!65 = distinct !{!65, !66}
!66 = !{!"llvm.loop.unroll.disable"}
!67 = !DILocation(line: 6, column: 3, scope: !23)
!68 = !{!"branch_weights", i32 4001, i32 4000000}
!69 = !DILocation(line: 0, scope: !23)
!70 = !DILocation(line: 6, column: 17, scope: !23)
!71 = !DILocation(line: 13, column: 5, scope: !23)
!72 = !DILocation(line: 20, column: 3, scope: !23)
!73 = !{!51, !6, i64 24}
!74 = !DILocation(line: 8, column: 12, scope: !22)
!75 = !DILocation(line: 11, column: 15, scope: !22)
!76 = !DILocation(line: 9, column: 7, scope: !22)
!77 = !DILocation(line: 0, scope: !22)
!78 = !{!48, !41, i64 40}
!79 = !{!48, !41, i64 44}
!80 = !{!"branch_weights", i32 2000, i32 1}
!81 = !DILocation(line: 0, scope: !28)
!82 = !DILocation(line: 13, column: 5, scope: !28)
!83 = !DILocation(line: 8, column: 7, scope: !28)
!84 = !{!48, !35, i64 56}
!85 = !DILocation(line: 13, column: 15, scope: !33)
!86 = !{!87}
!87 = distinct !{!87, !88, !"sorbet_T_unsafe: argument 0"}
!88 = distinct !{!88, !"sorbet_T_unsafe"}
!89 = !DILocation(line: 18, column: 12, scope: !33)
!90 = !DILocation(line: 16, column: 12, scope: !31)
