; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.anon.2, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, i32, i8, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.rb_id_table*, [1023 x %struct.rb_callcache*], %struct.anon.9, [29 x i16] }
%struct.anon.2 = type { %struct.list_head, i32, i32, %struct.rb_ractor_struct*, %struct.rb_thread_struct*, %struct.anon.3 }
%struct.rb_ractor_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_ractor_struct*, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_waiting_list*, %union.anon.12, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64, i32, i64, %struct.rb_ext_config, i8* }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.rb_id_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.16 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.15, i32, i32, i32, i32, i8, i8, %struct.rb_id_table* }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.anon.1 }
%struct.anon.1 = type { %struct.rb_thread_struct*, i64 }
%struct.rb_call_data = type { %struct.rb_callinfo*, %struct.rb_callcache* }
%struct.rb_callinfo = type { i64, %struct.rb_callinfo_kwarg*, i64, i64, i64 }
%struct.rb_callinfo_kwarg = type { i32, [0 x i64] }
%struct.rb_callcache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*)*, %union.__atomic_wide_counter }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.__atomic_wide_counter = type { i64 }
%struct.anon.15 = type { i64, i64, i64, i64* }
%union.anon.16 = type { %struct.anon.17 }
%struct.anon.17 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { %struct.rb_callinfo*, %struct.rb_callcache*, i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.11 }
%union.anon.11 = type { %union.pthread_cond_t }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.__atomic_wide_counter, %union.__atomic_wide_counter, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_waiting_list = type { %struct.rb_waiting_list*, %struct.rb_thread_struct*, %struct.rb_fiber_struct* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.rb_ext_config = type { i8 }
%struct.anon.3 = type { %union.pthread_mutex_t, %struct.rb_ractor_struct*, i32, i8, i32, %union.pthread_cond_t, %union.pthread_cond_t, i8 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.rb_id_table = type opaque
%struct.anon.9 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_call_data }
%struct.rb_captured_block = type { i64, i64*, %union.anon.19 }
%union.anon.19 = type { %struct.rb_iseq_struct* }
%struct.vm_ifunc = type { i64, i64, i64 (i64, i64, i32, i64*, i64)*, i8*, %struct.rb_code_position_struct }
%struct.RBasic = type { i64, i64 }
%struct.RArray = type { %struct.RBasic, %union.anon.22 }
%union.anon.22 = type { %struct.anon.23 }
%struct.anon.23 = type { i64, %union.__atomic_wide_counter, i64* }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_ec = external thread_local local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@"stackFramePrecomputed_func_<root>.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@iseqEncodedArray = internal global [5 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@"stackFramePrecomputed_func_<root>.13<static-init>$block_1" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"func_<root>.13<static-init>$block_1_ifunc" = internal unnamed_addr global i64 0
@"ic_+" = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@sorbet_moduleStringTable = internal unnamed_addr constant [112 x i8] c"<top (required)>\00test/testdata/compiler/block_args.rb\00block in <top (required)>\00<build-array>\00map\00+\00puts\00master\00", align 1
@sorbet_moduleIDTable = internal unnamed_addr global [6 x i64] zeroinitializer, align 8
@sorbet_moduleIDDescriptors = internal unnamed_addr constant [6 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 54, i32 25 }, %struct.rb_code_position_struct { i32 80, i32 13 }, %struct.rb_code_position_struct { i32 94, i32 3 }, %struct.rb_code_position_struct { i32 98, i32 1 }, %struct.rb_code_position_struct { i32 100, i32 4 }], align 8
@sorbet_moduleRubyStringTable = internal unnamed_addr global [3 x i64] zeroinitializer, align 8
@sorbet_moduleRubyStringDescriptors = internal unnamed_addr constant [3 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 17, i32 36 }, %struct.rb_code_position_struct { i32 54, i32 25 }], align 8

declare i64 @rb_ary_push(i64 noundef, i64 noundef) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef, i64 noundef, i64 noundef, i64 noundef, %struct.rb_iseq_struct* noundef, i32 noundef, i32 noundef, %struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_pushBlockFrame(%struct.rb_captured_block* noundef) local_unnamed_addr #0

declare void @sorbet_popFrame() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef, i64 noundef, i32 noundef, i32 noundef, i32 noundef, ...) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef, i64 noundef) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #0

declare i64 @sorbet_rb_int_plus_slowpath(i64 noundef, i64 noundef) local_unnamed_addr #0

declare i64 @sorbet_globalConstRegister(i64 noundef) local_unnamed_addr #0

declare %struct.vm_ifunc* @sorbet_globalConstFetchIfunc(i64 noundef) local_unnamed_addr #0

declare void @sorbet_vm_intern_ids(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

declare void @sorbet_vm_init_string_table(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

; Function Attrs: argmemonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1

; Function Attrs: argmemonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #1

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #2

declare i64 @rb_ary_new_capa(i64 noundef) local_unnamed_addr #0

declare i64 @rb_ary_new_from_values(i64 noundef, i64* noundef) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64 noundef, i8* noundef, ...) local_unnamed_addr #3

declare i64 @rb_int2big(i64 noundef) local_unnamed_addr #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind readnone speculatable willreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64) #4

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #2

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef, i32 noundef) local_unnamed_addr #0

declare %struct.vm_ifunc* @rb_vm_ifunc_new(i64 (i64, i64, i32, i64*, i64)* noundef, i8* noundef, i32 noundef, i32 noundef) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #5 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i32 0, i32 0)) #6
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #5 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i32 0, i32 0)) #6
  unreachable
}

define internal i64 @"func_<root>.13<static-init>$block_1"(i64 %firstYieldArgRaw, i64 %localsOffset, i32 %argc, i64* nocapture nofree readonly %argArray, i64 %blockArg) !dbg !9 {
functionEntryInitializers:
  %0 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !16
  %1 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %0, i64 0, i32 2
  %2 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %1, align 8, !tbaa !18
  %stackFrame = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>$block_1", align 8
  %3 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame, %struct.rb_iseq_struct** %3, align 8, !tbaa !22
  %4 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 4
  %5 = load i64*, i64** %4, align 8, !tbaa !24
  %6 = load i64, i64* %5, align 8, !tbaa !5
  %7 = and i64 %6, -129
  store i64 %7, i64* %5, align 8, !tbaa !5
  %8 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 0
  store i64* getelementptr inbounds ([5 x i64], [5 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %8, align 8, !tbaa !16
  %default0 = icmp eq i32 %argc, 0, !dbg !25
  br i1 %default0, label %fillFromDefaultBlockDone1.thread, label %fillFromDefaultBlockDone1, !dbg !25, !prof !26

fillFromDefaultBlockDone1:                        ; preds = %functionEntryInitializers
  %rawArg_x = load i64, i64* %argArray, align 8, !dbg !25
  tail call void @llvm.assume(i1 noundef true) #7, !dbg !27
  %9 = and i64 %rawArg_x, 1, !dbg !28
  %10 = icmp eq i64 %9, 0, !dbg !28
  br i1 %10, label %fillFromDefaultBlockDone1.thread, label %"fastSymCallIntrinsic_Integer_+", !dbg !28, !prof !26

fillFromDefaultBlockDone1.thread:                 ; preds = %functionEntryInitializers, %fillFromDefaultBlockDone1
  %x.sroa.0.017 = phi i64 [ %rawArg_x, %fillFromDefaultBlockDone1 ], [ 8, %functionEntryInitializers ]
  %11 = and i64 %x.sroa.0.017, 7, !dbg !28
  %12 = icmp ne i64 %11, 0, !dbg !28
  %13 = and i64 %x.sroa.0.017, -9, !dbg !28
  %14 = icmp eq i64 %13, 0, !dbg !28
  %15 = or i1 %12, %14, !dbg !28
  br i1 %15, label %"alternativeCallIntrinsic_Integer_+", label %sorbet_isa_Integer.exit, !dbg !28

sorbet_isa_Integer.exit:                          ; preds = %fillFromDefaultBlockDone1.thread
  %16 = inttoptr i64 %x.sroa.0.017 to %struct.RBasic*, !dbg !28
  %17 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %16, i64 0, i32 0, !dbg !28
  %18 = load i64, i64* %17, align 8, !dbg !28, !tbaa !29
  %19 = and i64 %18, 31, !dbg !28
  %20 = icmp eq i64 %19, 10, !dbg !28
  br i1 %20, label %"fastSymCallIntrinsic_Integer_+", label %"alternativeCallIntrinsic_Integer_+", !dbg !28, !prof !31

afterSend:                                        ; preds = %46, %sorbet_rb_int_plus.exit, %"alternativeCallIntrinsic_Integer_+"
  %"symIntrinsicRawPhi_+" = phi i64 [ %send, %"alternativeCallIntrinsic_Integer_+" ], [ %37, %sorbet_rb_int_plus.exit ], [ %37, %46 ], !dbg !28
  ret i64 %"symIntrinsicRawPhi_+", !dbg !28

"alternativeCallIntrinsic_Integer_+":             ; preds = %fillFromDefaultBlockDone1.thread, %sorbet_isa_Integer.exit
  %21 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %2, i64 0, i32 1, !dbg !28
  %22 = load i64*, i64** %21, align 8, !dbg !28
  store i64 %x.sroa.0.017, i64* %22, align 8, !dbg !28, !tbaa !5
  %23 = getelementptr inbounds i64, i64* %22, i64 1, !dbg !28
  store i64 3, i64* %23, align 8, !dbg !28, !tbaa !5
  %24 = getelementptr inbounds i64, i64* %23, i64 1, !dbg !28
  store i64* %24, i64** %21, align 8, !dbg !28
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @"ic_+", i64 0), !dbg !28
  br label %afterSend, !dbg !28

"fastSymCallIntrinsic_Integer_+":                 ; preds = %fillFromDefaultBlockDone1, %sorbet_isa_Integer.exit
  %x.sroa.0.016 = phi i64 [ %rawArg_x, %fillFromDefaultBlockDone1 ], [ %x.sroa.0.017, %sorbet_isa_Integer.exit ]
  tail call void @llvm.experimental.noalias.scope.decl(metadata !32), !dbg !28
  %25 = and i64 %x.sroa.0.016, 1, !dbg !28
  %26 = icmp ne i64 %25, 0, !dbg !28
  br i1 %26, label %27, label %35, !dbg !28, !prof !35

27:                                               ; preds = %"fastSymCallIntrinsic_Integer_+"
  %28 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 noundef %x.sroa.0.016, i64 noundef 2), !dbg !28
  %29 = extractvalue { i64, i1 } %28, 1, !dbg !28
  %30 = extractvalue { i64, i1 } %28, 0, !dbg !28
  br i1 %29, label %31, label %sorbet_rb_int_plus.exit, !dbg !28

31:                                               ; preds = %27
  %32 = ashr i64 %30, 1, !dbg !28
  %33 = xor i64 %32, -9223372036854775808, !dbg !28
  %34 = tail call i64 @rb_int2big(i64 noundef %33) #8, !dbg !28, !noalias !32
  br label %sorbet_rb_int_plus.exit, !dbg !28

35:                                               ; preds = %"fastSymCallIntrinsic_Integer_+"
  %36 = tail call i64 @sorbet_rb_int_plus_slowpath(i64 noundef %x.sroa.0.016, i64 noundef 3) #8, !dbg !28, !noalias !32
  br label %sorbet_rb_int_plus.exit, !dbg !28

sorbet_rb_int_plus.exit:                          ; preds = %27, %31, %35
  %37 = phi i64 [ %36, %35 ], [ %34, %31 ], [ %30, %27 ], !dbg !28
  %38 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !28, !tbaa !16
  %39 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %38, i64 0, i32 5, !dbg !28
  %40 = load i32, i32* %39, align 8, !dbg !28, !tbaa !36
  %41 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %38, i64 0, i32 6, !dbg !28
  %42 = load i32, i32* %41, align 4, !dbg !28, !tbaa !37
  %43 = xor i32 %42, -1, !dbg !28
  %44 = and i32 %43, %40, !dbg !28
  %45 = icmp eq i32 %44, 0, !dbg !28
  br i1 %45, label %afterSend, label %46, !dbg !28, !prof !31

46:                                               ; preds = %sorbet_rb_int_plus.exit
  %47 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %38, i64 0, i32 8, !dbg !28
  %48 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %47, align 8, !dbg !28, !tbaa !38
  %49 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %48, i32 noundef 0) #8, !dbg !28
  br label %afterSend, !dbg !28
}

define void @Init_block_args() local_unnamed_addr {
entry:
  %0 = alloca i64, align 8
  %callArgs.i = alloca [3 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  tail call void @sorbet_vm_intern_ids(i64* noundef getelementptr inbounds ([6 x i64], [6 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([6 x %struct.rb_code_position_struct], [6 x %struct.rb_code_position_struct]* @sorbet_moduleIDDescriptors, i32 0, i32 0), i32 noundef 6, i8* noundef getelementptr inbounds ([112 x i8], [112 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_vm_init_string_table(i64* noundef getelementptr inbounds ([3 x i64], [3 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([3 x %struct.rb_code_position_struct], [3 x %struct.rb_code_position_struct]* @sorbet_moduleRubyStringDescriptors, i32 0, i32 0), i32 noundef 3, i8* noundef getelementptr inbounds ([112 x i8], [112 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([5 x i64], [5 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 5)
  %"rubyId_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([6 x i64], [6 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), align 8, !invariant.load !14
  %"rubyStr_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([3 x i64], [3 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), align 8, !invariant.load !14
  %"rubyStr_test/testdata/compiler/block_args.rb.i.i" = load i64, i64* getelementptr inbounds ([3 x i64], [3 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 1), align 8, !invariant.load !14
  %1 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<top (required)>.i.i", i64 noundef %"rubyId_<top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/block_args.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %1, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %"rubyId_block in <top (required)>.i.i" = load i64, i64* getelementptr inbounds ([6 x i64], [6 x i64]* @sorbet_moduleIDTable, i64 0, i64 1), align 8, !invariant.load !14
  %"rubyStr_block in <top (required)>.i.i" = load i64, i64* getelementptr inbounds ([3 x i64], [3 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 2), align 8, !invariant.load !14
  %2 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_block in <top (required)>.i.i", i64 noundef %"rubyId_block in <top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/block_args.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef %1, i32 noundef 2, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef null, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %2, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>$block_1", align 8
  %3 = call %struct.vm_ifunc* @rb_vm_ifunc_new(i64 (i64, i64, i32, i64*, i64)* noundef @"func_<root>.13<static-init>$block_1", i8* noundef null, i32 noundef 1, i32 noundef 1) #8
  %4 = ptrtoint %struct.vm_ifunc* %3 to i64
  %5 = call i64 @sorbet_globalConstRegister(i64 noundef %4)
  store i64 %5, i64* @"func_<root>.13<static-init>$block_1_ifunc", align 8
  %"rubyId_+.i" = load i64, i64* getelementptr inbounds ([6 x i64], [6 x i64]* @sorbet_moduleIDTable, i64 0, i64 4), align 8, !dbg !28, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_+", i64 noundef %"rubyId_+.i", i32 noundef 16, i32 noundef 1, i32 noundef 0), !dbg !28
  %rubyId_puts.i = load i64, i64* getelementptr inbounds ([6 x i64], [6 x i64]* @sorbet_moduleIDTable, i64 0, i64 5), align 8, !dbg !39, !invariant.load !14
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !39
  %6 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !16
  %7 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %6, i64 0, i32 12
  %8 = load i64, i64* %7, align 8, !tbaa !40
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !16
  %10 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 2
  %11 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !tbaa !18
  %12 = bitcast [3 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 24, i8* nonnull %12)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %13 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !tbaa !18
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %14, align 8, !tbaa !22
  %15 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %13, i64 0, i32 4
  %16 = load i64*, i64** %15, align 8, !tbaa !24
  %17 = load i64, i64* %16, align 8, !tbaa !5
  %18 = and i64 %17, -33
  store i64 %18, i64* %16, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %9, %struct.rb_control_frame_struct* noundef %13, %struct.rb_iseq_struct* noundef %stackFrame.i) #8
  %19 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 0
  store i64* getelementptr inbounds ([5 x i64], [5 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %19, align 8, !tbaa !16
  call void @llvm.assume(i1 noundef true), !dbg !50
  call void @llvm.assume(i1 noundef true), !dbg !51
  %callArgs0Addr.i = getelementptr [3 x i64], [3 x i64]* %callArgs.i, i64 0, i64 0, !dbg !52
  %20 = bitcast i64* %callArgs0Addr.i to <2 x i64>*, !dbg !52
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %20, align 8, !dbg !52
  call void @llvm.experimental.noalias.scope.decl(metadata !53), !dbg !52
  %21 = call i64 @rb_ary_new_from_values(i64 noundef 2, i64* noundef nonnull align 8 %callArgs0Addr.i) #8, !dbg !52
  %22 = and i64 %21, 7, !dbg !52
  %23 = icmp ne i64 %22, 0, !dbg !52
  %24 = and i64 %21, -9, !dbg !52
  %25 = icmp eq i64 %24, 0, !dbg !52
  %26 = or i1 %23, %25, !dbg !52
  br i1 %26, label %sorbet_isa_Array.exit1, label %27, !dbg !52

27:                                               ; preds = %entry
  %28 = inttoptr i64 %21 to %struct.RBasic*, !dbg !52
  %29 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %28, i64 0, i32 0, !dbg !52
  %30 = load i64, i64* %29, align 8, !dbg !52, !tbaa !29
  %31 = and i64 %30, 31, !dbg !52
  %32 = icmp eq i64 %31, 7, !dbg !52
  br label %sorbet_isa_Array.exit1, !dbg !52

sorbet_isa_Array.exit1:                           ; preds = %entry, %27
  %33 = phi i1 [ false, %entry ], [ %32, %27 ], !dbg !52
  call void @llvm.assume(i1 noundef %33), !dbg !52
  %34 = load i64, i64* @"func_<root>.13<static-init>$block_1_ifunc", align 8, !dbg !52
  %35 = call %struct.vm_ifunc* @sorbet_globalConstFetchIfunc(i64 noundef %34) #8, !dbg !52
  %36 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !52, !tbaa !16
  %37 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %36, i64 0, i32 2, !dbg !52
  %38 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %37, align 8, !dbg !52, !tbaa !18
  %39 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %38, i64 0, i32 3, !dbg !52
  %40 = getelementptr inbounds i64, i64* %39, i64 2, !dbg !52
  %41 = bitcast i64* %40 to %struct.vm_ifunc**, !dbg !52
  store %struct.vm_ifunc* %35, %struct.vm_ifunc** %41, align 8, !dbg !52, !tbaa !56
  %42 = ptrtoint i64* %39 to i64, !dbg !52
  %43 = or i64 %42, 3, !dbg !52
  %44 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %36, i64 0, i32 17, !dbg !52
  %45 = and i64 %43, -4, !dbg !57
  %46 = inttoptr i64 %45 to %struct.rb_captured_block*, !dbg !57
  store i64 0, i64* %44, align 8, !dbg !57, !tbaa !59
  call void @sorbet_pushBlockFrame(%struct.rb_captured_block* noundef %46) #8, !dbg !57
  %47 = inttoptr i64 %21 to %struct.RBasic*, !dbg !57
  %48 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %47, i64 0, i32 0, !dbg !57
  %49 = load i64, i64* %48, align 8, !dbg !57, !tbaa !29
  %50 = and i64 %49, 8192, !dbg !57
  %51 = icmp eq i64 %50, 0, !dbg !57
  br i1 %51, label %55, label %52, !dbg !57

52:                                               ; preds = %sorbet_isa_Array.exit1
  %53 = lshr i64 %49, 15, !dbg !57
  %54 = and i64 %53, 3, !dbg !57
  br label %59, !dbg !57

55:                                               ; preds = %sorbet_isa_Array.exit1
  %56 = inttoptr i64 %21 to %struct.RArray*, !dbg !57
  %57 = getelementptr inbounds %struct.RArray, %struct.RArray* %56, i64 0, i32 1, i32 0, i32 0, !dbg !57
  %58 = load i64, i64* %57, align 8, !dbg !57, !tbaa !56
  br label %59, !dbg !57

59:                                               ; preds = %55, %52
  %60 = phi i64 [ %54, %52 ], [ %58, %55 ], !dbg !57
  %61 = call i64 @rb_ary_new_capa(i64 noundef %60) #8, !dbg !57
  %62 = inttoptr i64 %21 to %struct.RArray*, !dbg !57
  %63 = getelementptr inbounds %struct.RArray, %struct.RArray* %62, i64 0, i32 1, i32 0, i32 0, !dbg !57
  %64 = bitcast i64* %0 to i8*, !dbg !57
  %65 = getelementptr inbounds %struct.RArray, %struct.RArray* %62, i64 0, i32 1, i32 0, i32 2, !dbg !57
  br label %66, !dbg !57

66:                                               ; preds = %79, %59
  %67 = phi i64 [ 0, %59 ], [ %85, %79 ], !dbg !57
  %68 = load i64, i64* %48, align 8, !dbg !57, !tbaa !29
  %69 = and i64 %68, 8192, !dbg !57
  %70 = icmp eq i64 %69, 0, !dbg !57
  br i1 %70, label %71, label %.thread.i.i, !dbg !57

71:                                               ; preds = %66
  %72 = load i64, i64* %63, align 8, !dbg !57, !tbaa !56
  %73 = icmp slt i64 %67, %72, !dbg !57
  br i1 %73, label %77, label %forward_sorbet_rb_array_collect_withBlock.exit.i, !dbg !57

.thread.i.i:                                      ; preds = %66
  %74 = lshr i64 %68, 15, !dbg !57
  %75 = and i64 %74, 3, !dbg !57
  %76 = icmp ult i64 %67, %75, !dbg !57
  br i1 %76, label %.thread2.i.i, label %forward_sorbet_rb_array_collect_withBlock.exit.i, !dbg !57

.thread2.i.i:                                     ; preds = %.thread.i.i
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull %64) #8, !dbg !57
  br label %79, !dbg !57

77:                                               ; preds = %71
  call void @llvm.lifetime.start.p0i8(i64 noundef 8, i8* noundef nonnull %64) #8, !dbg !57
  %78 = load i64*, i64** %65, align 8, !dbg !57, !tbaa !56
  br label %79, !dbg !57

79:                                               ; preds = %77, %.thread2.i.i
  %80 = phi i64* [ %78, %77 ], [ %63, %.thread2.i.i ], !dbg !57
  %81 = getelementptr inbounds i64, i64* %80, i64 %67, !dbg !57
  %82 = load i64, i64* %81, align 8, !dbg !57, !tbaa !5
  store i64 %82, i64* %0, align 8, !dbg !57, !tbaa !5
  %83 = call i64 @"func_<root>.13<static-init>$block_1"(i64 poison, i64 poison, i32 noundef 1, i64* noalias nocapture nofree noundef nonnull readonly align 8 dereferenceable(8) %0, i64 poison) #8, !dbg !57
  %84 = call i64 @rb_ary_push(i64 noundef %61, i64 noundef %83) #8, !dbg !57
  call void @llvm.lifetime.end.p0i8(i64 noundef 8, i8* noundef nonnull %64) #8, !dbg !57
  %85 = add nuw nsw i64 %67, 1, !dbg !57
  br label %66, !dbg !57, !llvm.loop !60

forward_sorbet_rb_array_collect_withBlock.exit.i: ; preds = %.thread.i.i, %71
  call void @sorbet_popFrame() #8, !dbg !57
  %86 = and i64 %61, 7, !dbg !52
  %87 = icmp ne i64 %86, 0, !dbg !52
  %88 = and i64 %61, -9, !dbg !52
  %89 = icmp eq i64 %88, 0, !dbg !52
  %90 = or i1 %87, %89, !dbg !52
  br i1 %90, label %sorbet_isa_Array.exit, label %91, !dbg !52

91:                                               ; preds = %forward_sorbet_rb_array_collect_withBlock.exit.i
  %92 = inttoptr i64 %61 to %struct.RBasic*, !dbg !52
  %93 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %92, i64 0, i32 0, !dbg !52
  %94 = load i64, i64* %93, align 8, !dbg !52, !tbaa !29
  %95 = and i64 %94, 31, !dbg !52
  %96 = icmp eq i64 %95, 7, !dbg !52
  br label %sorbet_isa_Array.exit, !dbg !52

sorbet_isa_Array.exit:                            ; preds = %forward_sorbet_rb_array_collect_withBlock.exit.i, %91
  %97 = phi i1 [ false, %forward_sorbet_rb_array_collect_withBlock.exit.i ], [ %96, %91 ], !dbg !52
  call void @llvm.assume(i1 noundef %97), !dbg !52
  %98 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !52, !tbaa !16
  %99 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %98, i64 0, i32 5, !dbg !52
  %100 = load i32, i32* %99, align 8, !dbg !52, !tbaa !36
  %101 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %98, i64 0, i32 6, !dbg !52
  %102 = load i32, i32* %101, align 4, !dbg !52, !tbaa !37
  %103 = xor i32 %102, -1, !dbg !52
  %104 = and i32 %103, %100, !dbg !52
  %105 = icmp eq i32 %104, 0, !dbg !52
  br i1 %105, label %"func_<root>.13<static-init>.exit", label %106, !dbg !52, !prof !31

106:                                              ; preds = %sorbet_isa_Array.exit
  %107 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %98, i64 0, i32 8, !dbg !52
  %108 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %107, align 8, !dbg !52, !tbaa !38
  %109 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %108, i32 noundef 0) #8, !dbg !52
  br label %"func_<root>.13<static-init>.exit", !dbg !52

"func_<root>.13<static-init>.exit":               ; preds = %sorbet_isa_Array.exit, %106
  store i64* getelementptr inbounds ([5 x i64], [5 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %19, align 8, !tbaa !16
  %110 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !39
  %111 = load i64*, i64** %110, align 8, !dbg !39
  store i64 %8, i64* %111, align 8, !dbg !39, !tbaa !5
  %112 = getelementptr inbounds i64, i64* %111, i64 1, !dbg !39
  store i64 %61, i64* %112, align 8, !dbg !39, !tbaa !5
  %113 = getelementptr inbounds i64, i64* %112, i64 1, !dbg !39
  store i64* %113, i64** %110, align 8, !dbg !39
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !39
  call void @llvm.lifetime.end.p0i8(i64 24, i8* nonnull %12)
  ret void
}

attributes #0 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #1 = { argmemonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #2 = { inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #3 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #4 = { mustprogress nocallback nofree nosync nounwind readnone speculatable willreturn }
attributes #5 = { nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #6 = { noreturn nounwind }
attributes #7 = { willreturn }
attributes #8 = { nounwind }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!4 = !DIFile(filename: "test/testdata/compiler/block_args.rb", directory: ".")
!5 = !{!6, !6, i64 0}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>$block_1", scope: !10, file: !4, line: 4, type: !15, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!10 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>", scope: null, file: !4, line: 4, type: !11, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !14)
!11 = !DISubroutineType(cc: DW_CC_nocall, types: !12)
!12 = !{!13}
!13 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!14 = !{}
!15 = !DISubroutineType(types: !12)
!16 = !{!17, !17, i64 0}
!17 = !{!"any pointer", !7, i64 0}
!18 = !{!19, !17, i64 16}
!19 = !{!"rb_execution_context_struct", !17, i64 0, !6, i64 8, !17, i64 16, !17, i64 24, !17, i64 32, !20, i64 40, !20, i64 44, !17, i64 48, !17, i64 56, !17, i64 64, !6, i64 72, !6, i64 80, !17, i64 88, !6, i64 96, !17, i64 104, !17, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !21, i64 152}
!20 = !{!"int", !7, i64 0}
!21 = !{!"", !17, i64 0, !17, i64 8, !6, i64 16, !7, i64 24}
!22 = !{!23, !17, i64 16}
!23 = !{!"rb_control_frame_struct", !17, i64 0, !17, i64 8, !17, i64 16, !6, i64 24, !17, i64 32, !17, i64 40, !17, i64 48}
!24 = !{!23, !17, i64 32}
!25 = !DILocation(line: 4, column: 1, scope: !9)
!26 = !{!"branch_weights", i32 1, i32 2000}
!27 = !DILocation(line: 4, column: 25, scope: !9)
!28 = !DILocation(line: 4, column: 21, scope: !9)
!29 = !{!30, !6, i64 0}
!30 = !{!"RBasic", !6, i64 0, !6, i64 8}
!31 = !{!"branch_weights", i32 2000, i32 1}
!32 = !{!33}
!33 = distinct !{!33, !34, !"sorbet_rb_int_plus: argument 0"}
!34 = distinct !{!34, !"sorbet_rb_int_plus"}
!35 = !{!"branch_weights", i32 4000000, i32 4001}
!36 = !{!19, !20, i64 40}
!37 = !{!19, !20, i64 44}
!38 = !{!19, !17, i64 56}
!39 = !DILocation(line: 4, column: 1, scope: !10)
!40 = !{!41, !6, i64 376}
!41 = !{!"rb_vm_struct", !6, i64 0, !42, i64 8, !17, i64 216, !47, i64 224, !7, i64 232, !43, i64 272, !43, i64 288, !43, i64 304, !20, i64 320, !20, i64 324, !20, i64 324, !20, i64 324, !20, i64 324, !6, i64 328, !7, i64 336, !6, i64 376, !6, i64 384, !6, i64 392, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !17, i64 432, !17, i64 440, !48, i64 448, !17, i64 968, !17, i64 976, !20, i64 984, !20, i64 988, !43, i64 992, !7, i64 1008, !6, i64 1048, !6, i64 1056, !6, i64 1064, !20, i64 1072, !17, i64 1080, !17, i64 1088, !17, i64 1096, !17, i64 1104, !17, i64 1112, !17, i64 1120, !20, i64 1128, !17, i64 1136, !7, i64 1144, !49, i64 9328, !7, i64 9360}
!42 = !{!"", !43, i64 0, !20, i64 16, !20, i64 20, !17, i64 24, !17, i64 32, !45, i64 40}
!43 = !{!"list_head", !44, i64 0}
!44 = !{!"list_node", !17, i64 0, !17, i64 8}
!45 = !{!"", !7, i64 0, !17, i64 40, !20, i64 48, !46, i64 52, !20, i64 56, !7, i64 64, !7, i64 112, !46, i64 160}
!46 = !{!"_Bool", !7, i64 0}
!47 = !{!"long long", !7, i64 0}
!48 = !{!"", !7, i64 0}
!49 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!50 = !DILocation(line: 4, column: 7, scope: !10)
!51 = !DILocation(line: 4, column: 9, scope: !10)
!52 = !DILocation(line: 4, column: 6, scope: !10)
!53 = !{!54}
!54 = distinct !{!54, !55, !"sorbet_buildArrayIntrinsic: argument 0"}
!55 = distinct !{!55, !"sorbet_buildArrayIntrinsic"}
!56 = !{!7, !7, i64 0}
!57 = !DILocation(line: 4, column: 6, scope: !10, inlinedAt: !58)
!58 = distinct !DILocation(line: 4, column: 6, scope: !10)
!59 = !{!19, !6, i64 128}
!60 = distinct !{!60, !61}
!61 = !{!"llvm.loop.unroll.disable"}
