; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.anon.2, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, i32, i8, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.rb_id_table*, [1023 x %struct.rb_callcache*], %struct.anon.9, [29 x i16] }
%struct.anon.2 = type { %struct.list_head, i32, i32, %struct.rb_ractor_struct*, %struct.rb_thread_struct*, %struct.anon.3 }
%struct.rb_ractor_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_ractor_struct*, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_waiting_list*, %union.anon.12, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64, i32, i64, %struct.rb_ext_config, i8* }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.rb_id_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.16 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.15, i32, i32, i32, i32, i8, i8, %struct.rb_id_table* }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.anon.1 }
%struct.anon.1 = type { %struct.rb_thread_struct*, i64 }
%struct.rb_call_data = type { %struct.rb_callinfo*, %struct.rb_callcache* }
%struct.rb_callinfo = type { i64, %struct.rb_callinfo_kwarg*, i64, i64, i64 }
%struct.rb_callinfo_kwarg = type { i32, [0 x i64] }
%struct.rb_callcache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*)*, %union.__atomic_wide_counter }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.__atomic_wide_counter = type { i64 }
%struct.anon.15 = type { i64, i64, i64, i64* }
%union.anon.16 = type { %struct.anon.17 }
%struct.anon.17 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { %struct.rb_callinfo*, %struct.rb_callcache*, i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.11 }
%union.anon.11 = type { %union.pthread_cond_t }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.__atomic_wide_counter, %union.__atomic_wide_counter, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_waiting_list = type { %struct.rb_waiting_list*, %struct.rb_thread_struct*, %struct.rb_fiber_struct* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.rb_ext_config = type { i8 }
%struct.anon.3 = type { %union.pthread_mutex_t, %struct.rb_ractor_struct*, i32, i8, i32, %union.pthread_cond_t, %union.pthread_cond_t, i8 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.rb_id_table = type opaque
%struct.anon.9 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_call_data }
%struct.RBasic = type { i64, i64 }

@ruby_vm_global_constant_state = external local_unnamed_addr global i64, align 8
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_ec = external thread_local local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@"stackFramePrecomputed_func_<root>.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@iseqEncodedArray = internal global [30 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@"stackFramePrecomputed_func_Object#6fooAll" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Object#7fooAny1" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Object#7fooAny2" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Object#6fooInt" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@"stackFramePrecomputed_func_Object#8fooArray" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@ic_fooInt = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@ic_fooAny1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.1 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_fooAny2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.2 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_fooAll = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.3 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_fooArray = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.4 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_all = internal global %struct.FunctionInlineCache zeroinitializer
@ic_any = internal global %struct.FunctionInlineCache zeroinitializer
@ic_any.5 = internal global %struct.FunctionInlineCache zeroinitializer
@"ic_[]" = internal global %struct.FunctionInlineCache zeroinitializer
@sorbet_moduleStringTable = internal unnamed_addr constant [258 x i8] c"<top (required)>\00test/testdata/compiler/casts.rb\00fooAll\00normal\00Object\00arg\00fooAny1\00fooAny2\00fooInt\00fooArray\00puts\00<build-array>\00master\00BasicObject\00Kernel\00all\00T\00T.cast\00Integer\00Float\00any\00T.any(Integer, Float)\00T.any(Float, Integer)\00+\00[]\00T::Array\00T::Array[Integer]\00", align 1
@sorbet_moduleIDTable = internal unnamed_addr global [14 x i64] zeroinitializer, align 8
@sorbet_moduleIDDescriptors = internal unnamed_addr constant [14 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 49, i32 6 }, %struct.rb_code_position_struct { i32 56, i32 6 }, %struct.rb_code_position_struct { i32 70, i32 3 }, %struct.rb_code_position_struct { i32 74, i32 7 }, %struct.rb_code_position_struct { i32 82, i32 7 }, %struct.rb_code_position_struct { i32 90, i32 6 }, %struct.rb_code_position_struct { i32 97, i32 8 }, %struct.rb_code_position_struct { i32 106, i32 4 }, %struct.rb_code_position_struct { i32 111, i32 13 }, %struct.rb_code_position_struct { i32 151, i32 3 }, %struct.rb_code_position_struct { i32 178, i32 3 }, %struct.rb_code_position_struct { i32 226, i32 1 }, %struct.rb_code_position_struct { i32 228, i32 2 }], align 8
@sorbet_moduleRubyStringTable = internal unnamed_addr global [7 x i64] zeroinitializer, align 8
@sorbet_moduleRubyStringDescriptors = internal unnamed_addr constant [7 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 17, i32 31 }, %struct.rb_code_position_struct { i32 49, i32 6 }, %struct.rb_code_position_struct { i32 74, i32 7 }, %struct.rb_code_position_struct { i32 82, i32 7 }, %struct.rb_code_position_struct { i32 90, i32 6 }, %struct.rb_code_position_struct { i32 97, i32 8 }], align 8
@rb_cBasicObject = external local_unnamed_addr constant i64
@rb_mKernel = external local_unnamed_addr constant i64
@guard_epoch_T = linkonce local_unnamed_addr global i64 0
@guarded_const_T = linkonce local_unnamed_addr global i64 0
@rb_cInteger = external local_unnamed_addr constant i64
@rb_cFloat = external local_unnamed_addr constant i64
@"guard_epoch_T::Array" = linkonce local_unnamed_addr global i64 0
@"guarded_const_T::Array" = linkonce local_unnamed_addr global i64 0
@rb_cObject = external local_unnamed_addr constant i64

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i64 @rb_id2sym(i64 noundef) local_unnamed_addr #0

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i64 @rb_obj_is_kind_of(i64 noundef, i64 noundef) local_unnamed_addr #0

; Function Attrs: cold noreturn
declare void @sorbet_cast_failure(i64 noundef, i8* noundef, i8* noundef) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @sorbet_raiseArity(i32 noundef, i32 noundef, i32 noundef) local_unnamed_addr #2

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef, i64 noundef, i64 noundef, i64 noundef, %struct.rb_iseq_struct* noundef, i32 noundef, i32 noundef, %struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #3

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef) local_unnamed_addr #3

declare i64 @sorbet_getConstant(i8* noundef, i64 noundef) local_unnamed_addr #3

declare i64 @sorbet_readRealpath() local_unnamed_addr #3

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef, i64 noundef, i32 noundef, i32 noundef, i32 noundef, ...) local_unnamed_addr #3

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef, i64 noundef) local_unnamed_addr #3

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #3

declare i64 @sorbet_rb_int_plus_slowpath(i64 noundef, i64 noundef) local_unnamed_addr #3

declare void @sorbet_vm_define_method(i64 noundef, i8* noundef, i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef, i8* noundef, %struct.rb_iseq_struct* noundef, i1 noundef zeroext) local_unnamed_addr #3

declare void @sorbet_vm_intern_ids(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #3

declare void @sorbet_vm_init_string_table(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #3

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #4

declare i64 @rb_ary_new_from_values(i64 noundef, i64* noundef) local_unnamed_addr #3

; Function Attrs: noreturn
declare void @rb_raise(i64 noundef, i8* noundef, ...) local_unnamed_addr #2

declare i64 @rb_int2big(i64 noundef) local_unnamed_addr #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind readnone speculatable willreturn
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64) #5

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #4

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef, i32 noundef) local_unnamed_addr #3

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xcalloc(i64 noundef, i64 noundef) local_unnamed_addr #6

; Function Attrs: allocsize(0,1)
declare noalias nonnull i8* @ruby_xmalloc2(i64 noundef, i64 noundef) local_unnamed_addr #6

; Function Attrs: argmemonly mustprogress nocallback nofree nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #7

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #8 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i32 0, i32 0)) #13
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #8 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i32 0, i32 0)) #13
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @"func_Object#6fooAll"(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #9 !dbg !9 {
functionEntryInitializers:
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %0, align 8, !tbaa !14
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !16
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !16
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !16
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !16, !prof !17

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #14, !dbg !16
  unreachable, !dbg !16

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !16
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %0, align 8, !dbg !18, !tbaa !14
  %1 = load i64, i64* @rb_cBasicObject, align 8, !dbg !19
  %2 = load i64, i64* @rb_mKernel, align 8, !dbg !19
  %3 = load i64, i64* @guard_epoch_T, align 8, !dbg !19
  %4 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !19, !tbaa !20
  %needTakeSlowPath = icmp ne i64 %3, %4, !dbg !19
  br i1 %needTakeSlowPath, label %5, label %6, !dbg !19, !prof !22

5:                                                ; preds = %fillRequiredArgs
  tail call void @const_recompute_T(), !dbg !19
  br label %6, !dbg !19

6:                                                ; preds = %fillRequiredArgs, %5
  %7 = load i64, i64* @guarded_const_T, align 8, !dbg !19
  %8 = load i64, i64* @guard_epoch_T, align 8, !dbg !19
  %9 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !19, !tbaa !20
  %guardUpdated = icmp eq i64 %8, %9, !dbg !19
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !19
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !19
  %11 = load i64*, i64** %10, align 8, !dbg !19
  store i64 %7, i64* %11, align 8, !dbg !19, !tbaa !5
  %12 = getelementptr inbounds i64, i64* %11, i64 1, !dbg !19
  store i64 %1, i64* %12, align 8, !dbg !19, !tbaa !5
  %13 = getelementptr inbounds i64, i64* %12, i64 1, !dbg !19
  store i64 %2, i64* %13, align 8, !dbg !19, !tbaa !5
  %14 = getelementptr inbounds i64, i64* %13, i64 1, !dbg !19
  store i64* %14, i64** %10, align 8, !dbg !19
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_all, i64 0), !dbg !19
  %15 = tail call i64 @rb_obj_is_kind_of(i64 %rawArg_arg, i64 %2), !dbg !23
  %16 = icmp eq i64 %15, 20, !dbg !23
  br i1 %16, label %typeTestSuccess, label %codeRepl, !dbg !23, !prof !24

typeTestSuccess:                                  ; preds = %6
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %6
  tail call fastcc void @"func_Object#6fooAll.cold.1"(i64 %rawArg_arg) #15, !dbg !23
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @"func_Object#7fooAny1"(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #9 !dbg !25 {
functionEntryInitializers:
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %0, align 8, !tbaa !14
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !26
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !26
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !26
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !26, !prof !17

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #14, !dbg !26
  unreachable, !dbg !26

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !26
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 10), i64** %0, align 8, !dbg !27, !tbaa !14
  %1 = load i64, i64* @rb_cInteger, align 8, !dbg !28
  %2 = load i64, i64* @rb_cFloat, align 8, !dbg !28
  %3 = load i64, i64* @guard_epoch_T, align 8, !dbg !28
  %4 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !28, !tbaa !20
  %needTakeSlowPath = icmp ne i64 %3, %4, !dbg !28
  br i1 %needTakeSlowPath, label %5, label %6, !dbg !28, !prof !22

5:                                                ; preds = %fillRequiredArgs
  tail call void @const_recompute_T(), !dbg !28
  br label %6, !dbg !28

6:                                                ; preds = %fillRequiredArgs, %5
  %7 = load i64, i64* @guarded_const_T, align 8, !dbg !28
  %8 = load i64, i64* @guard_epoch_T, align 8, !dbg !28
  %9 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !28, !tbaa !20
  %guardUpdated = icmp eq i64 %8, %9, !dbg !28
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !28
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !28
  %11 = load i64*, i64** %10, align 8, !dbg !28
  store i64 %7, i64* %11, align 8, !dbg !28, !tbaa !5
  %12 = getelementptr inbounds i64, i64* %11, i64 1, !dbg !28
  store i64 %1, i64* %12, align 8, !dbg !28, !tbaa !5
  %13 = getelementptr inbounds i64, i64* %12, i64 1, !dbg !28
  store i64 %2, i64* %13, align 8, !dbg !28, !tbaa !5
  %14 = getelementptr inbounds i64, i64* %13, i64 1, !dbg !28
  store i64* %14, i64** %10, align 8, !dbg !28
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_any, i64 0), !dbg !28
  %15 = and i64 %rawArg_arg, 1, !dbg !29
  %16 = icmp eq i64 %15, 0, !dbg !29
  br i1 %16, label %17, label %typeTestSuccess, !dbg !29, !prof !30

17:                                               ; preds = %6
  %18 = and i64 %rawArg_arg, 7, !dbg !29
  %19 = icmp ne i64 %18, 0, !dbg !29
  %20 = and i64 %rawArg_arg, -9, !dbg !29
  %21 = icmp eq i64 %20, 0, !dbg !29
  %22 = or i1 %19, %21, !dbg !29
  br i1 %22, label %orCase, label %sorbet_isa_Integer.exit, !dbg !29

sorbet_isa_Integer.exit:                          ; preds = %17
  %23 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !29
  %24 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %23, i64 0, i32 0, !dbg !29
  %25 = load i64, i64* %24, align 8, !dbg !29, !tbaa !31
  %26 = and i64 %25, 31, !dbg !29
  %27 = icmp eq i64 %26, 10, !dbg !29
  %28 = and i64 %rawArg_arg, 3, !dbg !29
  %29 = icmp eq i64 %28, 2, !dbg !29
  %or.cond21 = select i1 %27, i1 true, i1 %29, !dbg !29
  br i1 %or.cond21, label %typeTestSuccess, label %30, !dbg !29

orCase:                                           ; preds = %17
  %.old = and i64 %rawArg_arg, 3, !dbg !29
  %.old20 = icmp eq i64 %.old, 2, !dbg !29
  br i1 %.old20, label %typeTestSuccess, label %30, !dbg !29

30:                                               ; preds = %sorbet_isa_Integer.exit, %orCase
  %31 = and i64 %rawArg_arg, 7, !dbg !29
  %32 = icmp ne i64 %31, 0, !dbg !29
  %33 = and i64 %rawArg_arg, -9, !dbg !29
  %34 = icmp eq i64 %33, 0, !dbg !29
  %35 = or i1 %32, %34, !dbg !29
  br i1 %35, label %codeRepl, label %sorbet_isa_Float.exit, !dbg !29

sorbet_isa_Float.exit:                            ; preds = %30
  %36 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !29
  %37 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %36, i64 0, i32 0, !dbg !29
  %38 = load i64, i64* %37, align 8, !dbg !29, !tbaa !31
  %39 = and i64 %38, 31, !dbg !29
  %40 = icmp eq i64 %39, 4, !dbg !29
  br i1 %40, label %typeTestSuccess, label %codeRepl, !dbg !29, !prof !24

typeTestSuccess:                                  ; preds = %orCase, %6, %sorbet_isa_Integer.exit, %sorbet_isa_Float.exit
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %30, %sorbet_isa_Float.exit
  tail call fastcc void @"func_Object#7fooAny1.cold.1"(i64 %rawArg_arg) #15, !dbg !29
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @"func_Object#7fooAny2"(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #9 !dbg !33 {
functionEntryInitializers:
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %0, align 8, !tbaa !14
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !34
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !34
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !34
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !34, !prof !17

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #14, !dbg !34
  unreachable, !dbg !34

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !34
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 14), i64** %0, align 8, !dbg !35, !tbaa !14
  %1 = load i64, i64* @rb_cFloat, align 8, !dbg !36
  %2 = load i64, i64* @rb_cInteger, align 8, !dbg !36
  %3 = load i64, i64* @guard_epoch_T, align 8, !dbg !36
  %4 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !36, !tbaa !20
  %needTakeSlowPath = icmp ne i64 %3, %4, !dbg !36
  br i1 %needTakeSlowPath, label %5, label %6, !dbg !36, !prof !22

5:                                                ; preds = %fillRequiredArgs
  tail call void @const_recompute_T(), !dbg !36
  br label %6, !dbg !36

6:                                                ; preds = %fillRequiredArgs, %5
  %7 = load i64, i64* @guarded_const_T, align 8, !dbg !36
  %8 = load i64, i64* @guard_epoch_T, align 8, !dbg !36
  %9 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !36, !tbaa !20
  %guardUpdated = icmp eq i64 %8, %9, !dbg !36
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !36
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !36
  %11 = load i64*, i64** %10, align 8, !dbg !36
  store i64 %7, i64* %11, align 8, !dbg !36, !tbaa !5
  %12 = getelementptr inbounds i64, i64* %11, i64 1, !dbg !36
  store i64 %1, i64* %12, align 8, !dbg !36, !tbaa !5
  %13 = getelementptr inbounds i64, i64* %12, i64 1, !dbg !36
  store i64 %2, i64* %13, align 8, !dbg !36, !tbaa !5
  %14 = getelementptr inbounds i64, i64* %13, i64 1, !dbg !36
  store i64* %14, i64** %10, align 8, !dbg !36
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_any.5, i64 0), !dbg !36
  %15 = and i64 %rawArg_arg, 3, !dbg !37
  %16 = icmp eq i64 %15, 2, !dbg !37
  br i1 %16, label %typeTestSuccess, label %17, !dbg !37

17:                                               ; preds = %6
  %18 = and i64 %rawArg_arg, 7, !dbg !37
  %19 = icmp ne i64 %18, 0, !dbg !37
  %20 = and i64 %rawArg_arg, -9, !dbg !37
  %21 = icmp eq i64 %20, 0, !dbg !37
  %22 = or i1 %19, %21, !dbg !37
  br i1 %22, label %orCase, label %sorbet_isa_Float.exit, !dbg !37

sorbet_isa_Float.exit:                            ; preds = %17
  %23 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !37
  %24 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %23, i64 0, i32 0, !dbg !37
  %25 = load i64, i64* %24, align 8, !dbg !37, !tbaa !31
  %26 = and i64 %25, 31, !dbg !37
  %27 = icmp ne i64 %26, 4, !dbg !37
  %28 = and i64 %rawArg_arg, 1, !dbg !37
  %29 = icmp eq i64 %28, 0, !dbg !37
  %or.cond21 = select i1 %27, i1 %29, i1 false, !dbg !37
  br i1 %or.cond21, label %30, label %typeTestSuccess, !dbg !37, !prof !38

orCase:                                           ; preds = %17
  %.old = and i64 %rawArg_arg, 1, !dbg !37
  %.old20 = icmp eq i64 %.old, 0, !dbg !37
  br i1 %.old20, label %30, label %typeTestSuccess, !dbg !37, !prof !30

30:                                               ; preds = %sorbet_isa_Float.exit, %orCase
  %31 = and i64 %rawArg_arg, 7, !dbg !37
  %32 = icmp ne i64 %31, 0, !dbg !37
  %33 = and i64 %rawArg_arg, -9, !dbg !37
  %34 = icmp eq i64 %33, 0, !dbg !37
  %35 = or i1 %32, %34, !dbg !37
  br i1 %35, label %codeRepl, label %sorbet_isa_Integer.exit, !dbg !37

sorbet_isa_Integer.exit:                          ; preds = %30
  %36 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !37
  %37 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %36, i64 0, i32 0, !dbg !37
  %38 = load i64, i64* %37, align 8, !dbg !37, !tbaa !31
  %39 = and i64 %38, 31, !dbg !37
  %40 = icmp eq i64 %39, 10, !dbg !37
  br i1 %40, label %typeTestSuccess, label %codeRepl, !dbg !37, !prof !24

typeTestSuccess:                                  ; preds = %orCase, %6, %sorbet_isa_Float.exit, %sorbet_isa_Integer.exit
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %30, %sorbet_isa_Integer.exit
  tail call fastcc void @"func_Object#7fooAny2.cold.1"(i64 %rawArg_arg) #15, !dbg !37
  unreachable
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @"func_Object#6fooInt"(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nocapture nofree nonnull writeonly align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #9 !dbg !39 {
functionEntryInitializers:
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 17), i64** %0, align 8, !tbaa !14
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !40
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !40
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !40
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !40, !prof !17

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #14, !dbg !40
  unreachable, !dbg !40

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !40
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 18), i64** %0, align 8, !dbg !41, !tbaa !14
  %1 = and i64 %rawArg_arg, 1, !dbg !42
  %2 = icmp eq i64 %1, 0, !dbg !42
  br i1 %2, label %3, label %"fastSymCallIntrinsic_Integer_+", !dbg !42, !prof !30

3:                                                ; preds = %fillRequiredArgs
  %4 = and i64 %rawArg_arg, 7, !dbg !42
  %5 = icmp ne i64 %4, 0, !dbg !42
  %6 = and i64 %rawArg_arg, -9, !dbg !42
  %7 = icmp eq i64 %6, 0, !dbg !42
  %8 = or i1 %5, %7, !dbg !42
  br i1 %8, label %codeRepl, label %sorbet_isa_Integer.exit, !dbg !42

sorbet_isa_Integer.exit:                          ; preds = %3
  %9 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !42
  %10 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %9, i64 0, i32 0, !dbg !42
  %11 = load i64, i64* %10, align 8, !dbg !42, !tbaa !31
  %12 = and i64 %11, 31, !dbg !42
  %13 = icmp eq i64 %12, 10, !dbg !42
  br i1 %13, label %"fastSymCallIntrinsic_Integer_+", label %codeRepl, !dbg !42, !prof !24

codeRepl:                                         ; preds = %3, %sorbet_isa_Integer.exit
  tail call fastcc void @"func_Object#6fooInt.cold.1"(i64 %rawArg_arg) #15, !dbg !42
  unreachable

"fastSymCallIntrinsic_Integer_+":                 ; preds = %fillRequiredArgs, %sorbet_isa_Integer.exit
  tail call void @llvm.experimental.noalias.scope.decl(metadata !43), !dbg !42
  %14 = and i64 %rawArg_arg, 1, !dbg !42
  %15 = icmp ne i64 %14, 0, !dbg !42
  br i1 %15, label %16, label %25, !dbg !42, !prof !46

16:                                               ; preds = %"fastSymCallIntrinsic_Integer_+"
  %17 = add nsw i64 %rawArg_arg, -1, !dbg !42
  %18 = tail call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 noundef %rawArg_arg, i64 %17), !dbg !42
  %19 = extractvalue { i64, i1 } %18, 1, !dbg !42
  %20 = extractvalue { i64, i1 } %18, 0, !dbg !42
  br i1 %19, label %21, label %sorbet_rb_int_plus.exit, !dbg !42

21:                                               ; preds = %16
  %22 = ashr i64 %20, 1, !dbg !42
  %23 = xor i64 %22, -9223372036854775808, !dbg !42
  %24 = tail call i64 @rb_int2big(i64 noundef %23) #16, !dbg !42, !noalias !43
  br label %sorbet_rb_int_plus.exit, !dbg !42

25:                                               ; preds = %"fastSymCallIntrinsic_Integer_+"
  %26 = tail call i64 @sorbet_rb_int_plus_slowpath(i64 noundef %rawArg_arg, i64 noundef %rawArg_arg) #16, !dbg !42, !noalias !43
  br label %sorbet_rb_int_plus.exit, !dbg !42

sorbet_rb_int_plus.exit:                          ; preds = %16, %21, %25
  %27 = phi i64 [ %26, %25 ], [ %24, %21 ], [ %20, %16 ], !dbg !42
  %28 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !42, !tbaa !14
  %29 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 5, !dbg !42
  %30 = load i32, i32* %29, align 8, !dbg !42, !tbaa !47
  %31 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 6, !dbg !42
  %32 = load i32, i32* %31, align 4, !dbg !42, !tbaa !51
  %33 = xor i32 %32, -1, !dbg !42
  %34 = and i32 %33, %30, !dbg !42
  %35 = icmp eq i32 %34, 0, !dbg !42
  br i1 %35, label %sorbet_afterIntrinsic.exit, label %36, !dbg !42, !prof !24

36:                                               ; preds = %sorbet_rb_int_plus.exit
  %37 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %28, i64 0, i32 8, !dbg !42
  %38 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %37, align 8, !dbg !42, !tbaa !52
  %39 = tail call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %38, i32 noundef 0) #16, !dbg !42
  br label %sorbet_afterIntrinsic.exit, !dbg !42

sorbet_afterIntrinsic.exit:                       ; preds = %sorbet_rb_int_plus.exit, %36
  ret i64 %27
}

; Function Attrs: nounwind sspreq uwtable
define internal i64 @"func_Object#8fooArray"(i32 %argc, i64* nocapture nofree readonly %argArray, i64 %selfRaw, %struct.rb_control_frame_struct* nonnull align 8 dereferenceable(8) %cfp, i8* nocapture nofree readnone %calling, i8* nocapture nofree readnone %callData) #9 !dbg !53 {
functionEntryInitializers:
  %0 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 21), i64** %0, align 8, !tbaa !14
  %tooManyArgs = icmp ugt i32 %argc, 1, !dbg !54
  %tooFewArgs = icmp ult i32 %argc, 1, !dbg !54
  %or.cond = or i1 %tooManyArgs, %tooFewArgs, !dbg !54
  br i1 %or.cond, label %argCountFailBlock, label %fillRequiredArgs, !dbg !54, !prof !17

argCountFailBlock:                                ; preds = %functionEntryInitializers
  tail call void @sorbet_raiseArity(i32 noundef %argc, i32 noundef 1, i32 noundef 1) #14, !dbg !54
  unreachable, !dbg !54

fillRequiredArgs:                                 ; preds = %functionEntryInitializers
  %rawArg_arg = load i64, i64* %argArray, align 8, !dbg !54
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 22), i64** %0, align 8, !dbg !55, !tbaa !14
  %1 = load i64, i64* @rb_cInteger, align 8, !dbg !56
  %2 = load i64, i64* @"guard_epoch_T::Array", align 8, !dbg !56
  %3 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !56, !tbaa !20
  %needTakeSlowPath = icmp ne i64 %2, %3, !dbg !56
  br i1 %needTakeSlowPath, label %4, label %5, !dbg !56, !prof !22

4:                                                ; preds = %fillRequiredArgs
  tail call void @"const_recompute_T::Array"(), !dbg !56
  br label %5, !dbg !56

5:                                                ; preds = %fillRequiredArgs, %4
  %6 = load i64, i64* @"guarded_const_T::Array", align 8, !dbg !56
  %7 = load i64, i64* @"guard_epoch_T::Array", align 8, !dbg !56
  %8 = load i64, i64* @ruby_vm_global_constant_state, align 8, !dbg !56, !tbaa !20
  %guardUpdated = icmp eq i64 %7, %8, !dbg !56
  tail call void @llvm.assume(i1 %guardUpdated), !dbg !56
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %cfp, i64 0, i32 1, !dbg !56
  %10 = load i64*, i64** %9, align 8, !dbg !56
  store i64 %6, i64* %10, align 8, !dbg !56, !tbaa !5
  %11 = getelementptr inbounds i64, i64* %10, i64 1, !dbg !56
  store i64 %1, i64* %11, align 8, !dbg !56, !tbaa !5
  %12 = getelementptr inbounds i64, i64* %11, i64 1, !dbg !56
  store i64* %12, i64** %9, align 8, !dbg !56
  %send = tail call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @"ic_[]", i64 0), !dbg !56
  %13 = and i64 %rawArg_arg, 7, !dbg !57
  %14 = icmp ne i64 %13, 0, !dbg !57
  %15 = and i64 %rawArg_arg, -9, !dbg !57
  %16 = icmp eq i64 %15, 0, !dbg !57
  %17 = or i1 %14, %16, !dbg !57
  br i1 %17, label %codeRepl, label %sorbet_isa_Array.exit, !dbg !57

sorbet_isa_Array.exit:                            ; preds = %5
  %18 = inttoptr i64 %rawArg_arg to %struct.RBasic*, !dbg !57
  %19 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %18, i64 0, i32 0, !dbg !57
  %20 = load i64, i64* %19, align 8, !dbg !57, !tbaa !31
  %21 = and i64 %20, 31, !dbg !57
  %22 = icmp eq i64 %21, 7, !dbg !57
  br i1 %22, label %typeTestSuccess, label %codeRepl, !dbg !57, !prof !24

typeTestSuccess:                                  ; preds = %sorbet_isa_Array.exit
  ret i64 %rawArg_arg

codeRepl:                                         ; preds = %5, %sorbet_isa_Array.exit
  tail call fastcc void @"func_Object#8fooArray.cold.1"(i64 %rawArg_arg) #15, !dbg !57
  unreachable
}

define void @Init_casts() local_unnamed_addr {
entry:
  %callArgs.i = alloca [4 x i64], align 8
  %positional_table.i = alloca i64, align 8, !dbg !58
  %positional_table82.i = alloca i64, align 8, !dbg !61
  %positional_table94.i = alloca i64, align 8, !dbg !62
  %positional_table106.i = alloca i64, align 8, !dbg !63
  %positional_table118.i = alloca i64, align 8, !dbg !64
  %locals.i15.i = alloca i64, i32 0, align 8
  %locals.i13.i = alloca i64, i32 0, align 8
  %locals.i11.i = alloca i64, i32 0, align 8
  %locals.i9.i = alloca i64, i32 0, align 8
  %locals.i7.i = alloca i64, i32 0, align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  tail call void @sorbet_vm_intern_ids(i64* noundef getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([14 x %struct.rb_code_position_struct], [14 x %struct.rb_code_position_struct]* @sorbet_moduleIDDescriptors, i32 0, i32 0), i32 noundef 14, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_vm_init_string_table(i64* noundef getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([7 x %struct.rb_code_position_struct], [7 x %struct.rb_code_position_struct]* @sorbet_moduleRubyStringDescriptors, i32 0, i32 0), i32 noundef 7, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 30)
  %"rubyId_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), align 8, !invariant.load !13
  %"rubyStr_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), align 8, !invariant.load !13
  %"rubyStr_test/testdata/compiler/casts.rb.i.i" = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 1), align 8, !invariant.load !13
  %0 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<top (required)>.i.i", i64 noundef %"rubyId_<top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %0, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %rubyId_fooInt.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 6), align 8, !dbg !65, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_fooInt, i64 noundef %rubyId_fooInt.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !65
  %rubyId_puts.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 8), align 8, !dbg !66, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !66
  %rubyId_fooAny1.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 4), align 8, !dbg !67, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_fooAny1, i64 noundef %rubyId_fooAny1.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !67
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.1, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !68
  %rubyId_fooAny2.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 5), align 8, !dbg !69, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_fooAny2, i64 noundef %rubyId_fooAny2.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !69
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.2, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !70
  %rubyId_fooAll.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 1), align 8, !dbg !71, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_fooAll, i64 noundef %rubyId_fooAll.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !71
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.3, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !72
  %rubyId_fooArray.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 7), align 8, !dbg !73, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_fooArray, i64 noundef %rubyId_fooArray.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !73
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.4, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !74
  %rubyStr_fooAll.i.i = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 2), align 8, !invariant.load !13
  %1 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_fooAll.i.i, i64 noundef %rubyId_fooAll.i, i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i7.i, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %1, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#6fooAll", align 8
  %rubyId_all.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 10), align 8, !dbg !19, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_all, i64 noundef %rubyId_all.i, i32 noundef 16, i32 noundef 2, i32 noundef 0), !dbg !19
  %rubyStr_fooAny1.i.i = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 3), align 8, !invariant.load !13
  %2 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_fooAny1.i.i, i64 noundef %rubyId_fooAny1.i, i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 9, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i9.i, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %2, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#7fooAny1", align 8
  %rubyId_any.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 11), align 8, !dbg !28, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_any, i64 noundef %rubyId_any.i, i32 noundef 16, i32 noundef 2, i32 noundef 0), !dbg !28
  %rubyStr_fooAny2.i.i = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 4), align 8, !invariant.load !13
  %3 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_fooAny2.i.i, i64 noundef %rubyId_fooAny2.i, i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 13, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i11.i, i32 noundef 0, i32 noundef 3)
  store %struct.rb_iseq_struct* %3, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#7fooAny2", align 8
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_any.5, i64 noundef %rubyId_any.i, i32 noundef 16, i32 noundef 2, i32 noundef 0), !dbg !36
  %rubyStr_fooInt.i.i = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 5), align 8, !invariant.load !13
  %4 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_fooInt.i.i, i64 noundef %rubyId_fooInt.i, i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 17, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i13.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %4, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#6fooInt", align 8
  %rubyStr_fooArray.i.i = load i64, i64* getelementptr inbounds ([7 x i64], [7 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 6), align 8, !invariant.load !13
  %5 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %rubyStr_fooArray.i.i, i64 noundef %rubyId_fooArray.i, i64 noundef %"rubyStr_test/testdata/compiler/casts.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 1, i32 noundef 21, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i15.i, i32 noundef 0, i32 noundef 2)
  store %struct.rb_iseq_struct* %5, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#8fooArray", align 8
  %"rubyId_[].i" = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 13), align 8, !dbg !56, !invariant.load !13
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @"ic_[]", i64 noundef %"rubyId_[].i", i32 noundef 16, i32 noundef 1, i32 noundef 0), !dbg !56
  %6 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !14
  %7 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %6, i64 0, i32 12
  %8 = load i64, i64* %7, align 8, !tbaa !75
  %9 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !14
  %10 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %9, i64 0, i32 2
  %11 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !tbaa !84
  %12 = bitcast [4 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 32, i8* nonnull %12)
  %13 = bitcast i64* %positional_table.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %13)
  %14 = bitcast i64* %positional_table82.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %14)
  %15 = bitcast i64* %positional_table94.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %15)
  %16 = bitcast i64* %positional_table106.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %16)
  %17 = bitcast i64* %positional_table118.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %17)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %18 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %10, align 8, !tbaa !84
  %19 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %18, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %19, align 8, !tbaa !85
  %20 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %18, i64 0, i32 4
  %21 = load i64*, i64** %20, align 8, !tbaa !87
  %22 = load i64, i64* %21, align 8, !tbaa !5
  %23 = and i64 %22, -33
  store i64 %23, i64* %21, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %9, %struct.rb_control_frame_struct* noundef %18, %struct.rb_iseq_struct* noundef %stackFrame.i) #16
  %24 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 0
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %24, align 8, !tbaa !14
  %rawSym.i = call i64 @rb_id2sym(i64 noundef %rubyId_fooAll.i), !dbg !58
  %25 = and i64 %rawSym.i, 255, !dbg !58
  %26 = icmp eq i64 %25, 12, !dbg !58
  br i1 %26, label %sorbet_isa_Symbol.exit, label %27, !dbg !58

27:                                               ; preds = %entry
  %28 = and i64 %rawSym.i, 7, !dbg !58
  %29 = icmp ne i64 %28, 0, !dbg !58
  %30 = and i64 %rawSym.i, -9, !dbg !58
  %31 = icmp eq i64 %30, 0, !dbg !58
  %32 = or i1 %29, %31, !dbg !58
  br i1 %32, label %sorbet_isa_Symbol.exit, label %33, !dbg !58

33:                                               ; preds = %27
  %34 = inttoptr i64 %rawSym.i to %struct.RBasic*, !dbg !58
  %35 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %34, i64 0, i32 0, !dbg !58
  %36 = load i64, i64* %35, align 8, !dbg !58, !tbaa !31
  %37 = and i64 %36, 31, !dbg !58
  %38 = icmp eq i64 %37, 20, !dbg !58
  br label %sorbet_isa_Symbol.exit, !dbg !58

sorbet_isa_Symbol.exit:                           ; preds = %entry, %27, %33
  %39 = phi i1 [ true, %entry ], [ %38, %33 ], [ false, %27 ], !dbg !58
  call void @llvm.assume(i1 noundef %39), !dbg !58
  %rubyId_normal.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 2), align 8, !dbg !58, !invariant.load !13
  %rawSym70.i = call i64 @rb_id2sym(i64 noundef %rubyId_normal.i), !dbg !58
  %40 = and i64 %rawSym70.i, 255, !dbg !58
  %41 = icmp eq i64 %40, 12, !dbg !58
  br i1 %41, label %sorbet_isa_Symbol.exit28, label %42, !dbg !58

42:                                               ; preds = %sorbet_isa_Symbol.exit
  %43 = and i64 %rawSym70.i, 7, !dbg !58
  %44 = icmp ne i64 %43, 0, !dbg !58
  %45 = and i64 %rawSym70.i, -9, !dbg !58
  %46 = icmp eq i64 %45, 0, !dbg !58
  %47 = or i1 %44, %46, !dbg !58
  br i1 %47, label %sorbet_isa_Symbol.exit28, label %48, !dbg !58

48:                                               ; preds = %42
  %49 = inttoptr i64 %rawSym70.i to %struct.RBasic*, !dbg !58
  %50 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %49, i64 0, i32 0, !dbg !58
  %51 = load i64, i64* %50, align 8, !dbg !58, !tbaa !31
  %52 = and i64 %51, 31, !dbg !58
  %53 = icmp eq i64 %52, 20, !dbg !58
  br label %sorbet_isa_Symbol.exit28, !dbg !58

sorbet_isa_Symbol.exit28:                         ; preds = %sorbet_isa_Symbol.exit, %42, %48
  %54 = phi i1 [ true, %sorbet_isa_Symbol.exit ], [ %53, %48 ], [ false, %42 ], !dbg !58
  call void @llvm.assume(i1 noundef %54), !dbg !58
  %55 = load i64, i64* @rb_cObject, align 8, !dbg !58
  %stackFrame71.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#6fooAll", align 8, !dbg !58
  %56 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !58
  %57 = bitcast i8* %56 to i16*, !dbg !58
  %58 = load i16, i16* %57, align 8, !dbg !58
  %59 = and i16 %58, -384, !dbg !58
  %60 = or i16 %59, 1, !dbg !58
  store i16 %60, i16* %57, align 8, !dbg !58
  %61 = getelementptr inbounds i8, i8* %56, i64 12, !dbg !58
  %62 = getelementptr inbounds i8, i8* %56, i64 4, !dbg !58
  %63 = bitcast i8* %62 to i32*, !dbg !58
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %61, i8 0, i64 20, i1 false), !dbg !58
  %64 = bitcast i32* %63 to <2 x i32>*, !dbg !58
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %64, align 4, !dbg !58, !tbaa !88
  %rubyId_arg.i = load i64, i64* getelementptr inbounds ([14 x i64], [14 x i64]* @sorbet_moduleIDTable, i64 0, i64 3), align 8, !dbg !58, !invariant.load !13
  store i64 %rubyId_arg.i, i64* %positional_table.i, align 8, !dbg !58
  %65 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !58
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %65, i8* noundef nonnull align 1 %13, i64 noundef 8, i1 noundef false), !dbg !58
  %66 = getelementptr inbounds i8, i8* %56, i64 32, !dbg !58
  %67 = bitcast i8* %66 to i8**, !dbg !58
  store i8* %65, i8** %67, align 8, !dbg !58, !tbaa !89
  call void @sorbet_vm_define_method(i64 noundef %55, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 49), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @"func_Object#6fooAll", i8* noundef nonnull %56, %struct.rb_iseq_struct* noundef %stackFrame71.i, i1 noundef zeroext false) #16, !dbg !58
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %24, align 8, !dbg !58, !tbaa !14
  %rawSym73.i = call i64 @rb_id2sym(i64 noundef %rubyId_fooAny1.i), !dbg !61
  %68 = and i64 %rawSym73.i, 255, !dbg !61
  %69 = icmp eq i64 %68, 12, !dbg !61
  br i1 %69, label %sorbet_isa_Symbol.exit27, label %70, !dbg !61

70:                                               ; preds = %sorbet_isa_Symbol.exit28
  %71 = and i64 %rawSym73.i, 7, !dbg !61
  %72 = icmp ne i64 %71, 0, !dbg !61
  %73 = and i64 %rawSym73.i, -9, !dbg !61
  %74 = icmp eq i64 %73, 0, !dbg !61
  %75 = or i1 %72, %74, !dbg !61
  br i1 %75, label %sorbet_isa_Symbol.exit27, label %76, !dbg !61

76:                                               ; preds = %70
  %77 = inttoptr i64 %rawSym73.i to %struct.RBasic*, !dbg !61
  %78 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %77, i64 0, i32 0, !dbg !61
  %79 = load i64, i64* %78, align 8, !dbg !61, !tbaa !31
  %80 = and i64 %79, 31, !dbg !61
  %81 = icmp eq i64 %80, 20, !dbg !61
  br label %sorbet_isa_Symbol.exit27, !dbg !61

sorbet_isa_Symbol.exit27:                         ; preds = %sorbet_isa_Symbol.exit28, %70, %76
  %82 = phi i1 [ true, %sorbet_isa_Symbol.exit28 ], [ %81, %76 ], [ false, %70 ], !dbg !61
  call void @llvm.assume(i1 noundef %82), !dbg !61
  %stackFrame80.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#7fooAny1", align 8, !dbg !61
  %83 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !61
  %84 = bitcast i8* %83 to i16*, !dbg !61
  %85 = load i16, i16* %84, align 8, !dbg !61
  %86 = and i16 %85, -384, !dbg !61
  %87 = or i16 %86, 1, !dbg !61
  store i16 %87, i16* %84, align 8, !dbg !61
  %88 = getelementptr inbounds i8, i8* %83, i64 12, !dbg !61
  %89 = getelementptr inbounds i8, i8* %83, i64 4, !dbg !61
  %90 = bitcast i8* %89 to i32*, !dbg !61
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %88, i8 0, i64 20, i1 false), !dbg !61
  %91 = bitcast i32* %90 to <2 x i32>*, !dbg !61
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %91, align 4, !dbg !61, !tbaa !88
  store i64 %rubyId_arg.i, i64* %positional_table82.i, align 8, !dbg !61
  %92 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !61
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %92, i8* noundef nonnull align 1 %14, i64 noundef 8, i1 noundef false), !dbg !61
  %93 = getelementptr inbounds i8, i8* %83, i64 32, !dbg !61
  %94 = bitcast i8* %93 to i8**, !dbg !61
  store i8* %92, i8** %94, align 8, !dbg !61, !tbaa !89
  call void @sorbet_vm_define_method(i64 noundef %55, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 74), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @"func_Object#7fooAny1", i8* noundef nonnull %83, %struct.rb_iseq_struct* noundef %stackFrame80.i, i1 noundef zeroext false) #16, !dbg !61
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 13), i64** %24, align 8, !dbg !61, !tbaa !14
  %rawSym85.i = call i64 @rb_id2sym(i64 noundef %rubyId_fooAny2.i), !dbg !62
  %95 = and i64 %rawSym85.i, 255, !dbg !62
  %96 = icmp eq i64 %95, 12, !dbg !62
  br i1 %96, label %sorbet_isa_Symbol.exit26, label %97, !dbg !62

97:                                               ; preds = %sorbet_isa_Symbol.exit27
  %98 = and i64 %rawSym85.i, 7, !dbg !62
  %99 = icmp ne i64 %98, 0, !dbg !62
  %100 = and i64 %rawSym85.i, -9, !dbg !62
  %101 = icmp eq i64 %100, 0, !dbg !62
  %102 = or i1 %99, %101, !dbg !62
  br i1 %102, label %sorbet_isa_Symbol.exit26, label %103, !dbg !62

103:                                              ; preds = %97
  %104 = inttoptr i64 %rawSym85.i to %struct.RBasic*, !dbg !62
  %105 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %104, i64 0, i32 0, !dbg !62
  %106 = load i64, i64* %105, align 8, !dbg !62, !tbaa !31
  %107 = and i64 %106, 31, !dbg !62
  %108 = icmp eq i64 %107, 20, !dbg !62
  br label %sorbet_isa_Symbol.exit26, !dbg !62

sorbet_isa_Symbol.exit26:                         ; preds = %sorbet_isa_Symbol.exit27, %97, %103
  %109 = phi i1 [ true, %sorbet_isa_Symbol.exit27 ], [ %108, %103 ], [ false, %97 ], !dbg !62
  call void @llvm.assume(i1 noundef %109), !dbg !62
  %stackFrame92.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#7fooAny2", align 8, !dbg !62
  %110 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !62
  %111 = bitcast i8* %110 to i16*, !dbg !62
  %112 = load i16, i16* %111, align 8, !dbg !62
  %113 = and i16 %112, -384, !dbg !62
  %114 = or i16 %113, 1, !dbg !62
  store i16 %114, i16* %111, align 8, !dbg !62
  %115 = getelementptr inbounds i8, i8* %110, i64 12, !dbg !62
  %116 = getelementptr inbounds i8, i8* %110, i64 4, !dbg !62
  %117 = bitcast i8* %116 to i32*, !dbg !62
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %115, i8 0, i64 20, i1 false), !dbg !62
  %118 = bitcast i32* %117 to <2 x i32>*, !dbg !62
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %118, align 4, !dbg !62, !tbaa !88
  store i64 %rubyId_arg.i, i64* %positional_table94.i, align 8, !dbg !62
  %119 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !62
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %119, i8* noundef nonnull align 1 %15, i64 noundef 8, i1 noundef false), !dbg !62
  %120 = getelementptr inbounds i8, i8* %110, i64 32, !dbg !62
  %121 = bitcast i8* %120 to i8**, !dbg !62
  store i8* %119, i8** %121, align 8, !dbg !62, !tbaa !89
  call void @sorbet_vm_define_method(i64 noundef %55, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 82), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @"func_Object#7fooAny2", i8* noundef nonnull %110, %struct.rb_iseq_struct* noundef %stackFrame92.i, i1 noundef zeroext false) #16, !dbg !62
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 17), i64** %24, align 8, !dbg !62, !tbaa !14
  %rawSym97.i = call i64 @rb_id2sym(i64 noundef %rubyId_fooInt.i), !dbg !63
  %122 = and i64 %rawSym97.i, 255, !dbg !63
  %123 = icmp eq i64 %122, 12, !dbg !63
  br i1 %123, label %sorbet_isa_Symbol.exit25, label %124, !dbg !63

124:                                              ; preds = %sorbet_isa_Symbol.exit26
  %125 = and i64 %rawSym97.i, 7, !dbg !63
  %126 = icmp ne i64 %125, 0, !dbg !63
  %127 = and i64 %rawSym97.i, -9, !dbg !63
  %128 = icmp eq i64 %127, 0, !dbg !63
  %129 = or i1 %126, %128, !dbg !63
  br i1 %129, label %sorbet_isa_Symbol.exit25, label %130, !dbg !63

130:                                              ; preds = %124
  %131 = inttoptr i64 %rawSym97.i to %struct.RBasic*, !dbg !63
  %132 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %131, i64 0, i32 0, !dbg !63
  %133 = load i64, i64* %132, align 8, !dbg !63, !tbaa !31
  %134 = and i64 %133, 31, !dbg !63
  %135 = icmp eq i64 %134, 20, !dbg !63
  br label %sorbet_isa_Symbol.exit25, !dbg !63

sorbet_isa_Symbol.exit25:                         ; preds = %sorbet_isa_Symbol.exit26, %124, %130
  %136 = phi i1 [ true, %sorbet_isa_Symbol.exit26 ], [ %135, %130 ], [ false, %124 ], !dbg !63
  call void @llvm.assume(i1 noundef %136), !dbg !63
  %stackFrame104.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#6fooInt", align 8, !dbg !63
  %137 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !63
  %138 = bitcast i8* %137 to i16*, !dbg !63
  %139 = load i16, i16* %138, align 8, !dbg !63
  %140 = and i16 %139, -384, !dbg !63
  %141 = or i16 %140, 1, !dbg !63
  store i16 %141, i16* %138, align 8, !dbg !63
  %142 = getelementptr inbounds i8, i8* %137, i64 12, !dbg !63
  %143 = getelementptr inbounds i8, i8* %137, i64 4, !dbg !63
  %144 = bitcast i8* %143 to i32*, !dbg !63
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %142, i8 0, i64 20, i1 false), !dbg !63
  %145 = bitcast i32* %144 to <2 x i32>*, !dbg !63
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %145, align 4, !dbg !63, !tbaa !88
  store i64 %rubyId_arg.i, i64* %positional_table106.i, align 8, !dbg !63
  %146 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !63
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %146, i8* noundef nonnull align 1 %16, i64 noundef 8, i1 noundef false), !dbg !63
  %147 = getelementptr inbounds i8, i8* %137, i64 32, !dbg !63
  %148 = bitcast i8* %147 to i8**, !dbg !63
  store i8* %146, i8** %148, align 8, !dbg !63, !tbaa !89
  call void @sorbet_vm_define_method(i64 noundef %55, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 90), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @"func_Object#6fooInt", i8* noundef nonnull %137, %struct.rb_iseq_struct* noundef %stackFrame104.i, i1 noundef zeroext false) #16, !dbg !63
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 21), i64** %24, align 8, !dbg !63, !tbaa !14
  %rawSym109.i = call i64 @rb_id2sym(i64 noundef %rubyId_fooArray.i), !dbg !64
  %149 = and i64 %rawSym109.i, 255, !dbg !64
  %150 = icmp eq i64 %149, 12, !dbg !64
  br i1 %150, label %sorbet_isa_Symbol.exit24, label %151, !dbg !64

151:                                              ; preds = %sorbet_isa_Symbol.exit25
  %152 = and i64 %rawSym109.i, 7, !dbg !64
  %153 = icmp ne i64 %152, 0, !dbg !64
  %154 = and i64 %rawSym109.i, -9, !dbg !64
  %155 = icmp eq i64 %154, 0, !dbg !64
  %156 = or i1 %153, %155, !dbg !64
  br i1 %156, label %sorbet_isa_Symbol.exit24, label %157, !dbg !64

157:                                              ; preds = %151
  %158 = inttoptr i64 %rawSym109.i to %struct.RBasic*, !dbg !64
  %159 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %158, i64 0, i32 0, !dbg !64
  %160 = load i64, i64* %159, align 8, !dbg !64, !tbaa !31
  %161 = and i64 %160, 31, !dbg !64
  %162 = icmp eq i64 %161, 20, !dbg !64
  br label %sorbet_isa_Symbol.exit24, !dbg !64

sorbet_isa_Symbol.exit24:                         ; preds = %sorbet_isa_Symbol.exit25, %151, %157
  %163 = phi i1 [ true, %sorbet_isa_Symbol.exit25 ], [ %162, %157 ], [ false, %151 ], !dbg !64
  call void @llvm.assume(i1 noundef %163), !dbg !64
  %stackFrame116.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_Object#8fooArray", align 8, !dbg !64
  %164 = call noalias nonnull dereferenceable(64) i8* @ruby_xcalloc(i64 noundef 1, i64 noundef 64) #17, !dbg !64
  %165 = bitcast i8* %164 to i16*, !dbg !64
  %166 = load i16, i16* %165, align 8, !dbg !64
  %167 = and i16 %166, -384, !dbg !64
  %168 = or i16 %167, 1, !dbg !64
  store i16 %168, i16* %165, align 8, !dbg !64
  %169 = getelementptr inbounds i8, i8* %164, i64 12, !dbg !64
  %170 = getelementptr inbounds i8, i8* %164, i64 4, !dbg !64
  %171 = bitcast i8* %170 to i32*, !dbg !64
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 %169, i8 0, i64 20, i1 false), !dbg !64
  %172 = bitcast i32* %171 to <2 x i32>*, !dbg !64
  store <2 x i32> <i32 1, i32 1>, <2 x i32>* %172, align 4, !dbg !64, !tbaa !88
  store i64 %rubyId_arg.i, i64* %positional_table118.i, align 8, !dbg !64
  %173 = call noalias nonnull i8* @ruby_xmalloc2(i64 noundef 1, i64 noundef 8) #17, !dbg !64
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 1 %173, i8* noundef nonnull align 1 %17, i64 noundef 8, i1 noundef false), !dbg !64
  %174 = getelementptr inbounds i8, i8* %164, i64 32, !dbg !64
  %175 = bitcast i8* %174 to i8**, !dbg !64
  store i8* %173, i8** %175, align 8, !dbg !64, !tbaa !89
  call void @sorbet_vm_define_method(i64 noundef %55, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 97), i64 (i32, i64*, i64, %struct.rb_control_frame_struct*, i8*, i8*)* noundef @"func_Object#8fooArray", i8* noundef nonnull %164, %struct.rb_iseq_struct* noundef %stackFrame116.i, i1 noundef zeroext false) #16, !dbg !64
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 25), i64** %24, align 8, !dbg !64, !tbaa !14
  call void @llvm.assume(i1 noundef true), !dbg !92
  %176 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !65
  %177 = load i64*, i64** %176, align 8, !dbg !65
  store i64 %8, i64* %177, align 8, !dbg !65, !tbaa !5
  %178 = getelementptr inbounds i64, i64* %177, i64 1, !dbg !65
  store i64 5, i64* %178, align 8, !dbg !65, !tbaa !5
  %179 = getelementptr inbounds i64, i64* %178, i64 1, !dbg !65
  store i64* %179, i64** %176, align 8, !dbg !65
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_fooInt, i64 0), !dbg !65
  %180 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !66
  %181 = load i64*, i64** %180, align 8, !dbg !66
  store i64 %8, i64* %181, align 8, !dbg !66, !tbaa !5
  %182 = getelementptr inbounds i64, i64* %181, i64 1, !dbg !66
  store i64 %send, i64* %182, align 8, !dbg !66, !tbaa !5
  %183 = getelementptr inbounds i64, i64* %182, i64 1, !dbg !66
  store i64* %183, i64** %180, align 8, !dbg !66
  %send7 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !66
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 26), i64** %24, align 8, !dbg !66, !tbaa !14
  %184 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !67
  %185 = load i64*, i64** %184, align 8, !dbg !67
  store i64 %8, i64* %185, align 8, !dbg !67, !tbaa !5
  %186 = getelementptr inbounds i64, i64* %185, i64 1, !dbg !67
  store i64 5, i64* %186, align 8, !dbg !67, !tbaa !5
  %187 = getelementptr inbounds i64, i64* %186, i64 1, !dbg !67
  store i64* %187, i64** %184, align 8, !dbg !67
  %send9 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_fooAny1, i64 0), !dbg !67
  %188 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !68
  %189 = load i64*, i64** %188, align 8, !dbg !68
  store i64 %8, i64* %189, align 8, !dbg !68, !tbaa !5
  %190 = getelementptr inbounds i64, i64* %189, i64 1, !dbg !68
  store i64 %send9, i64* %190, align 8, !dbg !68, !tbaa !5
  %191 = getelementptr inbounds i64, i64* %190, i64 1, !dbg !68
  store i64* %191, i64** %188, align 8, !dbg !68
  %send11 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.1, i64 0), !dbg !68
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 27), i64** %24, align 8, !dbg !68, !tbaa !14
  %192 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !69
  %193 = load i64*, i64** %192, align 8, !dbg !69
  store i64 %8, i64* %193, align 8, !dbg !69, !tbaa !5
  %194 = getelementptr inbounds i64, i64* %193, i64 1, !dbg !69
  store i64 5, i64* %194, align 8, !dbg !69, !tbaa !5
  %195 = getelementptr inbounds i64, i64* %194, i64 1, !dbg !69
  store i64* %195, i64** %192, align 8, !dbg !69
  %send13 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_fooAny2, i64 0), !dbg !69
  %196 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !70
  %197 = load i64*, i64** %196, align 8, !dbg !70
  store i64 %8, i64* %197, align 8, !dbg !70, !tbaa !5
  %198 = getelementptr inbounds i64, i64* %197, i64 1, !dbg !70
  store i64 %send13, i64* %198, align 8, !dbg !70, !tbaa !5
  %199 = getelementptr inbounds i64, i64* %198, i64 1, !dbg !70
  store i64* %199, i64** %196, align 8, !dbg !70
  %send15 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.2, i64 0), !dbg !70
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 28), i64** %24, align 8, !dbg !70, !tbaa !14
  %200 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !71
  %201 = load i64*, i64** %200, align 8, !dbg !71
  store i64 %8, i64* %201, align 8, !dbg !71, !tbaa !5
  %202 = getelementptr inbounds i64, i64* %201, i64 1, !dbg !71
  store i64 5, i64* %202, align 8, !dbg !71, !tbaa !5
  %203 = getelementptr inbounds i64, i64* %202, i64 1, !dbg !71
  store i64* %203, i64** %200, align 8, !dbg !71
  %send17 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_fooAll, i64 0), !dbg !71
  %204 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !72
  %205 = load i64*, i64** %204, align 8, !dbg !72
  store i64 %8, i64* %205, align 8, !dbg !72, !tbaa !5
  %206 = getelementptr inbounds i64, i64* %205, i64 1, !dbg !72
  store i64 %send17, i64* %206, align 8, !dbg !72, !tbaa !5
  %207 = getelementptr inbounds i64, i64* %206, i64 1, !dbg !72
  store i64* %207, i64** %204, align 8, !dbg !72
  %send19 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.3, i64 0), !dbg !72
  store i64* getelementptr inbounds ([30 x i64], [30 x i64]* @iseqEncodedArray, i64 0, i64 29), i64** %24, align 8, !dbg !72, !tbaa !14
  %callArgs0Addr.i = getelementptr [4 x i64], [4 x i64]* %callArgs.i, i64 0, i64 0, !dbg !93
  store i64 5, i64* %callArgs0Addr.i, align 8, !dbg !93
  call void @llvm.experimental.noalias.scope.decl(metadata !94), !dbg !93
  %208 = call i64 @rb_ary_new_from_values(i64 noundef 1, i64* noundef nonnull align 8 %callArgs0Addr.i) #16, !dbg !93
  %209 = and i64 %208, 7, !dbg !93
  %210 = icmp ne i64 %209, 0, !dbg !93
  %211 = and i64 %208, -9, !dbg !93
  %212 = icmp eq i64 %211, 0, !dbg !93
  %213 = or i1 %210, %212, !dbg !93
  br i1 %213, label %sorbet_isa_Array.exit, label %214, !dbg !93

214:                                              ; preds = %sorbet_isa_Symbol.exit24
  %215 = inttoptr i64 %208 to %struct.RBasic*, !dbg !93
  %216 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %215, i64 0, i32 0, !dbg !93
  %217 = load i64, i64* %216, align 8, !dbg !93, !tbaa !31
  %218 = and i64 %217, 31, !dbg !93
  %219 = icmp eq i64 %218, 7, !dbg !93
  br label %sorbet_isa_Array.exit, !dbg !93

sorbet_isa_Array.exit:                            ; preds = %sorbet_isa_Symbol.exit24, %214
  %220 = phi i1 [ false, %sorbet_isa_Symbol.exit24 ], [ %219, %214 ], !dbg !93
  call void @llvm.assume(i1 noundef %220), !dbg !93
  %221 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !73
  %222 = load i64*, i64** %221, align 8, !dbg !73
  store i64 %8, i64* %222, align 8, !dbg !73, !tbaa !5
  %223 = getelementptr inbounds i64, i64* %222, i64 1, !dbg !73
  store i64 %208, i64* %223, align 8, !dbg !73, !tbaa !5
  %224 = getelementptr inbounds i64, i64* %223, i64 1, !dbg !73
  store i64* %224, i64** %221, align 8, !dbg !73
  %send21 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_fooArray, i64 0), !dbg !73
  %225 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %11, i64 0, i32 1, !dbg !74
  %226 = load i64*, i64** %225, align 8, !dbg !74
  store i64 %8, i64* %226, align 8, !dbg !74, !tbaa !5
  %227 = getelementptr inbounds i64, i64* %226, i64 1, !dbg !74
  store i64 %send21, i64* %227, align 8, !dbg !74, !tbaa !5
  %228 = getelementptr inbounds i64, i64* %227, i64 1, !dbg !74
  store i64* %228, i64** %225, align 8, !dbg !74
  %send23 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.4, i64 0), !dbg !74
  call void @llvm.lifetime.end.p0i8(i64 32, i8* nonnull %12)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %13)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %14)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %15)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %16)
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %17)
  ret void
}

; Function Attrs: argmemonly nocallback nofree nounwind willreturn writeonly
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #10

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #11

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#6fooAll.cold.1"(i64 %rawArg_arg) unnamed_addr #12 !dbg !97 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 noundef %rawArg_arg, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 157), i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 144)) #14, !dbg !99
  unreachable, !dbg !99
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#7fooAny1.cold.1"(i64 %rawArg_arg) unnamed_addr #12 !dbg !100 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 noundef %rawArg_arg, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 157), i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 182)) #14, !dbg !101
  unreachable, !dbg !101
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#7fooAny2.cold.1"(i64 %rawArg_arg) unnamed_addr #12 !dbg !102 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 noundef %rawArg_arg, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 157), i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 204)) #14, !dbg !103
  unreachable, !dbg !103
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#6fooInt.cold.1"(i64 %rawArg_arg) unnamed_addr #12 !dbg !104 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 noundef %rawArg_arg, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 157), i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 164)) #14, !dbg !105
  unreachable, !dbg !105
}

; Function Attrs: cold minsize noreturn nounwind sspreq uwtable
define internal fastcc void @"func_Object#8fooArray.cold.1"(i64 %rawArg_arg) unnamed_addr #12 !dbg !106 {
newFuncRoot:
  tail call void @sorbet_cast_failure(i64 noundef %rawArg_arg, i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 157), i8* noundef getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 240)) #14, !dbg !107
  unreachable, !dbg !107
}

define linkonce void @const_recompute_T() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 155), i64 1)
  store i64 %1, i64* @guarded_const_T, align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !20
  store i64 %2, i64* @guard_epoch_T, align 8
  ret void
}

define linkonce void @"const_recompute_T::Array"() local_unnamed_addr {
  %1 = tail call i64 @sorbet_getConstant(i8* getelementptr inbounds ([258 x i8], [258 x i8]* @sorbet_moduleStringTable, i64 0, i64 231), i64 8)
  store i64 %1, i64* @"guarded_const_T::Array", align 8
  %2 = load i64, i64* @ruby_vm_global_constant_state, align 8, !tbaa !20
  store i64 %2, i64* @"guard_epoch_T::Array", align 8
  ret void
}

attributes #0 = { mustprogress nofree nosync nounwind readnone willreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #1 = { cold noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #2 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #3 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #4 = { inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #5 = { mustprogress nocallback nofree nosync nounwind readnone speculatable willreturn }
attributes #6 = { allocsize(0,1) "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #7 = { argmemonly mustprogress nocallback nofree nounwind willreturn }
attributes #8 = { nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #9 = { nounwind sspreq uwtable }
attributes #10 = { argmemonly nocallback nofree nounwind willreturn writeonly }
attributes #11 = { argmemonly nocallback nofree nosync nounwind willreturn }
attributes #12 = { cold minsize noreturn nounwind sspreq uwtable }
attributes #13 = { noreturn nounwind }
attributes #14 = { noreturn }
attributes #15 = { noinline }
attributes #16 = { nounwind }
attributes #17 = { nounwind allocsize(0,1) }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!4 = !DIFile(filename: "test/testdata/compiler/casts.rb", directory: ".")
!5 = !{!6, !6, i64 0}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = distinct !DISubprogram(name: "Object#fooAll", linkageName: "func_Object#6fooAll", scope: null, file: !4, line: 5, type: !10, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!10 = !DISubroutineType(types: !11)
!11 = !{!12}
!12 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!13 = !{}
!14 = !{!15, !15, i64 0}
!15 = !{!"any pointer", !7, i64 0}
!16 = !DILocation(line: 5, column: 1, scope: !9)
!17 = !{!"branch_weights", i32 4001, i32 4000000}
!18 = !DILocation(line: 5, column: 12, scope: !9)
!19 = !DILocation(line: 6, column: 15, scope: !9)
!20 = !{!21, !21, i64 0}
!21 = !{!"long long", !7, i64 0}
!22 = !{!"branch_weights", i32 1, i32 10000}
!23 = !DILocation(line: 6, column: 3, scope: !9)
!24 = !{!"branch_weights", i32 2000, i32 1}
!25 = distinct !DISubprogram(name: "Object#fooAny1", linkageName: "func_Object#7fooAny1", scope: null, file: !4, line: 9, type: !10, scopeLine: 9, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!26 = !DILocation(line: 9, column: 1, scope: !25)
!27 = !DILocation(line: 9, column: 13, scope: !25)
!28 = !DILocation(line: 10, column: 15, scope: !25)
!29 = !DILocation(line: 10, column: 3, scope: !25)
!30 = !{!"branch_weights", i32 1, i32 2000}
!31 = !{!32, !6, i64 0}
!32 = !{!"RBasic", !6, i64 0, !6, i64 8}
!33 = distinct !DISubprogram(name: "Object#fooAny2", linkageName: "func_Object#7fooAny2", scope: null, file: !4, line: 13, type: !10, scopeLine: 13, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!34 = !DILocation(line: 13, column: 1, scope: !33)
!35 = !DILocation(line: 13, column: 13, scope: !33)
!36 = !DILocation(line: 14, column: 15, scope: !33)
!37 = !DILocation(line: 14, column: 3, scope: !33)
!38 = !{!"branch_weights", i32 1, i32 4001}
!39 = distinct !DISubprogram(name: "Object#fooInt", linkageName: "func_Object#6fooInt", scope: null, file: !4, line: 17, type: !10, scopeLine: 17, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!40 = !DILocation(line: 17, column: 1, scope: !39)
!41 = !DILocation(line: 17, column: 12, scope: !39)
!42 = !DILocation(line: 18, column: 3, scope: !39)
!43 = !{!44}
!44 = distinct !{!44, !45, !"sorbet_rb_int_plus: argument 0"}
!45 = distinct !{!45, !"sorbet_rb_int_plus"}
!46 = !{!"branch_weights", i32 4000000, i32 4001}
!47 = !{!48, !49, i64 40}
!48 = !{!"rb_execution_context_struct", !15, i64 0, !6, i64 8, !15, i64 16, !15, i64 24, !15, i64 32, !49, i64 40, !49, i64 44, !15, i64 48, !15, i64 56, !15, i64 64, !6, i64 72, !6, i64 80, !15, i64 88, !6, i64 96, !15, i64 104, !15, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !50, i64 152}
!49 = !{!"int", !7, i64 0}
!50 = !{!"", !15, i64 0, !15, i64 8, !6, i64 16, !7, i64 24}
!51 = !{!48, !49, i64 44}
!52 = !{!48, !15, i64 56}
!53 = distinct !DISubprogram(name: "Object#fooArray", linkageName: "func_Object#8fooArray", scope: null, file: !4, line: 21, type: !10, scopeLine: 21, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!54 = !DILocation(line: 21, column: 1, scope: !53)
!55 = !DILocation(line: 21, column: 14, scope: !53)
!56 = !DILocation(line: 22, column: 15, scope: !53)
!57 = !DILocation(line: 22, column: 3, scope: !53)
!58 = !DILocation(line: 5, column: 1, scope: !59)
!59 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>", scope: null, file: !4, line: 5, type: !60, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !13)
!60 = !DISubroutineType(cc: DW_CC_nocall, types: !11)
!61 = !DILocation(line: 9, column: 1, scope: !59)
!62 = !DILocation(line: 13, column: 1, scope: !59)
!63 = !DILocation(line: 17, column: 1, scope: !59)
!64 = !DILocation(line: 21, column: 1, scope: !59)
!65 = !DILocation(line: 25, column: 6, scope: !59)
!66 = !DILocation(line: 25, column: 1, scope: !59)
!67 = !DILocation(line: 26, column: 6, scope: !59)
!68 = !DILocation(line: 26, column: 1, scope: !59)
!69 = !DILocation(line: 27, column: 6, scope: !59)
!70 = !DILocation(line: 27, column: 1, scope: !59)
!71 = !DILocation(line: 28, column: 6, scope: !59)
!72 = !DILocation(line: 28, column: 1, scope: !59)
!73 = !DILocation(line: 29, column: 6, scope: !59)
!74 = !DILocation(line: 29, column: 1, scope: !59)
!75 = !{!76, !6, i64 376}
!76 = !{!"rb_vm_struct", !6, i64 0, !77, i64 8, !15, i64 216, !21, i64 224, !7, i64 232, !78, i64 272, !78, i64 288, !78, i64 304, !49, i64 320, !49, i64 324, !49, i64 324, !49, i64 324, !49, i64 324, !6, i64 328, !7, i64 336, !6, i64 376, !6, i64 384, !6, i64 392, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !15, i64 432, !15, i64 440, !82, i64 448, !15, i64 968, !15, i64 976, !49, i64 984, !49, i64 988, !78, i64 992, !7, i64 1008, !6, i64 1048, !6, i64 1056, !6, i64 1064, !49, i64 1072, !15, i64 1080, !15, i64 1088, !15, i64 1096, !15, i64 1104, !15, i64 1112, !15, i64 1120, !49, i64 1128, !15, i64 1136, !7, i64 1144, !83, i64 9328, !7, i64 9360}
!77 = !{!"", !78, i64 0, !49, i64 16, !49, i64 20, !15, i64 24, !15, i64 32, !80, i64 40}
!78 = !{!"list_head", !79, i64 0}
!79 = !{!"list_node", !15, i64 0, !15, i64 8}
!80 = !{!"", !7, i64 0, !15, i64 40, !49, i64 48, !81, i64 52, !49, i64 56, !7, i64 64, !7, i64 112, !81, i64 160}
!81 = !{!"_Bool", !7, i64 0}
!82 = !{!"", !7, i64 0}
!83 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!84 = !{!48, !15, i64 16}
!85 = !{!86, !15, i64 16}
!86 = !{!"rb_control_frame_struct", !15, i64 0, !15, i64 8, !15, i64 16, !6, i64 24, !15, i64 32, !15, i64 40, !15, i64 48}
!87 = !{!86, !15, i64 32}
!88 = !{!49, !49, i64 0}
!89 = !{!90, !15, i64 32}
!90 = !{!"rb_sorbet_param_struct", !91, i64 0, !49, i64 4, !49, i64 8, !49, i64 12, !49, i64 16, !49, i64 20, !49, i64 24, !49, i64 28, !15, i64 32, !49, i64 40, !49, i64 44, !49, i64 48, !49, i64 52, !15, i64 56}
!91 = !{!"", !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 0, !49, i64 1, !49, i64 1}
!92 = !DILocation(line: 25, column: 13, scope: !59)
!93 = !DILocation(line: 29, column: 15, scope: !59)
!94 = !{!95}
!95 = distinct !{!95, !96, !"sorbet_buildArrayIntrinsic: argument 0"}
!96 = distinct !{!96, !"sorbet_buildArrayIntrinsic"}
!97 = distinct !DISubprogram(name: "func_Object#6fooAll.cold.1", linkageName: "func_Object#6fooAll.cold.1", scope: null, file: !4, type: !98, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !13)
!98 = !DISubroutineType(types: !13)
!99 = !DILocation(line: 6, column: 3, scope: !97)
!100 = distinct !DISubprogram(name: "func_Object#7fooAny1.cold.1", linkageName: "func_Object#7fooAny1.cold.1", scope: null, file: !4, type: !98, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !13)
!101 = !DILocation(line: 10, column: 3, scope: !100)
!102 = distinct !DISubprogram(name: "func_Object#7fooAny2.cold.1", linkageName: "func_Object#7fooAny2.cold.1", scope: null, file: !4, type: !98, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !13)
!103 = !DILocation(line: 14, column: 3, scope: !102)
!104 = distinct !DISubprogram(name: "func_Object#6fooInt.cold.1", linkageName: "func_Object#6fooInt.cold.1", scope: null, file: !4, type: !98, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !13)
!105 = !DILocation(line: 18, column: 3, scope: !104)
!106 = distinct !DISubprogram(name: "func_Object#8fooArray.cold.1", linkageName: "func_Object#8fooArray.cold.1", scope: null, file: !4, type: !98, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !3, retainedNodes: !13)
!107 = !DILocation(line: 22, column: 3, scope: !106)
