; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.anon.2, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, i32, i8, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.rb_id_table*, [1023 x %struct.rb_callcache*], %struct.anon.9, [29 x i16] }
%struct.anon.2 = type { %struct.list_head, i32, i32, %struct.rb_ractor_struct*, %struct.rb_thread_struct*, %struct.anon.3 }
%struct.rb_ractor_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_ractor_struct*, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_waiting_list*, %union.anon.12, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64, i32, i64, %struct.rb_ext_config, i8* }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.rb_id_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.16 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.15, i32, i32, i32, i32, i8, i8, %struct.rb_id_table* }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.anon.1 }
%struct.anon.1 = type { %struct.rb_thread_struct*, i64 }
%struct.rb_call_data = type { %struct.rb_callinfo*, %struct.rb_callcache* }
%struct.rb_callinfo = type { i64, %struct.rb_callinfo_kwarg*, i64, i64, i64 }
%struct.rb_callinfo_kwarg = type { i32, [0 x i64] }
%struct.rb_callcache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*)*, %union.__atomic_wide_counter }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.__atomic_wide_counter = type { i64 }
%struct.anon.15 = type { i64, i64, i64, i64* }
%union.anon.16 = type { %struct.anon.17 }
%struct.anon.17 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { %struct.rb_callinfo*, %struct.rb_callcache*, i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.11 }
%union.anon.11 = type { %union.pthread_cond_t }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.__atomic_wide_counter, %union.__atomic_wide_counter, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_waiting_list = type { %struct.rb_waiting_list*, %struct.rb_thread_struct*, %struct.rb_fiber_struct* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.rb_ext_config = type { i8 }
%struct.anon.3 = type { %union.pthread_mutex_t, %struct.rb_ractor_struct*, i32, i8, i32, %union.pthread_cond_t, %union.pthread_cond_t, i8 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.rb_id_table = type opaque
%struct.anon.9 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_call_data }
%struct.RBasic = type { i64, i64 }

@.str.4 = private unnamed_addr constant [8 x i8] c"to_proc\00", align 1
@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_ec = external thread_local local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@"stackFramePrecomputed_func_<root>.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@iseqEncodedArray = internal global [7 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@ruby_hashLiteral1 = internal unnamed_addr global i64 0, align 8
@ic_map = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@sorbet_moduleStringTable = internal unnamed_addr constant [104 x i8] c"<top (required)>\00test/testdata/compiler/send_with_block_param.rb\00T\00unsafe\00<build-array>\00map\00puts\00master\00", align 1
@sorbet_moduleIDTable = internal unnamed_addr global [5 x i64] zeroinitializer, align 8
@sorbet_moduleIDDescriptors = internal unnamed_addr constant [5 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 67, i32 6 }, %struct.rb_code_position_struct { i32 74, i32 13 }, %struct.rb_code_position_struct { i32 88, i32 3 }, %struct.rb_code_position_struct { i32 92, i32 4 }], align 8
@sorbet_moduleRubyStringTable = internal unnamed_addr global [2 x i64] zeroinitializer, align 8
@sorbet_moduleRubyStringDescriptors = internal unnamed_addr constant [2 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 17, i32 47 }], align 8

; Function Attrs: mustprogress nofree nosync nounwind readnone willreturn
declare i64 @rb_id2sym(i64 noundef) local_unnamed_addr #0

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef, i64 noundef, i64 noundef, i64 noundef, %struct.rb_iseq_struct* noundef, i32 noundef, i32 noundef, %struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #1

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef) local_unnamed_addr #1

declare i64 @sorbet_readRealpath() local_unnamed_addr #1

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef, i64 noundef, i32 noundef, i32 noundef, i32 noundef, ...) local_unnamed_addr #1

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef, i64 noundef) local_unnamed_addr #1

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #1

declare i64 @sorbet_globalConstRegister(i64 noundef) local_unnamed_addr #1

declare i64 @sorbet_globalConstDupHash(i64 noundef) local_unnamed_addr #1

declare void @sorbet_vm_intern_ids(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #1

declare void @sorbet_vm_init_string_table(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #1

declare i64 @rb_intern2(i8* noundef, i64 noundef) local_unnamed_addr #1

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #2

declare i64 @rb_ary_new_from_values(i64 noundef, i64* noundef) local_unnamed_addr #1

declare i64 @rb_hash_new_with_size(i64 noundef) local_unnamed_addr #1

declare void @rb_hash_bulk_insert(i64 noundef, i64* noundef, i64 noundef) local_unnamed_addr #1

; Function Attrs: noreturn
declare void @rb_raise(i64 noundef, i8* noundef, ...) local_unnamed_addr #3

declare i64 @rb_funcall(i64 noundef, i64 noundef, i32 noundef, ...) local_unnamed_addr #1

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #2

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef, i32 noundef) local_unnamed_addr #1

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i32 0, i32 0)) #6
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #4 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i32 0, i32 0)) #6
  unreachable
}

define void @Init_send_with_block_param() local_unnamed_addr {
entry:
  %callArgs.i = alloca [4 x i64], align 8
  %argArray.i.i = alloca [2 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  tail call void @sorbet_vm_intern_ids(i64* noundef getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([5 x %struct.rb_code_position_struct], [5 x %struct.rb_code_position_struct]* @sorbet_moduleIDDescriptors, i32 0, i32 0), i32 noundef 5, i8* noundef getelementptr inbounds ([104 x i8], [104 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_vm_init_string_table(i64* noundef getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([2 x %struct.rb_code_position_struct], [2 x %struct.rb_code_position_struct]* @sorbet_moduleRubyStringDescriptors, i32 0, i32 0), i32 noundef 2, i8* noundef getelementptr inbounds ([104 x i8], [104 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 7)
  %"rubyId_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), align 8, !invariant.load !9
  %"rubyStr_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), align 8, !invariant.load !9
  %"rubyStr_test/testdata/compiler/send_with_block_param.rb.i.i" = load i64, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 1), align 8, !invariant.load !9
  %0 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<top (required)>.i.i", i64 noundef %"rubyId_<top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/send_with_block_param.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 4, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 4)
  store %struct.rb_iseq_struct* %0, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %1 = bitcast [2 x i64]* %argArray.i.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 16, i8* nonnull %1)
  call void @llvm.assume(i1 noundef true) #7
  %hashArgs0Addr.i.i = getelementptr [2 x i64], [2 x i64]* %argArray.i.i, i64 0, i64 0
  call void @llvm.assume(i1 noundef true) #7
  %2 = bitcast i64* %hashArgs0Addr.i.i to <2 x i64>*
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %2, align 8
  %3 = call i64 @rb_hash_new_with_size(i64 noundef 1) #8
  call void @rb_hash_bulk_insert(i64 noundef 2, i64* noundef nonnull %hashArgs0Addr.i.i, i64 noundef %3) #8
  %4 = call i64 @sorbet_globalConstRegister(i64 noundef %3) #8
  store i64 %4, i64* @ruby_hashLiteral1, align 8
  call void @llvm.lifetime.end.p0i8(i64 16, i8* nonnull %1)
  %rubyId_map.i = load i64, i64* getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i64 0, i64 3), align 8, !dbg !10, !invariant.load !9
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_map, i64 noundef %rubyId_map.i, i32 noundef 18, i32 noundef 0, i32 noundef 0), !dbg !10
  %rubyId_puts.i = load i64, i64* getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i64 0, i64 4), align 8, !dbg !15, !invariant.load !9
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !15
  %5 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !16
  %6 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %5, i64 0, i32 12
  %7 = load i64, i64* %6, align 8, !tbaa !18
  %8 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !16
  %9 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %8, i64 0, i32 2
  %10 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %9, align 8, !tbaa !29
  %11 = bitcast [4 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 32, i8* nonnull %11)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %12 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %9, align 8, !tbaa !29
  %13 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %12, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %13, align 8, !tbaa !32
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %12, i64 0, i32 4
  %15 = load i64*, i64** %14, align 8, !tbaa !34
  %16 = load i64, i64* %15, align 8, !tbaa !5
  %17 = and i64 %16, -33
  store i64 %17, i64* %15, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %8, %struct.rb_control_frame_struct* noundef %12, %struct.rb_iseq_struct* noundef %stackFrame.i) #8
  %18 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %10, i64 0, i32 0
  store i64* getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i64 0, i64 4), i64** %18, align 8, !tbaa !16
  %hashLiteral.i = load i64, i64* @ruby_hashLiteral1, align 8, !dbg !35
  %duplicatedHash.i = call i64 @sorbet_globalConstDupHash(i64 noundef %hashLiteral.i) #8, !dbg !35
  %19 = and i64 %duplicatedHash.i, 7, !dbg !35
  %20 = icmp ne i64 %19, 0, !dbg !35
  %21 = and i64 %duplicatedHash.i, -9, !dbg !35
  %22 = icmp eq i64 %21, 0, !dbg !35
  %23 = or i1 %20, %22, !dbg !35
  br i1 %23, label %sorbet_isa_Hash.exit, label %24, !dbg !35

24:                                               ; preds = %entry
  %25 = inttoptr i64 %duplicatedHash.i to %struct.RBasic*, !dbg !35
  %26 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %25, i64 0, i32 0, !dbg !35
  %27 = load i64, i64* %26, align 8, !dbg !35, !tbaa !36
  %28 = and i64 %27, 31, !dbg !35
  %29 = icmp eq i64 %28, 8, !dbg !35
  br label %sorbet_isa_Hash.exit, !dbg !35

sorbet_isa_Hash.exit:                             ; preds = %entry, %24
  %30 = phi i1 [ false, %entry ], [ %29, %24 ], !dbg !35
  call void @llvm.assume(i1 noundef %30), !dbg !35
  %callArgs0Addr.i = getelementptr [4 x i64], [4 x i64]* %callArgs.i, i64 0, i64 0, !dbg !38
  call void @llvm.experimental.noalias.scope.decl(metadata !39), !dbg !38
  %31 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !38, !tbaa !16
  %32 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %31, i64 0, i32 5, !dbg !38
  %33 = load i32, i32* %32, align 8, !dbg !38, !tbaa !42
  %34 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %31, i64 0, i32 6, !dbg !38
  %35 = load i32, i32* %34, align 4, !dbg !38, !tbaa !43
  %36 = xor i32 %35, -1, !dbg !38
  %37 = and i32 %36, %33, !dbg !38
  %38 = icmp eq i32 %37, 0, !dbg !38
  br i1 %38, label %sorbet_afterIntrinsic.exit.i, label %39, !dbg !38, !prof !44

39:                                               ; preds = %sorbet_isa_Hash.exit
  %40 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %31, i64 0, i32 8, !dbg !38
  %41 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %40, align 8, !dbg !38, !tbaa !45
  %42 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %41, i32 noundef 0) #8, !dbg !38
  br label %sorbet_afterIntrinsic.exit.i, !dbg !38

sorbet_afterIntrinsic.exit.i:                     ; preds = %39, %sorbet_isa_Hash.exit
  store i64* getelementptr inbounds ([7 x i64], [7 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %18, align 8, !dbg !38, !tbaa !16
  store i64 3, i64* %callArgs0Addr.i, align 8, !dbg !10
  call void @llvm.experimental.noalias.scope.decl(metadata !46), !dbg !10
  %43 = call i64 @rb_ary_new_from_values(i64 noundef 1, i64* noundef nonnull align 8 %callArgs0Addr.i) #8, !dbg !10
  %44 = and i64 %43, 7, !dbg !10
  %45 = icmp ne i64 %44, 0, !dbg !10
  %46 = and i64 %43, -9, !dbg !10
  %47 = icmp eq i64 %46, 0, !dbg !10
  %48 = or i1 %45, %47, !dbg !10
  br i1 %48, label %sorbet_isa_Array.exit, label %49, !dbg !10

49:                                               ; preds = %sorbet_afterIntrinsic.exit.i
  %50 = inttoptr i64 %43 to %struct.RBasic*, !dbg !10
  %51 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %50, i64 0, i32 0, !dbg !10
  %52 = load i64, i64* %51, align 8, !dbg !10, !tbaa !36
  %53 = and i64 %52, 31, !dbg !10
  %54 = icmp eq i64 %53, 7, !dbg !10
  br label %sorbet_isa_Array.exit, !dbg !10

sorbet_isa_Array.exit:                            ; preds = %sorbet_afterIntrinsic.exit.i, %49
  %55 = phi i1 [ false, %sorbet_afterIntrinsic.exit.i ], [ %54, %49 ], !dbg !10
  call void @llvm.assume(i1 noundef %55), !dbg !10
  %rawSym.i = call i64 @rb_id2sym(i64 noundef %rubyId_map.i), !dbg !10
  %56 = and i64 %rawSym.i, 255, !dbg !10
  %57 = icmp eq i64 %56, 12, !dbg !10
  br i1 %57, label %sorbet_isa_Symbol.exit, label %58, !dbg !10

58:                                               ; preds = %sorbet_isa_Array.exit
  %59 = and i64 %rawSym.i, 7, !dbg !10
  %60 = icmp ne i64 %59, 0, !dbg !10
  %61 = and i64 %rawSym.i, -9, !dbg !10
  %62 = icmp eq i64 %61, 0, !dbg !10
  %63 = or i1 %60, %62, !dbg !10
  br i1 %63, label %sorbet_isa_Symbol.exit, label %64, !dbg !10

64:                                               ; preds = %58
  %65 = inttoptr i64 %rawSym.i to %struct.RBasic*, !dbg !10
  %66 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %65, i64 0, i32 0, !dbg !10
  %67 = load i64, i64* %66, align 8, !dbg !10, !tbaa !36
  %68 = and i64 %67, 31, !dbg !10
  %69 = icmp eq i64 %68, 20, !dbg !10
  br label %sorbet_isa_Symbol.exit, !dbg !10

sorbet_isa_Symbol.exit:                           ; preds = %sorbet_isa_Array.exit, %58, %64
  %70 = phi i1 [ true, %sorbet_isa_Array.exit ], [ %69, %64 ], [ false, %58 ], !dbg !10
  call void @llvm.assume(i1 noundef %70), !dbg !10
  %71 = icmp eq i64 %duplicatedHash.i, 8, !dbg !10
  br i1 %71, label %"func_<root>.13<static-init>.exit", label %72, !dbg !10

72:                                               ; preds = %sorbet_isa_Symbol.exit
  %73 = call i64 @rb_intern2(i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @.str.4, i32 0, i32 0), i64 noundef 7) #8, !dbg !10
  %74 = call i64 (i64, i64, i32, ...) @rb_funcall(i64 noundef %duplicatedHash.i, i64 noundef %73, i32 noundef 0) #8, !dbg !10
  br label %"func_<root>.13<static-init>.exit", !dbg !10

"func_<root>.13<static-init>.exit":               ; preds = %sorbet_isa_Symbol.exit, %72
  %75 = phi i64 [ %74, %72 ], [ 0, %sorbet_isa_Symbol.exit ], !dbg !10
  %76 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %10, i64 0, i32 1, !dbg !10
  %77 = load i64*, i64** %76, align 8, !dbg !10
  store i64 %43, i64* %77, align 8, !dbg !10, !tbaa !5
  %78 = getelementptr inbounds i64, i64* %77, i64 1, !dbg !10
  store i64* %78, i64** %76, align 8, !dbg !10
  %send.i = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef @ic_map, i64 noundef %75) #8, !dbg !10
  %79 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %10, i64 0, i32 1, !dbg !15
  %80 = load i64*, i64** %79, align 8, !dbg !15
  store i64 %7, i64* %80, align 8, !dbg !15, !tbaa !5
  %81 = getelementptr inbounds i64, i64* %80, i64 1, !dbg !15
  store i64 %send.i, i64* %81, align 8, !dbg !15, !tbaa !5
  %82 = getelementptr inbounds i64, i64* %81, i64 1, !dbg !15
  store i64* %82, i64** %79, align 8, !dbg !15
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !15
  call void @llvm.lifetime.end.p0i8(i64 32, i8* nonnull %11)
  ret void
}

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #5

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #5

attributes #0 = { mustprogress nofree nosync nounwind readnone willreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #2 = { inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #3 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #4 = { nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #5 = { argmemonly nocallback nofree nosync nounwind willreturn }
attributes #6 = { noreturn nounwind }
attributes #7 = { willreturn }
attributes #8 = { nounwind }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!4 = !DIFile(filename: "test/testdata/compiler/send_with_block_param.rb", directory: ".")
!5 = !{!6, !6, i64 0}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{}
!10 = !DILocation(line: 6, column: 6, scope: !11)
!11 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>", scope: null, file: !4, line: 4, type: !12, scopeLine: 4, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !9)
!12 = !DISubroutineType(cc: DW_CC_nocall, types: !13)
!13 = !{!14}
!14 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!15 = !DILocation(line: 6, column: 1, scope: !11)
!16 = !{!17, !17, i64 0}
!17 = !{!"any pointer", !7, i64 0}
!18 = !{!19, !6, i64 376}
!19 = !{!"rb_vm_struct", !6, i64 0, !20, i64 8, !17, i64 216, !26, i64 224, !7, i64 232, !21, i64 272, !21, i64 288, !21, i64 304, !23, i64 320, !23, i64 324, !23, i64 324, !23, i64 324, !23, i64 324, !6, i64 328, !7, i64 336, !6, i64 376, !6, i64 384, !6, i64 392, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !17, i64 432, !17, i64 440, !27, i64 448, !17, i64 968, !17, i64 976, !23, i64 984, !23, i64 988, !21, i64 992, !7, i64 1008, !6, i64 1048, !6, i64 1056, !6, i64 1064, !23, i64 1072, !17, i64 1080, !17, i64 1088, !17, i64 1096, !17, i64 1104, !17, i64 1112, !17, i64 1120, !23, i64 1128, !17, i64 1136, !7, i64 1144, !28, i64 9328, !7, i64 9360}
!20 = !{!"", !21, i64 0, !23, i64 16, !23, i64 20, !17, i64 24, !17, i64 32, !24, i64 40}
!21 = !{!"list_head", !22, i64 0}
!22 = !{!"list_node", !17, i64 0, !17, i64 8}
!23 = !{!"int", !7, i64 0}
!24 = !{!"", !7, i64 0, !17, i64 40, !23, i64 48, !25, i64 52, !23, i64 56, !7, i64 64, !7, i64 112, !25, i64 160}
!25 = !{!"_Bool", !7, i64 0}
!26 = !{!"long long", !7, i64 0}
!27 = !{!"", !7, i64 0}
!28 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!29 = !{!30, !17, i64 16}
!30 = !{!"rb_execution_context_struct", !17, i64 0, !6, i64 8, !17, i64 16, !17, i64 24, !17, i64 32, !23, i64 40, !23, i64 44, !17, i64 48, !17, i64 56, !17, i64 64, !6, i64 72, !6, i64 80, !17, i64 88, !6, i64 96, !17, i64 104, !17, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !31, i64 152}
!31 = !{!"", !17, i64 0, !17, i64 8, !6, i64 16, !7, i64 24}
!32 = !{!33, !17, i64 16}
!33 = !{!"rb_control_frame_struct", !17, i64 0, !17, i64 8, !17, i64 16, !6, i64 24, !17, i64 32, !17, i64 40, !17, i64 48}
!34 = !{!33, !17, i64 32}
!35 = !DILocation(line: 4, column: 14, scope: !11)
!36 = !{!37, !6, i64 0}
!37 = !{!"RBasic", !6, i64 0, !6, i64 8}
!38 = !DILocation(line: 4, column: 5, scope: !11)
!39 = !{!40}
!40 = distinct !{!40, !41, !"sorbet_T_unsafe: argument 0"}
!41 = distinct !{!41, !"sorbet_T_unsafe"}
!42 = !{!30, !23, i64 40}
!43 = !{!30, !23, i64 44}
!44 = !{!"branch_weights", i32 2000, i32 1}
!45 = !{!30, !17, i64 56}
!46 = !{!47}
!47 = distinct !{!47, !48, !"sorbet_buildArrayIntrinsic: argument 0"}
!48 = distinct !{!48, !"sorbet_buildArrayIntrinsic"}
