; ModuleID = 'payload'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

%struct.rb_vm_struct = type { i64, %struct.anon.2, i8*, i64, %union.pthread_mutex_t, %struct.list_head, %struct.list_head, %struct.list_head, i32, i8, i64, [5 x i64], i64, i64, i64, i64, i64, i64, i64, %struct.st_table*, %struct.st_table*, %struct.anon.5, %struct.st_table*, %struct.rb_postponed_job_struct*, i32, i32, %struct.list_head, %union.pthread_mutex_t, i64, i64, i64, i32, %struct.st_table*, %struct.rb_objspace*, %struct.rb_at_exit_list*, i64*, %struct.st_table*, %struct.rb_builtin_function*, i32, %struct.rb_id_table*, [1023 x %struct.rb_callcache*], %struct.anon.9, [29 x i16] }
%struct.anon.2 = type { %struct.list_head, i32, i32, %struct.rb_ractor_struct*, %struct.rb_thread_struct*, %struct.anon.3 }
%struct.rb_ractor_struct = type opaque
%struct.rb_thread_struct = type { %struct.list_node, i64, %struct.rb_ractor_struct*, %struct.rb_vm_struct*, %struct.rb_execution_context_struct*, i64, %struct.rb_calling_info*, i64, i64, i64, i8, i8, i32, %struct.native_thread_data_struct, i8*, i64, i64, i64, i64, %union.pthread_mutex_t, %struct.rb_unblock_callback, i64, %struct.rb_mutex_struct*, %struct.rb_waiting_list*, %union.anon.12, i32, i64, %struct.rb_fiber_struct*, [5 x i8*], i64, i32, i64, %struct.rb_ext_config, i8* }
%struct.list_node = type { %struct.list_node*, %struct.list_node* }
%struct.rb_execution_context_struct = type { i64*, i64, %struct.rb_control_frame_struct*, %struct.rb_vm_tag*, %struct.rb_vm_protect_tag*, i32, i32, %struct.rb_fiber_struct*, %struct.rb_thread_struct*, %struct.rb_id_table*, i64, i64, i64*, i64, %struct.rb_ensure_list*, %struct.rb_trace_arg_struct*, i64, i64, i8, i8, i64, %struct.anon.7 }
%struct.rb_control_frame_struct = type { i64*, i64*, %struct.rb_iseq_struct*, i64, i64*, i8*, i64* }
%struct.rb_iseq_struct = type { i64, i64, %struct.rb_iseq_constant_body*, %union.anon.16 }
%struct.rb_iseq_constant_body = type { i32, i32, i64*, %struct.anon, %struct.rb_iseq_location_struct, %struct.iseq_insn_info, i64*, %struct.iseq_catch_table*, %struct.rb_iseq_struct*, %struct.rb_iseq_struct*, %union.iseq_inline_storage_entry*, %struct.rb_call_data*, %struct.anon.15, i32, i32, i32, i32, i8, i8, %struct.rb_id_table* }
%struct.anon = type { %struct.anon.0, i32, i32, i32, i32, i32, i32, i32, i64*, %struct.rb_iseq_param_keyword* }
%struct.anon.0 = type { i16, [2 x i8] }
%struct.rb_iseq_param_keyword = type { i32, i32, i32, i32, i64*, i64* }
%struct.rb_iseq_location_struct = type { i64, i64, i64, i64, i32, %struct.rb_code_location_struct }
%struct.rb_code_location_struct = type { %struct.rb_code_position_struct, %struct.rb_code_position_struct }
%struct.rb_code_position_struct = type { i32, i32 }
%struct.iseq_insn_info = type { %struct.iseq_insn_info_entry*, i32*, i32, %struct.succ_index_table* }
%struct.iseq_insn_info_entry = type opaque
%struct.succ_index_table = type opaque
%struct.iseq_catch_table = type opaque
%union.iseq_inline_storage_entry = type { %struct.anon.1 }
%struct.anon.1 = type { %struct.rb_thread_struct*, i64 }
%struct.rb_call_data = type { %struct.rb_callinfo*, %struct.rb_callcache* }
%struct.rb_callinfo = type { i64, %struct.rb_callinfo_kwarg*, i64, i64, i64 }
%struct.rb_callinfo_kwarg = type { i32, [0 x i64] }
%struct.rb_callcache = type { i64, i64, %struct.rb_callable_method_entry_struct*, i64 (%struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, %struct.rb_calling_info*)*, %union.__atomic_wide_counter }
%struct.rb_callable_method_entry_struct = type { i64, i64, %struct.rb_method_definition_struct*, i64, i64 }
%struct.rb_method_definition_struct = type { i64, %union.anon, i64, i64 }
%union.anon = type { %struct.rb_method_cfunc_struct }
%struct.rb_method_cfunc_struct = type { i64 (...)*, i64 (i64, i32, i64*, i64 (...)*)*, i32 }
%union.__atomic_wide_counter = type { i64 }
%struct.anon.15 = type { i64, i64, i64, i64* }
%union.anon.16 = type { %struct.anon.17 }
%struct.anon.17 = type { i64, i32 }
%struct.rb_vm_tag = type { i64, i64, [5 x i8*], %struct.rb_vm_tag*, i32, i32 }
%struct.rb_vm_protect_tag = type { %struct.rb_vm_protect_tag* }
%struct.rb_ensure_list = type { %struct.rb_ensure_list*, %struct.rb_ensure_entry }
%struct.rb_ensure_entry = type { i64, i64 (i64)*, i64 }
%struct.rb_trace_arg_struct = type { i32, %struct.rb_execution_context_struct*, %struct.rb_control_frame_struct*, i64, i64, i64, i64, i64, i32, i32, i64 }
%struct.anon.7 = type { i64*, i64*, i64, [1 x %struct.__jmp_buf_tag] }
%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }
%struct.rb_calling_info = type { %struct.rb_callinfo*, %struct.rb_callcache*, i64, i64, i32, i32 }
%struct.native_thread_data_struct = type { %struct.list_head, %union.anon.11 }
%union.anon.11 = type { %union.pthread_cond_t }
%union.pthread_cond_t = type { %struct.__pthread_cond_s }
%struct.__pthread_cond_s = type { %union.__atomic_wide_counter, %union.__atomic_wide_counter, [2 x i32], [2 x i32], i32, i32, [2 x i32] }
%struct.rb_unblock_callback = type { void (i8*)*, i8* }
%struct.rb_mutex_struct = type opaque
%struct.rb_waiting_list = type { %struct.rb_waiting_list*, %struct.rb_thread_struct*, %struct.rb_fiber_struct* }
%union.anon.12 = type { %struct.anon.13 }
%struct.anon.13 = type { i64, i64, i32 }
%struct.rb_fiber_struct = type opaque
%struct.rb_ext_config = type { i8 }
%struct.anon.3 = type { %union.pthread_mutex_t, %struct.rb_ractor_struct*, i32, i8, i32, %union.pthread_cond_t, %union.pthread_cond_t, i8 }
%struct.anon.5 = type { [65 x i64] }
%struct.rb_postponed_job_struct = type opaque
%struct.list_head = type { %struct.list_node }
%union.pthread_mutex_t = type { %struct.__pthread_mutex_s }
%struct.__pthread_mutex_s = type { i32, i32, i32, i32, i32, i16, i16, %struct.__pthread_internal_list }
%struct.__pthread_internal_list = type { %struct.__pthread_internal_list*, %struct.__pthread_internal_list* }
%struct.rb_objspace = type opaque
%struct.rb_at_exit_list = type { void (%struct.rb_vm_struct*)*, %struct.rb_at_exit_list* }
%struct.st_table = type { i8, i8, i8, i32, %struct.st_hash_type*, i64, i64*, i64, i64, %struct.st_table_entry* }
%struct.st_hash_type = type { i32 (i64, i64)*, i64 (i64)* }
%struct.st_table_entry = type opaque
%struct.rb_builtin_function = type opaque
%struct.rb_id_table = type opaque
%struct.anon.9 = type { i64, i64, i64, i64 }
%struct.SorbetLineNumberInfo = type { i32, %struct.iseq_insn_info_entry*, i64* }
%struct.FunctionInlineCache = type { %struct.rb_call_data }
%struct.RBasic = type { i64, i64 }

@rb_eRuntimeError = external local_unnamed_addr global i64, align 8
@.str.6 = private unnamed_addr constant [95 x i8] c"sorbet_getBuildSCMRevision: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@.str.7 = private unnamed_addr constant [93 x i8] c"sorbet_getIsReleaseBuild: Shared objects compiled by sorbet_llvm must be run by sorbet_ruby.\00", align 1
@ruby_current_vm_ptr = external local_unnamed_addr global %struct.rb_vm_struct*, align 8
@ruby_current_ec = external thread_local local_unnamed_addr global %struct.rb_execution_context_struct*, align 8
@"stackFramePrecomputed_func_<root>.13<static-init>" = internal unnamed_addr global %struct.rb_iseq_struct* null, align 8
@iseqEncodedArray = internal global [13 x i64] zeroinitializer
@fileLineNumberInfo = internal global %struct.SorbetLineNumberInfo zeroinitializer
@ic_puts = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.6 = internal global %struct.FunctionInlineCache zeroinitializer
@ic_puts.10 = internal global %struct.FunctionInlineCache zeroinitializer
@sorbet_moduleStringTable = internal unnamed_addr constant [100 x i8] c"<top (required)>\00test/testdata/compiler/splat_assign.rb\00<build-array>\00<expand-splat>\00[]\00puts\00master\00", align 1
@sorbet_moduleIDTable = internal unnamed_addr global [5 x i64] zeroinitializer, align 8
@sorbet_moduleIDDescriptors = internal unnamed_addr constant [5 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 56, i32 13 }, %struct.rb_code_position_struct { i32 70, i32 14 }, %struct.rb_code_position_struct { i32 85, i32 2 }, %struct.rb_code_position_struct { i32 88, i32 4 }], align 8
@sorbet_moduleRubyStringTable = internal unnamed_addr global [2 x i64] zeroinitializer, align 8
@sorbet_moduleRubyStringDescriptors = internal unnamed_addr constant [2 x %struct.rb_code_position_struct] [%struct.rb_code_position_struct { i32 0, i32 16 }, %struct.rb_code_position_struct { i32 17, i32 38 }], align 8

declare %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef, i64 noundef, i64 noundef, i64 noundef, %struct.rb_iseq_struct* noundef, i32 noundef, i32 noundef, %struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef, i32 noundef) local_unnamed_addr #0

declare void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef, i64* noundef, i32 noundef) local_unnamed_addr #0

declare i64 @sorbet_readRealpath() local_unnamed_addr #0

declare void @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef, i64 noundef, i32 noundef, i32 noundef, i32 noundef, ...) local_unnamed_addr #0

declare i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* noundef, i64 noundef) local_unnamed_addr #0

declare void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef, %struct.rb_control_frame_struct* noundef, %struct.rb_iseq_struct* noundef) local_unnamed_addr #0

declare i64 @sorbet_vm_expandSplatIntrinsic(i64 noundef, i64 noundef, i64 noundef) local_unnamed_addr #0

declare void @sorbet_vm_intern_ids(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

declare void @sorbet_vm_init_string_table(i64* noundef, %struct.rb_code_position_struct* noundef, i32 noundef, i8* noundef) local_unnamed_addr #0

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #1

declare i64 @rb_ary_new_from_values(i64 noundef, i64* noundef) local_unnamed_addr #0

; Function Attrs: noreturn
declare void @rb_raise(i64 noundef, i8* noundef, ...) local_unnamed_addr #2

declare i64 @rb_ary_entry(i64 noundef, i64 noundef) local_unnamed_addr #0

; Function Attrs: inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.experimental.noalias.scope.decl(metadata) #1

declare i64 @rb_ary_new() local_unnamed_addr #0

declare i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef, i32 noundef) local_unnamed_addr #0

; Function Attrs: nounwind ssp uwtable
define weak i32 @sorbet_getIsReleaseBuild() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([93 x i8], [93 x i8]* @.str.7, i32 0, i32 0)) #5
  unreachable
}

; Function Attrs: nounwind ssp uwtable
define weak i8* @sorbet_getBuildSCMRevision() local_unnamed_addr #3 {
  %1 = load i64, i64* @rb_eRuntimeError, align 8, !tbaa !5
  tail call void (i64, i8*, ...) @rb_raise(i64 noundef %1, i8* noundef getelementptr inbounds ([95 x i8], [95 x i8]* @.str.6, i32 0, i32 0)) #5
  unreachable
}

define void @Init_splat_assign() local_unnamed_addr {
entry:
  %callArgs.i = alloca [8 x i64], align 8
  %locals.i.i = alloca i64, i32 0, align 8
  %realpath = tail call i64 @sorbet_readRealpath()
  tail call void @sorbet_vm_intern_ids(i64* noundef getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([5 x %struct.rb_code_position_struct], [5 x %struct.rb_code_position_struct]* @sorbet_moduleIDDescriptors, i32 0, i32 0), i32 noundef 5, i8* noundef getelementptr inbounds ([100 x i8], [100 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_vm_init_string_table(i64* noundef getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), %struct.rb_code_position_struct* noundef getelementptr inbounds ([2 x %struct.rb_code_position_struct], [2 x %struct.rb_code_position_struct]* @sorbet_moduleRubyStringDescriptors, i32 0, i32 0), i32 noundef 2, i8* noundef getelementptr inbounds ([100 x i8], [100 x i8]* @sorbet_moduleStringTable, i32 0, i32 0))
  tail call void @sorbet_initLineNumberInfo(%struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i32 0, i32 0), i32 noundef 13)
  %"rubyId_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i32 0, i32 0), align 8, !invariant.load !9
  %"rubyStr_<top (required)>.i.i" = load i64, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i32 0, i32 0), align 8, !invariant.load !9
  %"rubyStr_test/testdata/compiler/splat_assign.rb.i.i" = load i64, i64* getelementptr inbounds ([2 x i64], [2 x i64]* @sorbet_moduleRubyStringTable, i64 0, i64 1), align 8, !invariant.load !9
  %0 = call %struct.rb_iseq_struct* @sorbet_allocateRubyStackFrame(i64 noundef %"rubyStr_<top (required)>.i.i", i64 noundef %"rubyId_<top (required)>.i.i", i64 noundef %"rubyStr_test/testdata/compiler/splat_assign.rb.i.i", i64 noundef %realpath, %struct.rb_iseq_struct* noundef null, i32 noundef 0, i32 noundef 5, %struct.SorbetLineNumberInfo* noundef @fileLineNumberInfo, i64* noundef nonnull %locals.i.i, i32 noundef 0, i32 noundef 8)
  store %struct.rb_iseq_struct* %0, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %rubyId_puts.i = load i64, i64* getelementptr inbounds ([5 x i64], [5 x i64]* @sorbet_moduleIDTable, i64 0, i64 4), align 8, !dbg !10, !invariant.load !9
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !10
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.6, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !15
  call void (%struct.FunctionInlineCache*, i64, i32, i32, i32, ...) @sorbet_setupFunctionInlineCache(%struct.FunctionInlineCache* noundef @ic_puts.10, i64 noundef %rubyId_puts.i, i32 noundef 20, i32 noundef 1, i32 noundef 0), !dbg !16
  %1 = load %struct.rb_vm_struct*, %struct.rb_vm_struct** @ruby_current_vm_ptr, align 8, !tbaa !17
  %2 = getelementptr inbounds %struct.rb_vm_struct, %struct.rb_vm_struct* %1, i64 0, i32 12
  %3 = load i64, i64* %2, align 8, !tbaa !19
  %4 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !tbaa !17
  %5 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %4, i64 0, i32 2
  %6 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %5, align 8, !tbaa !30
  %7 = bitcast [8 x i64]* %callArgs.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 64, i8* nonnull %7)
  %stackFrame.i = load %struct.rb_iseq_struct*, %struct.rb_iseq_struct** @"stackFramePrecomputed_func_<root>.13<static-init>", align 8
  %8 = load %struct.rb_control_frame_struct*, %struct.rb_control_frame_struct** %5, align 8, !tbaa !30
  %9 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %8, i64 0, i32 2
  store %struct.rb_iseq_struct* %stackFrame.i, %struct.rb_iseq_struct** %9, align 8, !tbaa !33
  %10 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %8, i64 0, i32 4
  %11 = load i64*, i64** %10, align 8, !tbaa !35
  %12 = load i64, i64* %11, align 8, !tbaa !5
  %13 = and i64 %12, -33
  store i64 %13, i64* %11, align 8, !tbaa !5
  call void @sorbet_setMethodStackFrame(%struct.rb_execution_context_struct* noundef %4, %struct.rb_control_frame_struct* noundef %8, %struct.rb_iseq_struct* noundef %stackFrame.i) #6
  %14 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %6, i64 0, i32 0
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 5), i64** %14, align 8, !tbaa !17
  call void @llvm.assume(i1 noundef true), !dbg !36
  call void @llvm.assume(i1 noundef true), !dbg !37
  call void @llvm.assume(i1 noundef true), !dbg !38
  call void @llvm.assume(i1 noundef true), !dbg !39
  call void @llvm.assume(i1 noundef true), !dbg !40
  call void @llvm.assume(i1 noundef true), !dbg !41
  call void @llvm.assume(i1 noundef true), !dbg !42
  %callArgs0Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 0, !dbg !43
  %callArgs1Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 1, !dbg !43
  %callArgs2Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 2, !dbg !43
  %15 = bitcast i64* %callArgs0Addr.i to <4 x i64>*, !dbg !43
  store <4 x i64> <i64 3, i64 5, i64 7, i64 9>, <4 x i64>* %15, align 8, !dbg !43
  %callArgs4Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 4, !dbg !43
  %16 = bitcast i64* %callArgs4Addr.i to <2 x i64>*, !dbg !43
  store <2 x i64> <i64 11, i64 13>, <2 x i64>* %16, align 8, !dbg !43
  %callArgs6Addr.i = getelementptr [8 x i64], [8 x i64]* %callArgs.i, i64 0, i64 6, !dbg !43
  store i64 15, i64* %callArgs6Addr.i, align 8, !dbg !43
  call void @llvm.experimental.noalias.scope.decl(metadata !44), !dbg !43
  %17 = call i64 @rb_ary_new_from_values(i64 noundef 7, i64* noundef nonnull align 8 %callArgs0Addr.i) #6, !dbg !43
  %18 = and i64 %17, 7, !dbg !43
  %19 = icmp ne i64 %18, 0, !dbg !43
  %20 = and i64 %17, -9, !dbg !43
  %21 = icmp eq i64 %20, 0, !dbg !43
  %22 = or i1 %19, %21, !dbg !43
  br i1 %22, label %sorbet_isa_Array.exit12, label %23, !dbg !43

23:                                               ; preds = %entry
  %24 = inttoptr i64 %17 to %struct.RBasic*, !dbg !43
  %25 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %24, i64 0, i32 0, !dbg !43
  %26 = load i64, i64* %25, align 8, !dbg !43, !tbaa !47
  %27 = and i64 %26, 31, !dbg !43
  %28 = icmp eq i64 %27, 7, !dbg !43
  br label %sorbet_isa_Array.exit12, !dbg !43

sorbet_isa_Array.exit12:                          ; preds = %entry, %23
  %29 = phi i1 [ false, %entry ], [ %28, %23 ], !dbg !43
  call void @llvm.assume(i1 noundef %29), !dbg !43
  store i64 %17, i64* %callArgs0Addr.i, align 8, !dbg !49
  %30 = bitcast i64* %callArgs1Addr.i to <2 x i64>*, !dbg !49
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %30, align 8, !dbg !49
  call void @llvm.experimental.noalias.scope.decl(metadata !50), !dbg !49
  %31 = getelementptr inbounds i64, i64* %callArgs0Addr.i, i64 1, !dbg !49
  %32 = getelementptr inbounds i64, i64* %callArgs0Addr.i, i64 2, !dbg !49
  %33 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 noundef %17, i64 noundef 3, i64 noundef 5) #6, !dbg !49, !noalias !50
  %34 = and i64 %33, 7, !dbg !49
  %35 = icmp ne i64 %34, 0, !dbg !49
  %36 = and i64 %33, -9, !dbg !49
  %37 = icmp eq i64 %36, 0, !dbg !49
  %38 = or i1 %35, %37, !dbg !49
  br i1 %38, label %sorbet_isa_Array.exit11, label %39, !dbg !49

39:                                               ; preds = %sorbet_isa_Array.exit12
  %40 = inttoptr i64 %33 to %struct.RBasic*, !dbg !49
  %41 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %40, i64 0, i32 0, !dbg !49
  %42 = load i64, i64* %41, align 8, !dbg !49, !tbaa !47
  %43 = and i64 %42, 31, !dbg !49
  %44 = icmp eq i64 %43, 7, !dbg !49
  br label %sorbet_isa_Array.exit11, !dbg !49

sorbet_isa_Array.exit11:                          ; preds = %sorbet_isa_Array.exit12, %39
  %45 = phi i1 [ false, %sorbet_isa_Array.exit12 ], [ %44, %39 ], !dbg !49
  call void @llvm.assume(i1 noundef %45), !dbg !49
  call void @llvm.assume(i1 noundef true), !dbg !49
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !49
  call void @llvm.experimental.noalias.scope.decl(metadata !53), !dbg !49
  %46 = call i64 @rb_ary_entry(i64 noundef %33, i64 noundef 0) #6, !dbg !49, !noalias !53
  %47 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !49, !tbaa !17
  %48 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %47, i64 0, i32 5, !dbg !49
  %49 = load i32, i32* %48, align 8, !dbg !49, !tbaa !56
  %50 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %47, i64 0, i32 6, !dbg !49
  %51 = load i32, i32* %50, align 4, !dbg !49, !tbaa !57
  %52 = xor i32 %51, -1, !dbg !49
  %53 = and i32 %52, %49, !dbg !49
  %54 = icmp eq i32 %53, 0, !dbg !49
  br i1 %54, label %sorbet_rb_array_square_br.exit372.i, label %55, !dbg !49, !prof !58

55:                                               ; preds = %sorbet_isa_Array.exit11
  %56 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %47, i64 0, i32 8, !dbg !49
  %57 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %56, align 8, !dbg !49, !tbaa !59
  %58 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %57, i32 noundef 0) #6, !dbg !49
  br label %sorbet_rb_array_square_br.exit372.i, !dbg !49

sorbet_rb_array_square_br.exit372.i:              ; preds = %55, %sorbet_isa_Array.exit11
  call void @llvm.assume(i1 noundef true), !dbg !49
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !60
  call void @llvm.experimental.noalias.scope.decl(metadata !61), !dbg !60
  %59 = call i64 @rb_ary_entry(i64 noundef %33, i64 noundef -2) #6, !dbg !60, !noalias !61
  %60 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !60, !tbaa !17
  %61 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 5, !dbg !60
  %62 = load i32, i32* %61, align 8, !dbg !60, !tbaa !56
  %63 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 6, !dbg !60
  %64 = load i32, i32* %63, align 4, !dbg !60, !tbaa !57
  %65 = xor i32 %64, -1, !dbg !60
  %66 = and i32 %65, %62, !dbg !60
  %67 = icmp eq i32 %66, 0, !dbg !60
  br i1 %67, label %sorbet_rb_array_square_br.exit374.i, label %68, !dbg !60, !prof !58

68:                                               ; preds = %sorbet_rb_array_square_br.exit372.i
  %69 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %60, i64 0, i32 8, !dbg !60
  %70 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %69, align 8, !dbg !60, !tbaa !59
  %71 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %70, i32 noundef 0) #6, !dbg !60
  br label %sorbet_rb_array_square_br.exit374.i, !dbg !60

sorbet_rb_array_square_br.exit374.i:              ; preds = %68, %sorbet_rb_array_square_br.exit372.i
  call void @llvm.assume(i1 noundef true), !dbg !49
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !64
  call void @llvm.experimental.noalias.scope.decl(metadata !65), !dbg !64
  %72 = call i64 @rb_ary_entry(i64 noundef %33, i64 noundef -1) #6, !dbg !64, !noalias !65
  %73 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !64, !tbaa !17
  %74 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %73, i64 0, i32 5, !dbg !64
  %75 = load i32, i32* %74, align 8, !dbg !64, !tbaa !56
  %76 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %73, i64 0, i32 6, !dbg !64
  %77 = load i32, i32* %76, align 4, !dbg !64, !tbaa !57
  %78 = xor i32 %77, -1, !dbg !64
  %79 = and i32 %78, %75, !dbg !64
  %80 = icmp eq i32 %79, 0, !dbg !64
  br i1 %80, label %sorbet_rb_array_square_br.exit377.i, label %81, !dbg !64, !prof !58

81:                                               ; preds = %sorbet_rb_array_square_br.exit374.i
  %82 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %73, i64 0, i32 8, !dbg !64
  %83 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %82, align 8, !dbg !64, !tbaa !59
  %84 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %83, i32 noundef 0) #6, !dbg !64
  br label %sorbet_rb_array_square_br.exit377.i, !dbg !64

sorbet_rb_array_square_br.exit377.i:              ; preds = %81, %sorbet_rb_array_square_br.exit374.i
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 6), i64** %14, align 8, !dbg !68, !tbaa !17
  store i64 %46, i64* %callArgs0Addr.i, align 8, !dbg !69
  store i64 %59, i64* %callArgs1Addr.i, align 8, !dbg !69
  store i64 %72, i64* %callArgs2Addr.i, align 8, !dbg !69
  call void @llvm.experimental.noalias.scope.decl(metadata !70), !dbg !69
  %85 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %callArgs0Addr.i) #6, !dbg !69
  %86 = and i64 %85, 7, !dbg !69
  %87 = icmp ne i64 %86, 0, !dbg !69
  %88 = and i64 %85, -9, !dbg !69
  %89 = icmp eq i64 %88, 0, !dbg !69
  %90 = or i1 %87, %89, !dbg !69
  br i1 %90, label %sorbet_isa_Array.exit10, label %91, !dbg !69

91:                                               ; preds = %sorbet_rb_array_square_br.exit377.i
  %92 = inttoptr i64 %85 to %struct.RBasic*, !dbg !69
  %93 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %92, i64 0, i32 0, !dbg !69
  %94 = load i64, i64* %93, align 8, !dbg !69, !tbaa !47
  %95 = and i64 %94, 31, !dbg !69
  %96 = icmp eq i64 %95, 7, !dbg !69
  br label %sorbet_isa_Array.exit10, !dbg !69

sorbet_isa_Array.exit10:                          ; preds = %sorbet_rb_array_square_br.exit377.i, %91
  %97 = phi i1 [ false, %sorbet_rb_array_square_br.exit377.i ], [ %96, %91 ], !dbg !69
  call void @llvm.assume(i1 noundef %97), !dbg !69
  %98 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %6, i64 0, i32 1, !dbg !10
  %99 = load i64*, i64** %98, align 8, !dbg !10
  store i64 %3, i64* %99, align 8, !dbg !10, !tbaa !5
  %100 = getelementptr inbounds i64, i64* %99, i64 1, !dbg !10
  store i64 %85, i64* %100, align 8, !dbg !10, !tbaa !5
  %101 = getelementptr inbounds i64, i64* %100, i64 1, !dbg !10
  store i64* %101, i64** %98, align 8, !dbg !10
  %send = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts, i64 0), !dbg !10
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 8), i64** %14, align 8, !dbg !10, !tbaa !17
  %102 = bitcast i64* %callArgs0Addr.i to <2 x i64>*, !dbg !73
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %102, align 8, !dbg !73
  call void @llvm.experimental.noalias.scope.decl(metadata !74), !dbg !73
  %103 = call i64 @rb_ary_new_from_values(i64 noundef 2, i64* noundef nonnull %callArgs0Addr.i) #6, !dbg !73
  %104 = and i64 %103, 7, !dbg !73
  %105 = icmp ne i64 %104, 0, !dbg !73
  %106 = and i64 %103, -9, !dbg !73
  %107 = icmp eq i64 %106, 0, !dbg !73
  %108 = or i1 %105, %107, !dbg !73
  br i1 %108, label %sorbet_isa_Array.exit9, label %109, !dbg !73

109:                                              ; preds = %sorbet_isa_Array.exit10
  %110 = inttoptr i64 %103 to %struct.RBasic*, !dbg !73
  %111 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %110, i64 0, i32 0, !dbg !73
  %112 = load i64, i64* %111, align 8, !dbg !73, !tbaa !47
  %113 = and i64 %112, 31, !dbg !73
  %114 = icmp eq i64 %113, 7, !dbg !73
  br label %sorbet_isa_Array.exit9, !dbg !73

sorbet_isa_Array.exit9:                           ; preds = %sorbet_isa_Array.exit10, %109
  %115 = phi i1 [ false, %sorbet_isa_Array.exit10 ], [ %114, %109 ], !dbg !73
  call void @llvm.assume(i1 noundef %115), !dbg !73
  store i64 %103, i64* %callArgs0Addr.i, align 8, !dbg !77
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %30, align 8, !dbg !77
  call void @llvm.experimental.noalias.scope.decl(metadata !78), !dbg !77
  %116 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 noundef %103, i64 noundef 3, i64 noundef 5) #6, !dbg !77, !noalias !78
  %117 = and i64 %116, 7, !dbg !77
  %118 = icmp ne i64 %117, 0, !dbg !77
  %119 = and i64 %116, -9, !dbg !77
  %120 = icmp eq i64 %119, 0, !dbg !77
  %121 = or i1 %118, %120, !dbg !77
  br i1 %121, label %sorbet_isa_Array.exit8, label %122, !dbg !77

122:                                              ; preds = %sorbet_isa_Array.exit9
  %123 = inttoptr i64 %116 to %struct.RBasic*, !dbg !77
  %124 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %123, i64 0, i32 0, !dbg !77
  %125 = load i64, i64* %124, align 8, !dbg !77, !tbaa !47
  %126 = and i64 %125, 31, !dbg !77
  %127 = icmp eq i64 %126, 7, !dbg !77
  br label %sorbet_isa_Array.exit8, !dbg !77

sorbet_isa_Array.exit8:                           ; preds = %sorbet_isa_Array.exit9, %122
  %128 = phi i1 [ false, %sorbet_isa_Array.exit9 ], [ %127, %122 ], !dbg !77
  call void @llvm.assume(i1 noundef %128), !dbg !77
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !77
  call void @llvm.experimental.noalias.scope.decl(metadata !81), !dbg !77
  %129 = call i64 @rb_ary_entry(i64 noundef %116, i64 noundef 0) #6, !dbg !77, !noalias !81
  %130 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !77, !tbaa !17
  %131 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %130, i64 0, i32 5, !dbg !77
  %132 = load i32, i32* %131, align 8, !dbg !77, !tbaa !56
  %133 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %130, i64 0, i32 6, !dbg !77
  %134 = load i32, i32* %133, align 4, !dbg !77, !tbaa !57
  %135 = xor i32 %134, -1, !dbg !77
  %136 = and i32 %135, %132, !dbg !77
  %137 = icmp eq i32 %136, 0, !dbg !77
  br i1 %137, label %sorbet_rb_array_square_br.exit379.i, label %138, !dbg !77, !prof !58

138:                                              ; preds = %sorbet_isa_Array.exit8
  %139 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %130, i64 0, i32 8, !dbg !77
  %140 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %139, align 8, !dbg !77, !tbaa !59
  %141 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %140, i32 noundef 0) #6, !dbg !77
  br label %sorbet_rb_array_square_br.exit379.i, !dbg !77

sorbet_rb_array_square_br.exit379.i:              ; preds = %138, %sorbet_isa_Array.exit8
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !84
  call void @llvm.experimental.noalias.scope.decl(metadata !85), !dbg !84
  %142 = call i64 @rb_ary_entry(i64 noundef %116, i64 noundef -2) #6, !dbg !84, !noalias !85
  %143 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !84, !tbaa !17
  %144 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %143, i64 0, i32 5, !dbg !84
  %145 = load i32, i32* %144, align 8, !dbg !84, !tbaa !56
  %146 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %143, i64 0, i32 6, !dbg !84
  %147 = load i32, i32* %146, align 4, !dbg !84, !tbaa !57
  %148 = xor i32 %147, -1, !dbg !84
  %149 = and i32 %148, %145, !dbg !84
  %150 = icmp eq i32 %149, 0, !dbg !84
  br i1 %150, label %sorbet_rb_array_square_br.exit381.i, label %151, !dbg !84, !prof !58

151:                                              ; preds = %sorbet_rb_array_square_br.exit379.i
  %152 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %143, i64 0, i32 8, !dbg !84
  %153 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %152, align 8, !dbg !84, !tbaa !59
  %154 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %153, i32 noundef 0) #6, !dbg !84
  br label %sorbet_rb_array_square_br.exit381.i, !dbg !84

sorbet_rb_array_square_br.exit381.i:              ; preds = %151, %sorbet_rb_array_square_br.exit379.i
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !88
  call void @llvm.experimental.noalias.scope.decl(metadata !89), !dbg !88
  %155 = call i64 @rb_ary_entry(i64 noundef %116, i64 noundef -1) #6, !dbg !88, !noalias !89
  %156 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !88, !tbaa !17
  %157 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %156, i64 0, i32 5, !dbg !88
  %158 = load i32, i32* %157, align 8, !dbg !88, !tbaa !56
  %159 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %156, i64 0, i32 6, !dbg !88
  %160 = load i32, i32* %159, align 4, !dbg !88, !tbaa !57
  %161 = xor i32 %160, -1, !dbg !88
  %162 = and i32 %161, %158, !dbg !88
  %163 = icmp eq i32 %162, 0, !dbg !88
  br i1 %163, label %sorbet_rb_array_square_br.exit369.i, label %164, !dbg !88, !prof !58

164:                                              ; preds = %sorbet_rb_array_square_br.exit381.i
  %165 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %156, i64 0, i32 8, !dbg !88
  %166 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %165, align 8, !dbg !88, !tbaa !59
  %167 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %166, i32 noundef 0) #6, !dbg !88
  br label %sorbet_rb_array_square_br.exit369.i, !dbg !88

sorbet_rb_array_square_br.exit369.i:              ; preds = %164, %sorbet_rb_array_square_br.exit381.i
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 9), i64** %14, align 8, !dbg !68, !tbaa !17
  store i64 %129, i64* %callArgs0Addr.i, align 8, !dbg !92
  store i64 %142, i64* %callArgs1Addr.i, align 8, !dbg !92
  store i64 %155, i64* %callArgs2Addr.i, align 8, !dbg !92
  call void @llvm.experimental.noalias.scope.decl(metadata !93), !dbg !92
  %168 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %callArgs0Addr.i) #6, !dbg !92
  %169 = and i64 %168, 7, !dbg !92
  %170 = icmp ne i64 %169, 0, !dbg !92
  %171 = and i64 %168, -9, !dbg !92
  %172 = icmp eq i64 %171, 0, !dbg !92
  %173 = or i1 %170, %172, !dbg !92
  br i1 %173, label %sorbet_isa_Array.exit7, label %174, !dbg !92

174:                                              ; preds = %sorbet_rb_array_square_br.exit369.i
  %175 = inttoptr i64 %168 to %struct.RBasic*, !dbg !92
  %176 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %175, i64 0, i32 0, !dbg !92
  %177 = load i64, i64* %176, align 8, !dbg !92, !tbaa !47
  %178 = and i64 %177, 31, !dbg !92
  %179 = icmp eq i64 %178, 7, !dbg !92
  br label %sorbet_isa_Array.exit7, !dbg !92

sorbet_isa_Array.exit7:                           ; preds = %sorbet_rb_array_square_br.exit369.i, %174
  %180 = phi i1 [ false, %sorbet_rb_array_square_br.exit369.i ], [ %179, %174 ], !dbg !92
  call void @llvm.assume(i1 noundef %180), !dbg !92
  %181 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %6, i64 0, i32 1, !dbg !15
  %182 = load i64*, i64** %181, align 8, !dbg !15
  store i64 %3, i64* %182, align 8, !dbg !15, !tbaa !5
  %183 = getelementptr inbounds i64, i64* %182, i64 1, !dbg !15
  store i64 %168, i64* %183, align 8, !dbg !15, !tbaa !5
  %184 = getelementptr inbounds i64, i64* %183, i64 1, !dbg !15
  store i64* %184, i64** %181, align 8, !dbg !15
  %send2 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.6, i64 0), !dbg !15
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 11), i64** %14, align 8, !dbg !68, !tbaa !17
  call void @llvm.experimental.noalias.scope.decl(metadata !96), !dbg !99
  %185 = call i64 @rb_ary_new() #6, !dbg !99, !noalias !96
  %186 = and i64 %185, 7, !dbg !99
  %187 = icmp ne i64 %186, 0, !dbg !99
  %188 = and i64 %185, -9, !dbg !99
  %189 = icmp eq i64 %188, 0, !dbg !99
  %190 = or i1 %187, %189, !dbg !99
  br i1 %190, label %sorbet_isa_Array.exit6, label %191, !dbg !99

191:                                              ; preds = %sorbet_isa_Array.exit7
  %192 = inttoptr i64 %185 to %struct.RBasic*, !dbg !99
  %193 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %192, i64 0, i32 0, !dbg !99
  %194 = load i64, i64* %193, align 8, !dbg !99, !tbaa !47
  %195 = and i64 %194, 31, !dbg !99
  %196 = icmp eq i64 %195, 7, !dbg !99
  br label %sorbet_isa_Array.exit6, !dbg !99

sorbet_isa_Array.exit6:                           ; preds = %sorbet_isa_Array.exit7, %191
  %197 = phi i1 [ false, %sorbet_isa_Array.exit7 ], [ %196, %191 ], !dbg !99
  call void @llvm.assume(i1 noundef %197), !dbg !99
  store i64 %185, i64* %callArgs0Addr.i, align 8, !dbg !100
  store <2 x i64> <i64 3, i64 5>, <2 x i64>* %30, align 8, !dbg !100
  call void @llvm.experimental.noalias.scope.decl(metadata !101), !dbg !100
  %198 = call i64 @sorbet_vm_expandSplatIntrinsic(i64 noundef %185, i64 noundef 3, i64 noundef 5) #6, !dbg !100, !noalias !101
  %199 = and i64 %198, 7, !dbg !100
  %200 = icmp ne i64 %199, 0, !dbg !100
  %201 = and i64 %198, -9, !dbg !100
  %202 = icmp eq i64 %201, 0, !dbg !100
  %203 = or i1 %200, %202, !dbg !100
  br i1 %203, label %sorbet_isa_Array.exit5, label %204, !dbg !100

204:                                              ; preds = %sorbet_isa_Array.exit6
  %205 = inttoptr i64 %198 to %struct.RBasic*, !dbg !100
  %206 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %205, i64 0, i32 0, !dbg !100
  %207 = load i64, i64* %206, align 8, !dbg !100, !tbaa !47
  %208 = and i64 %207, 31, !dbg !100
  %209 = icmp eq i64 %208, 7, !dbg !100
  br label %sorbet_isa_Array.exit5, !dbg !100

sorbet_isa_Array.exit5:                           ; preds = %sorbet_isa_Array.exit6, %204
  %210 = phi i1 [ false, %sorbet_isa_Array.exit6 ], [ %209, %204 ], !dbg !100
  call void @llvm.assume(i1 noundef %210), !dbg !100
  store i64 1, i64* %callArgs0Addr.i, align 8, !dbg !100
  call void @llvm.experimental.noalias.scope.decl(metadata !104), !dbg !100
  %211 = call i64 @rb_ary_entry(i64 noundef %198, i64 noundef 0) #6, !dbg !100, !noalias !104
  %212 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !100, !tbaa !17
  %213 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %212, i64 0, i32 5, !dbg !100
  %214 = load i32, i32* %213, align 8, !dbg !100, !tbaa !56
  %215 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %212, i64 0, i32 6, !dbg !100
  %216 = load i32, i32* %215, align 4, !dbg !100, !tbaa !57
  %217 = xor i32 %216, -1, !dbg !100
  %218 = and i32 %217, %214, !dbg !100
  %219 = icmp eq i32 %218, 0, !dbg !100
  br i1 %219, label %sorbet_rb_array_square_br.exit367.i, label %220, !dbg !100, !prof !58

220:                                              ; preds = %sorbet_isa_Array.exit5
  %221 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %212, i64 0, i32 8, !dbg !100
  %222 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %221, align 8, !dbg !100, !tbaa !59
  %223 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %222, i32 noundef 0) #6, !dbg !100
  br label %sorbet_rb_array_square_br.exit367.i, !dbg !100

sorbet_rb_array_square_br.exit367.i:              ; preds = %220, %sorbet_isa_Array.exit5
  store i64 -3, i64* %callArgs0Addr.i, align 8, !dbg !107
  call void @llvm.experimental.noalias.scope.decl(metadata !108), !dbg !107
  %224 = call i64 @rb_ary_entry(i64 noundef %198, i64 noundef -2) #6, !dbg !107, !noalias !108
  %225 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !107, !tbaa !17
  %226 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %225, i64 0, i32 5, !dbg !107
  %227 = load i32, i32* %226, align 8, !dbg !107, !tbaa !56
  %228 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %225, i64 0, i32 6, !dbg !107
  %229 = load i32, i32* %228, align 4, !dbg !107, !tbaa !57
  %230 = xor i32 %229, -1, !dbg !107
  %231 = and i32 %230, %227, !dbg !107
  %232 = icmp eq i32 %231, 0, !dbg !107
  br i1 %232, label %sorbet_rb_array_square_br.exit.i, label %233, !dbg !107, !prof !58

233:                                              ; preds = %sorbet_rb_array_square_br.exit367.i
  %234 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %225, i64 0, i32 8, !dbg !107
  %235 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %234, align 8, !dbg !107, !tbaa !59
  %236 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %235, i32 noundef 0) #6, !dbg !107
  br label %sorbet_rb_array_square_br.exit.i, !dbg !107

sorbet_rb_array_square_br.exit.i:                 ; preds = %233, %sorbet_rb_array_square_br.exit367.i
  store i64 -1, i64* %callArgs0Addr.i, align 8, !dbg !111
  call void @llvm.experimental.noalias.scope.decl(metadata !112), !dbg !111
  %237 = call i64 @rb_ary_entry(i64 noundef %198, i64 noundef -1) #6, !dbg !111, !noalias !112
  %238 = load %struct.rb_execution_context_struct*, %struct.rb_execution_context_struct** @ruby_current_ec, align 8, !dbg !111, !tbaa !17
  %239 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %238, i64 0, i32 5, !dbg !111
  %240 = load i32, i32* %239, align 8, !dbg !111, !tbaa !56
  %241 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %238, i64 0, i32 6, !dbg !111
  %242 = load i32, i32* %241, align 4, !dbg !111, !tbaa !57
  %243 = xor i32 %242, -1, !dbg !111
  %244 = and i32 %243, %240, !dbg !111
  %245 = icmp eq i32 %244, 0, !dbg !111
  br i1 %245, label %"func_<root>.13<static-init>.exit", label %246, !dbg !111, !prof !58

246:                                              ; preds = %sorbet_rb_array_square_br.exit.i
  %247 = getelementptr inbounds %struct.rb_execution_context_struct, %struct.rb_execution_context_struct* %238, i64 0, i32 8, !dbg !111
  %248 = load %struct.rb_thread_struct*, %struct.rb_thread_struct** %247, align 8, !dbg !111, !tbaa !59
  %249 = call i32 @rb_threadptr_execute_interrupts(%struct.rb_thread_struct* noundef %248, i32 noundef 0) #6, !dbg !111
  br label %"func_<root>.13<static-init>.exit", !dbg !111

"func_<root>.13<static-init>.exit":               ; preds = %sorbet_rb_array_square_br.exit.i, %246
  store i64* getelementptr inbounds ([13 x i64], [13 x i64]* @iseqEncodedArray, i64 0, i64 12), i64** %14, align 8, !dbg !68, !tbaa !17
  store i64 %211, i64* %callArgs0Addr.i, align 8, !dbg !115
  store i64 %224, i64* %callArgs1Addr.i, align 8, !dbg !115
  store i64 %237, i64* %callArgs2Addr.i, align 8, !dbg !115
  call void @llvm.experimental.noalias.scope.decl(metadata !116), !dbg !115
  %250 = call i64 @rb_ary_new_from_values(i64 noundef 3, i64* noundef nonnull %callArgs0Addr.i) #6, !dbg !115
  %251 = and i64 %250, 7, !dbg !115
  %252 = icmp ne i64 %251, 0, !dbg !115
  %253 = and i64 %250, -9, !dbg !115
  %254 = icmp eq i64 %253, 0, !dbg !115
  %255 = or i1 %252, %254, !dbg !115
  br i1 %255, label %sorbet_isa_Array.exit, label %256, !dbg !115

256:                                              ; preds = %"func_<root>.13<static-init>.exit"
  %257 = inttoptr i64 %250 to %struct.RBasic*, !dbg !115
  %258 = getelementptr inbounds %struct.RBasic, %struct.RBasic* %257, i64 0, i32 0, !dbg !115
  %259 = load i64, i64* %258, align 8, !dbg !115, !tbaa !47
  %260 = and i64 %259, 31, !dbg !115
  %261 = icmp eq i64 %260, 7, !dbg !115
  br label %sorbet_isa_Array.exit, !dbg !115

sorbet_isa_Array.exit:                            ; preds = %"func_<root>.13<static-init>.exit", %256
  %262 = phi i1 [ false, %"func_<root>.13<static-init>.exit" ], [ %261, %256 ], !dbg !115
  call void @llvm.assume(i1 noundef %262), !dbg !115
  %263 = getelementptr inbounds %struct.rb_control_frame_struct, %struct.rb_control_frame_struct* %6, i64 0, i32 1, !dbg !16
  %264 = load i64*, i64** %263, align 8, !dbg !16
  store i64 %3, i64* %264, align 8, !dbg !16, !tbaa !5
  %265 = getelementptr inbounds i64, i64* %264, i64 1, !dbg !16
  store i64 %250, i64* %265, align 8, !dbg !16, !tbaa !5
  %266 = getelementptr inbounds i64, i64* %265, i64 1, !dbg !16
  store i64* %266, i64** %263, align 8, !dbg !16
  %send4 = call i64 @sorbet_callFuncWithCache(%struct.FunctionInlineCache* @ic_puts.10, i64 0), !dbg !16
  call void @llvm.lifetime.end.p0i8(i64 64, i8* nonnull %7)
  ret void
}

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #4

attributes #0 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #1 = { inaccessiblememonly mustprogress nocallback nofree nosync nounwind willreturn }
attributes #2 = { noreturn "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #3 = { nounwind ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" }
attributes #4 = { argmemonly nocallback nofree nosync nounwind willreturn }
attributes #5 = { noreturn nounwind }
attributes #6 = { nounwind }

!llvm.module.flags = !{!0, !1, !2}
!llvm.dbg.cu = !{!3}

!0 = !{i32 2, !"Debug Info Version", i32 3}
!1 = !{i32 4, !"cf-protection-return", i32 1}
!2 = !{i32 4, !"cf-protection-branch", i32 1}
!3 = distinct !DICompileUnit(language: DW_LANG_C, file: !4, producer: "Sorbet LLVM", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
!4 = !DIFile(filename: "test/testdata/compiler/splat_assign.rb", directory: ".")
!5 = !{!6, !6, i64 0}
!6 = !{!"long", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{}
!10 = !DILocation(line: 6, column: 1, scope: !11)
!11 = distinct !DISubprogram(name: "<root>.<static-init>", linkageName: "func_<root>.13<static-init>", scope: null, file: !4, line: 5, type: !12, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !3, retainedNodes: !9)
!12 = !DISubroutineType(cc: DW_CC_nocall, types: !13)
!13 = !{!14}
!14 = !DIBasicType(name: "VALUE", size: 64, encoding: DW_ATE_signed)
!15 = !DILocation(line: 9, column: 1, scope: !11)
!16 = !DILocation(line: 12, column: 1, scope: !11)
!17 = !{!18, !18, i64 0}
!18 = !{!"any pointer", !7, i64 0}
!19 = !{!20, !6, i64 376}
!20 = !{!"rb_vm_struct", !6, i64 0, !21, i64 8, !18, i64 216, !27, i64 224, !7, i64 232, !22, i64 272, !22, i64 288, !22, i64 304, !24, i64 320, !24, i64 324, !24, i64 324, !24, i64 324, !24, i64 324, !6, i64 328, !7, i64 336, !6, i64 376, !6, i64 384, !6, i64 392, !6, i64 400, !6, i64 408, !6, i64 416, !6, i64 424, !18, i64 432, !18, i64 440, !28, i64 448, !18, i64 968, !18, i64 976, !24, i64 984, !24, i64 988, !22, i64 992, !7, i64 1008, !6, i64 1048, !6, i64 1056, !6, i64 1064, !24, i64 1072, !18, i64 1080, !18, i64 1088, !18, i64 1096, !18, i64 1104, !18, i64 1112, !18, i64 1120, !24, i64 1128, !18, i64 1136, !7, i64 1144, !29, i64 9328, !7, i64 9360}
!21 = !{!"", !22, i64 0, !24, i64 16, !24, i64 20, !18, i64 24, !18, i64 32, !25, i64 40}
!22 = !{!"list_head", !23, i64 0}
!23 = !{!"list_node", !18, i64 0, !18, i64 8}
!24 = !{!"int", !7, i64 0}
!25 = !{!"", !7, i64 0, !18, i64 40, !24, i64 48, !26, i64 52, !24, i64 56, !7, i64 64, !7, i64 112, !26, i64 160}
!26 = !{!"_Bool", !7, i64 0}
!27 = !{!"long long", !7, i64 0}
!28 = !{!"", !7, i64 0}
!29 = !{!"", !6, i64 0, !6, i64 8, !6, i64 16, !6, i64 24}
!30 = !{!31, !18, i64 16}
!31 = !{!"rb_execution_context_struct", !18, i64 0, !6, i64 8, !18, i64 16, !18, i64 24, !18, i64 32, !24, i64 40, !24, i64 44, !18, i64 48, !18, i64 56, !18, i64 64, !6, i64 72, !6, i64 80, !18, i64 88, !6, i64 96, !18, i64 104, !18, i64 112, !6, i64 120, !6, i64 128, !7, i64 136, !7, i64 137, !6, i64 144, !32, i64 152}
!32 = !{!"", !18, i64 0, !18, i64 8, !6, i64 16, !7, i64 24}
!33 = !{!34, !18, i64 16}
!34 = !{!"rb_control_frame_struct", !18, i64 0, !18, i64 8, !18, i64 16, !6, i64 24, !18, i64 32, !18, i64 40, !18, i64 48}
!35 = !{!34, !18, i64 32}
!36 = !DILocation(line: 5, column: 12, scope: !11)
!37 = !DILocation(line: 5, column: 14, scope: !11)
!38 = !DILocation(line: 5, column: 16, scope: !11)
!39 = !DILocation(line: 5, column: 18, scope: !11)
!40 = !DILocation(line: 5, column: 20, scope: !11)
!41 = !DILocation(line: 5, column: 22, scope: !11)
!42 = !DILocation(line: 5, column: 24, scope: !11)
!43 = !DILocation(line: 5, column: 11, scope: !11)
!44 = !{!45}
!45 = distinct !{!45, !46, !"sorbet_buildArrayIntrinsic: argument 0"}
!46 = distinct !{!46, !"sorbet_buildArrayIntrinsic"}
!47 = !{!48, !6, i64 0}
!48 = !{!"RBasic", !6, i64 0, !6, i64 8}
!49 = !DILocation(line: 5, column: 1, scope: !11)
!50 = !{!51}
!51 = distinct !{!51, !52, !"sorbet_expandSplatIntrinsic: argument 0"}
!52 = distinct !{!52, !"sorbet_expandSplatIntrinsic"}
!53 = !{!54}
!54 = distinct !{!54, !55, !"sorbet_rb_array_square_br: argument 0"}
!55 = distinct !{!55, !"sorbet_rb_array_square_br"}
!56 = !{!31, !24, i64 40}
!57 = !{!31, !24, i64 44}
!58 = !{!"branch_weights", i32 2000, i32 1}
!59 = !{!31, !18, i64 56}
!60 = !DILocation(line: 5, column: 5, scope: !11)
!61 = !{!62}
!62 = distinct !{!62, !63, !"sorbet_rb_array_square_br: argument 0"}
!63 = distinct !{!63, !"sorbet_rb_array_square_br"}
!64 = !DILocation(line: 5, column: 7, scope: !11)
!65 = !{!66}
!66 = distinct !{!66, !67, !"sorbet_rb_array_square_br: argument 0"}
!67 = distinct !{!67, !"sorbet_rb_array_square_br"}
!68 = !DILocation(line: 0, scope: !11)
!69 = !DILocation(line: 6, column: 6, scope: !11)
!70 = !{!71}
!71 = distinct !{!71, !72, !"sorbet_buildArrayIntrinsic: argument 0"}
!72 = distinct !{!72, !"sorbet_buildArrayIntrinsic"}
!73 = !DILocation(line: 8, column: 11, scope: !11)
!74 = !{!75}
!75 = distinct !{!75, !76, !"sorbet_buildArrayIntrinsic: argument 0"}
!76 = distinct !{!76, !"sorbet_buildArrayIntrinsic"}
!77 = !DILocation(line: 8, column: 1, scope: !11)
!78 = !{!79}
!79 = distinct !{!79, !80, !"sorbet_expandSplatIntrinsic: argument 0"}
!80 = distinct !{!80, !"sorbet_expandSplatIntrinsic"}
!81 = !{!82}
!82 = distinct !{!82, !83, !"sorbet_rb_array_square_br: argument 0"}
!83 = distinct !{!83, !"sorbet_rb_array_square_br"}
!84 = !DILocation(line: 8, column: 5, scope: !11)
!85 = !{!86}
!86 = distinct !{!86, !87, !"sorbet_rb_array_square_br: argument 0"}
!87 = distinct !{!87, !"sorbet_rb_array_square_br"}
!88 = !DILocation(line: 8, column: 7, scope: !11)
!89 = !{!90}
!90 = distinct !{!90, !91, !"sorbet_rb_array_square_br: argument 0"}
!91 = distinct !{!91, !"sorbet_rb_array_square_br"}
!92 = !DILocation(line: 9, column: 6, scope: !11)
!93 = !{!94}
!94 = distinct !{!94, !95, !"sorbet_buildArrayIntrinsic: argument 0"}
!95 = distinct !{!95, !"sorbet_buildArrayIntrinsic"}
!96 = !{!97}
!97 = distinct !{!97, !98, !"sorbet_buildArrayIntrinsic: argument 0"}
!98 = distinct !{!98, !"sorbet_buildArrayIntrinsic"}
!99 = !DILocation(line: 11, column: 11, scope: !11)
!100 = !DILocation(line: 11, column: 1, scope: !11)
!101 = !{!102}
!102 = distinct !{!102, !103, !"sorbet_expandSplatIntrinsic: argument 0"}
!103 = distinct !{!103, !"sorbet_expandSplatIntrinsic"}
!104 = !{!105}
!105 = distinct !{!105, !106, !"sorbet_rb_array_square_br: argument 0"}
!106 = distinct !{!106, !"sorbet_rb_array_square_br"}
!107 = !DILocation(line: 11, column: 5, scope: !11)
!108 = !{!109}
!109 = distinct !{!109, !110, !"sorbet_rb_array_square_br: argument 0"}
!110 = distinct !{!110, !"sorbet_rb_array_square_br"}
!111 = !DILocation(line: 11, column: 7, scope: !11)
!112 = !{!113}
!113 = distinct !{!113, !114, !"sorbet_rb_array_square_br: argument 0"}
!114 = distinct !{!114, !"sorbet_rb_array_square_br"}
!115 = !DILocation(line: 12, column: 6, scope: !11)
!116 = !{!117}
!117 = distinct !{!117, !118, !"sorbet_buildArrayIntrinsic: argument 0"}
!118 = distinct !{!118, !"sorbet_buildArrayIntrinsic"}
